//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOutputStream.h"

@class BHSocketStream, NSError, NSRunLoop, NSString;

@interface __CURLOutputStream : NSOutputStream
{
    BHSocketStream *_stream;
    id <NSStreamDelegate> _delegate;
    NSRunLoop *_runloop;
    NSString *_runloopMode;
    unsigned long long _streamStatus;
    BOOL _hasSpaceAvailable;
    NSError *_outpuStreamError;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)_switchOutputStreamStatus:(unsigned long long)arg1;
- (void)_tryWaiting;
- (long long)write:(const char *)arg1 maxLength:(unsigned long long)arg2;
- (BOOL)hasSpaceAvailable;
- (void)close;
- (void)open;
- (id)streamError;
- (unsigned long long)streamStatus;
- (void)removeFromRunLoop:(id)arg1 forMode:(id)arg2;
- (void)scheduleInRunLoop:(id)arg1 forMode:(id)arg2;
- (id)propertyForKey:(id)arg1;
- (BOOL)setProperty:(id)arg1 forKey:(id)arg2;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (id)initWithStream:(id)arg1;

@end

