//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSComboBoxDelegate.h"

@class BHProfileModel, EIMButton, MQAvatarImageView, NSButton, NSComboBox, NSImageView, NSMutableArray, NSString, NSTextField, TChatMenuController;

@interface AddAContactController : NSWindowController <NSComboBoxDelegate>
{
    unsigned long long m_dwUin;
    NSTextField *textNickName;
    NSTextField *textValidateTip;
    NSTextField *textValidateInfo;
    NSTextField *textQuestionLabel;
    NSTextField *textQuestion_0;
    NSTextField *textQuestion_1;
    NSTextField *textQuestion_2;
    NSTextField *textAnswer_0;
    NSTextField *textAnswer_1;
    NSTextField *textAnswer_2;
    NSComboBox *comboFolder;
    NSButton *mBtnSend;
    NSTextField *textFolderLable;
    NSTextField *textDisplayName;
    NSTextField *textDisplayNameLable;
    NSTextField *limitTip;
    NSTextField *errorText;
    EIMButton *_popUpButton;
    NSMutableArray *_menuGroupDataSource;
    TChatMenuController *_menuGroup;
    long long folderId;
    MQAvatarImageView *headImage;
    NSTextField *locationText;
    NSImageView *locationImg;
    _Bool mIsSaveDefaultFrame;
    struct CGRect mTextValidateInfoRect;
    struct CGRect mTextFolderLableRect;
    struct CGRect mComboFolderRect;
    struct CGRect mWindowRect;
    struct CGRect mTextDisplayNameRect;
    struct CGRect mTextDisplayNameLabelRect;
    NSString *m_strQuestion;
    int m_bQuestion;
    int m_bMulQuestion;
    NSMutableArray *m_arrMulQuestion;
    _Bool m_bShowOnWindow;
    _Bool m_bLastOpenOnWindow;
    BOOL m_bHadShowLimitTip;
    BHProfileModel *_profileModel;
    long long _sourceId;
    double _groupUin;
}

+ (id)sharedAddAContactController;
@property(nonatomic) double groupUin; // @synthesize groupUin=_groupUin;
@property(nonatomic) long long sourceId; // @synthesize sourceId=_sourceId;
@property(retain, nonatomic) BHProfileModel *profileModel; // @synthesize profileModel=_profileModel;
- (void).cxx_destruct;
- (void)reachLimit:(id)arg1;
- (void)showLimitTip:(id)arg1;
- (void)preDisplay;
- (void)setShowOnWindow:(_Bool)arg1;
- (void)hideQuestionLabel:(int)arg1;
- (void)ShowMulQuestionView:(id)arg1;
- (void)ShowQuestionView:(id)arg1;
- (void)OnCancel:(id)arg1;
- (void)sheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)ShowView;
- (void)hideView;
- (void)ShowAddContactSheet;
- (void)saveDefaultFrame;
- (void)showErrorText:(id)arg1;
- (void)reset;
- (void)OnAddContact:(id)arg1;
- (unsigned long long)getFolderId;
- (id)getValidateMessage;
- (id)answerArray;
- (void)textDidChange:(id)arg1;
- (void)comboBoxWillPopUp:(id)arg1;
- (void)onClickPopMenu:(id)arg1;
- (void)awakeFromNib;
- (void)_setSendBtnEnable:(BOOL)arg1;
- (void)refreshFolder;
- (void)dealloc;
- (void)windowDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

