//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FileMessageUploadTransferTask.h"

@interface AirCopyDiscussGroupFileTransferTask : FileMessageUploadTransferTask
{
}

- (void)_request0X345_0x6_ApplyTransFile;
- (void)_request0X345_0x5_ApplyCopyFile;
- (void)onDoPreprocess;
- (void)onDoTransfer;
- (void)onDoPrepare;

@end

