//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface AVSessionMgr : NSObject
{
    NSMutableArray *_sessionDic;
}

+ (id)getInstance;
- (void)onDAVSDKEvent:(id)arg1;
- (void)onMAVSDKEvent:(id)arg1;
- (id)DAVSessionOfUin:(unsigned long long)arg1;
- (BOOL)cleanSessionsPMD:(struct AV_ID)arg1;
- (BOOL)cleanAllSessionsPMD;
- (id)getCurrentSession;
- (void)removeAllSessions;
- (id)getSession:(struct AV_ID)arg1;
- (void)dealloc;
- (id)init;

@end

