//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CADisplayLink, NSMutableArray, NSRecursiveLock, NSRunLoop, NSThread, QQBlueThread;

@interface BaseFrameMonitor : NSObject
{
    unsigned int _threadid;
    NSRecursiveLock *_lock;
    vector_c9646404 _stuckFrames;
    struct CThreadMonitor _monitor;
    BOOL _frameMonitorOpen;
    BOOL _dlMonitorOpen;
    double _dlTime;
    BOOL _needDetailWhenDl;
    unsigned int _stuckFlag;
    unsigned int _frames;
    double _dropFrameTime;
    double _perFrameTime;
    NSRunLoop *_runloop;
    NSThread *_thread;
    id _excb;
    NSMutableArray *_observers;
    CADisplayLink *_mainCaLink;
    CADisplayLink *_capCaLink;
    QQBlueThread *_captureThread;
    double _lastRefreshTime;
    id _callback;
    id _dlCallback;
}

@property(copy) id dlCallback; // @synthesize dlCallback=_dlCallback;
@property(copy) id callback; // @synthesize callback=_callback;
@property(nonatomic) double lastRefreshTime; // @synthesize lastRefreshTime=_lastRefreshTime;
@property(retain, nonatomic) QQBlueThread *captureThread; // @synthesize captureThread=_captureThread;
@property(retain, nonatomic) CADisplayLink *capCaLink; // @synthesize capCaLink=_capCaLink;
@property(retain, nonatomic) CADisplayLink *mainCaLink; // @synthesize mainCaLink=_mainCaLink;
@property(retain, nonatomic) NSMutableArray *observers; // @synthesize observers=_observers;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onExceptionData:(id)arg1;
- (void)setThreadRunloop:(id)arg1 thread:(id)arg2;
- (void)setThreadId:(unsigned int)arg1;
- (void)setFrameInterval:(long long)arg1;
- (void)setThreshold:(double)arg1;
- (void)setupCADisplayLink;
- (void)invalidCALink;
- (void)stopCALink;
- (void)stopDeadLockMonitor;
- (void)onFrameRefreshCap;
- (BOOL)shouldCaptureStack;
- (void)onFrameRefreshMain;
- (void)stop;
- (void)startWithCallback:(id)arg1;
- (void)startDeadLockMonitor:(id)arg1 needDetail:(BOOL)arg2;
- (void)dealloc;
- (id)init;

@end

