//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString, NSTimer;

@interface BDHConnection : NSObject
{
    int _sessionID;
    NSString *_ip;
    long long _port;
    id <BDHConnectionDelegate> _delegate;
    NSTimer *_timer;
    NSMutableArray *_writeQueue;
    NSString *_realIp;
    int _maxPacketSize;
    int _connectTime;
}

@property(nonatomic) int connectTime; // @synthesize connectTime=_connectTime;
@property(retain, nonatomic) NSString *realIp; // @synthesize realIp=_realIp;
@property(retain, nonatomic) NSMutableArray *writeQueue; // @synthesize writeQueue=_writeQueue;
@property(nonatomic) id <BDHConnectionDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long port; // @synthesize port=_port;
@property(retain, nonatomic) NSString *ip; // @synthesize ip=_ip;
@property(nonatomic) int sessionID; // @synthesize sessionID=_sessionID;
- (BOOL)isValidDataHead:(const char *)arg1 len:(int)arg2;
- (id)getRemoteIPAddress;
- (void)sendTimeout;
- (int)inputStreamStatus;
- (void)clearDelegate;
- (BOOL)IsConnected;
- (void)insertPacketToPriorityQueue:(id)arg1;
- (void)DisConnect;
- (int)send:(id)arg1 tag:(long long)arg2;
- (void)connect:(id)arg1 port:(long long)arg2 timeout:(long long)arg3;
- (int)connectionType;
- (id)init;
- (void)dealloc;

@end

