//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BDHSessionInfo : NSObject
{
    int _port;
    int _ret;
    int _connectTime;
    NSString *_ip;
}

+ (id)infoWithIP:(id)arg1 port:(int)arg2 ret:(int)arg3 contime:(int)arg4;
@property(nonatomic) int connectTime; // @synthesize connectTime=_connectTime;
@property(nonatomic) int ret; // @synthesize ret=_ret;
@property(nonatomic) int port; // @synthesize port=_port;
@property(retain, nonatomic) NSString *ip; // @synthesize ip=_ip;
- (void)dealloc;

@end

