//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQModel_Internal.h"

@class BHCollectionStyle, NSString;

@interface BHCollectionParagraph : QQModel_Internal
{
    NSString *_content;
    BHCollectionStyle *_style;
}

@property(retain, nonatomic) BHCollectionStyle *style; // @synthesize style=_style;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;

@end

