//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BHHistoryFileDataSource : NSObject
{
    unsigned int _maxMsgId;
    int _sessType;
    long long _uin;
    unsigned long long _fileType;
}

+ (id)compatibleConditionWithUin:(long long)arg1 sessType:(int)arg2 fileType:(unsigned long long)arg3 maxMsgId:(int)arg4 start:(long long)arg5 count:(long long)arg6;
+ (id)conditionWithUin:(long long)arg1 sessType:(int)arg2 fileType:(unsigned long long)arg3 maxMsgId:(int)arg4 start:(long long)arg5 count:(long long)arg6;
@property(nonatomic) unsigned long long fileType; // @synthesize fileType=_fileType;
@property(nonatomic) int sessType; // @synthesize sessType=_sessType;
@property(nonatomic) long long uin; // @synthesize uin=_uin;
- (void)getMessageWithFromIndex:(int)arg1 count:(int)arg2 completion:(id)arg3;
- (id)initWithUin:(long long)arg1 sessType:(int)arg2 fileType:(unsigned long long)arg3;

@end

