//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BHSSORequest.h"

@interface BHJCERequest : BHSSORequest
{
}

- (id)initWithServiceCommand:(id)arg1 andJCEPacket:(UniPacket_625f2f0c)arg2;

@end

