//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface BHLoginDeviceModel : NSObject
{
    BOOL _canBeKicked;
    BOOL _isCurrentDevice;
    unsigned long long _appID;
    NSData *_guid;
    unsigned long long _loginTime;
    unsigned long long _platform;
    NSString *_location;
    NSString *_deviceName;
    NSString *_deviceInfo;
    unsigned long long _terminalType;
    NSData *_deviceItemDes;
}

@property(retain, nonatomic) NSData *deviceItemDes; // @synthesize deviceItemDes=_deviceItemDes;
@property(nonatomic) BOOL isCurrentDevice; // @synthesize isCurrentDevice=_isCurrentDevice;
@property(nonatomic) BOOL canBeKicked; // @synthesize canBeKicked=_canBeKicked;
@property(nonatomic) unsigned long long terminalType; // @synthesize terminalType=_terminalType;
@property(copy, nonatomic) NSString *deviceInfo; // @synthesize deviceInfo=_deviceInfo;
@property(copy, nonatomic) NSString *deviceName; // @synthesize deviceName=_deviceName;
@property(copy, nonatomic) NSString *location; // @synthesize location=_location;
@property(nonatomic) unsigned long long platform; // @synthesize platform=_platform;
@property(nonatomic) unsigned long long loginTime; // @synthesize loginTime=_loginTime;
@property(retain, nonatomic) NSData *guid; // @synthesize guid=_guid;
@property(nonatomic) unsigned long long appID; // @synthesize appID=_appID;
- (void).cxx_destruct;

@end

