//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BHMessageContent.h"

@class NSString;

@interface BHMessageContentPTT : BHMessageContent
{
    unsigned int _duration;
    unsigned int _format;
    unsigned int _fileType;
    unsigned int _fileLength;
    NSString *_filename;
    NSString *_UUID;
    NSString *_MD5;
    NSString *_fileKey;
}

@property(copy, nonatomic) NSString *fileKey; // @synthesize fileKey=_fileKey;
@property(copy, nonatomic) NSString *MD5; // @synthesize MD5=_MD5;
@property(copy, nonatomic) NSString *UUID; // @synthesize UUID=_UUID;
@property(copy, nonatomic) NSString *filename; // @synthesize filename=_filename;
@property(nonatomic) unsigned int fileLength; // @synthesize fileLength=_fileLength;
@property(nonatomic) unsigned int fileType; // @synthesize fileType=_fileType;
@property(nonatomic) unsigned int format; // @synthesize format=_format;
@property(nonatomic) unsigned int duration; // @synthesize duration=_duration;
- (void).cxx_destruct;
- (id)contentString;
- (id)initWithContent:(id)arg1;

@end

