//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

#import "QQAccountEventObserver.h"
#import "SlaveQQAccountEventObserver.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface BHMsgListManager : QQBaseSingleton <QQAccountEventObserver, SlaveQQAccountEventObserver>
{
    NSMutableDictionary *_msgDict;
    NSMutableArray *_removeArray;
    NSMutableDictionary *_unreadCountDict;
    long long _appType;
    NSArray *_tmpMsgList;
}

+ (id)msgListManagerWithAccount:(unsigned long long)arg1;
@property(readonly, copy, nonatomic) NSArray *removeArray; // @synthesize removeArray=_removeArray;
- (void).cxx_destruct;
- (void)onMessageSendingResult:(id)arg1;
- (void)onRefreshUnreadCountWhenGetMessage:(id)arg1;
- (void)onGetMessage:(id)arg1;
- (id)loadRecentModel:(id)arg1 sessionType:(int)arg2;
- (void)removeAllRecentModels;
- (void)removeRecentModel:(id)arg1;
- (void)setUnreadCount:(int)arg1 toUin:(id)arg2 type:(int)arg3;
- (void)recallMessage:(id)arg1;
- (void)addLocalMessage:(id)arg1 addUnread:(int)arg2 isReset:(BOOL)arg3;
- (id)getRecentModelByUin:(id)arg1 msgSessionType:(int)arg2;
@property(readonly, nonatomic) NSArray *recentMsgList;
- (id)init;
- (void)doSyncSystemUnreadCount:(id)arg1;
- (int)_caculateTroopUnreadCountByGroupCode:(id)arg1 memberSeq:(unsigned long long)arg2 maxSeq:(unsigned long long)arg3;
- (void)doSyncTroopUnreadCount:(id)arg1 memberSeq:(unsigned long long)arg2 maxSeq:(unsigned long long)arg3;
- (int)_caculateC2CUnreadCountByUin:(id)arg1 lastReadTime:(unsigned long long)arg2;
- (void)doSyncC2CUnreadCount:(id)arg1 lastReadedTime:(unsigned long long)arg2;
- (void)_updateUnreadCountWhenReceiveMsgs:(id)arg1;
- (id)msgListRemovedKeyPath;
- (void)deleteRemovedKeyByMessageModel:(id)arg1;
- (void)addRemovedKeys:(id)arg1;
- (void)addRemovedKeyByMessageModel:(id)arg1;
- (id)currentAccount;
- (BOOL)isValidMessageModel:(id)arg1;
- (void)notifyUI4MsgListChangedWithUserInfo:(id)arg1;
- (void)clearTmpCache;
- (void)loadMessageListFromDB;
- (BOOL)_mergeOldUnreadCountFromLocal4Ipad;
- (void)loadHistoryUnreadCountFromLocal;
- (void)saveRecentHistoryUnreadCountRightAway;
- (void)saveRecentHistoryUnreadCount;
- (long long)_covertMsgSource:(long long)arg1;
- (int)getUnreadMessageCount:(id)arg1 type:(int)arg2;
- (void)updateMessageCache:(id)arg1 messageKey:(id)arg2;
- (void)removeMessageFromCache:(id)arg1;
- (id)getMessageFromCache:(id)arg1;
- (id)_createRecentMessageModelWith:(id)arg1 causedBy:(long long)arg2;
- (id)createRecentMessageModelWith:(id)arg1 causedBy:(long long)arg2;
- (void)addMessage:(id)arg1;
- (void)updateMessageSendState:(id)arg1;
- (id)getRecentMsgList;
- (id)getMessageKey:(id)arg1 type:(int)arg2;
- (id)getMessageKey:(id)arg1;
- (void)onSlaveQQDidChangeAccount;
- (void)onDidChangeAccount;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

