//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

@class NSMutableArray;

@interface BHMsgHandler : QQBaseSingleton
{
    NSMutableArray *_handlerArray;
}

@property(retain, nonatomic) NSMutableArray *handlerArray; // @synthesize handlerArray=_handlerArray;
- (void).cxx_destruct;
- (BOOL)handleMsg:(out id)arg1 pbMsg:(const struct Msg *)arg2;
- (BOOL)isDuplicateMsg:(id)arg1 duplicate:(char *)arg2;
- (BOOL)preHandleMsg:(id)arg1 pbMsg:(const struct Msg *)arg2;
- (BOOL)p2p_PreParsePbMsg:(id)arg1 pbMsg:(const struct Msg *)arg2;
- (BOOL)preParsePbMsg:(id)arg1 PbMsg:(const struct Msg *)arg2;
- (void)unregisterMsgHandler:(id)arg1;
- (void)registerMsgHandler:(id)arg1;
- (id)init;

@end

