//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface BHProfileModel : NSObject
{
    BOOL _isVIP;
    BOOL _isSVIP;
    BOOL _isYearVIP;
    unsigned char _VIPLevel;
    unsigned int _age;
    unsigned int _QQAge;
    unsigned int _birthdayYear;
    unsigned int _birthdayMonth;
    unsigned int _birthdayDay;
    unsigned int _counrtyID;
    unsigned int _proviceID;
    unsigned int _cityID;
    unsigned int _qzoneID;
    unsigned int _hometownCountryID;
    unsigned int _hometownProvinceID;
    unsigned int _hometownCityID;
    unsigned int _hometownZoneID;
    unsigned int _zodiac;
    unsigned int _occupation;
    unsigned int _bubbleID;
    NSString *_uin;
    long long _gender;
    NSString *_nick;
    NSString *_signature;
    long long _constellation;
    long long _bloodType;
    NSString *_email;
    NSString *_company;
    NSString *_school;
    NSString *_introduction;
    NSString *_homepage;
    NSString *_phoneNumber;
    NSString *_cellphoneNumber;
    long long _addFriendSetting;
    NSArray *_addFriendQA;
    NSArray *_addFriendQuestions;
    NSString *_coverURL;
    NSString *_primaryDisplayAccount;
    NSString *_profileJSONString;
}

@property(copy, nonatomic) NSString *profileJSONString; // @synthesize profileJSONString=_profileJSONString;
@property(copy, nonatomic) NSString *primaryDisplayAccount; // @synthesize primaryDisplayAccount=_primaryDisplayAccount;
@property(nonatomic) unsigned int bubbleID; // @synthesize bubbleID=_bubbleID;
@property(nonatomic) unsigned char VIPLevel; // @synthesize VIPLevel=_VIPLevel;
@property(nonatomic) BOOL isYearVIP; // @synthesize isYearVIP=_isYearVIP;
@property(nonatomic) BOOL isSVIP; // @synthesize isSVIP=_isSVIP;
@property(nonatomic) BOOL isVIP; // @synthesize isVIP=_isVIP;
@property(copy, nonatomic) NSString *coverURL; // @synthesize coverURL=_coverURL;
@property(copy, nonatomic) NSArray *addFriendQuestions; // @synthesize addFriendQuestions=_addFriendQuestions;
@property(copy, nonatomic) NSArray *addFriendQA; // @synthesize addFriendQA=_addFriendQA;
@property(nonatomic) long long addFriendSetting; // @synthesize addFriendSetting=_addFriendSetting;
@property(copy, nonatomic) NSString *cellphoneNumber; // @synthesize cellphoneNumber=_cellphoneNumber;
@property(copy, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(copy, nonatomic) NSString *homepage; // @synthesize homepage=_homepage;
@property(copy, nonatomic) NSString *introduction; // @synthesize introduction=_introduction;
@property(copy, nonatomic) NSString *school; // @synthesize school=_school;
@property(copy, nonatomic) NSString *company; // @synthesize company=_company;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(nonatomic) unsigned int occupation; // @synthesize occupation=_occupation;
@property(nonatomic) long long bloodType; // @synthesize bloodType=_bloodType;
@property(nonatomic) unsigned int zodiac; // @synthesize zodiac=_zodiac;
@property(nonatomic) long long constellation; // @synthesize constellation=_constellation;
@property(nonatomic) unsigned int hometownZoneID; // @synthesize hometownZoneID=_hometownZoneID;
@property(nonatomic) unsigned int hometownCityID; // @synthesize hometownCityID=_hometownCityID;
@property(nonatomic) unsigned int hometownProvinceID; // @synthesize hometownProvinceID=_hometownProvinceID;
@property(nonatomic) unsigned int hometownCountryID; // @synthesize hometownCountryID=_hometownCountryID;
@property(nonatomic) unsigned int qzoneID; // @synthesize qzoneID=_qzoneID;
@property(nonatomic) unsigned int cityID; // @synthesize cityID=_cityID;
@property(nonatomic) unsigned int proviceID; // @synthesize proviceID=_proviceID;
@property(nonatomic) unsigned int counrtyID; // @synthesize counrtyID=_counrtyID;
@property(nonatomic) unsigned int birthdayDay; // @synthesize birthdayDay=_birthdayDay;
@property(nonatomic) unsigned int birthdayMonth; // @synthesize birthdayMonth=_birthdayMonth;
@property(nonatomic) unsigned int birthdayYear; // @synthesize birthdayYear=_birthdayYear;
@property(nonatomic) unsigned int QQAge; // @synthesize QQAge=_QQAge;
@property(copy, nonatomic) NSString *signature; // @synthesize signature=_signature;
@property(copy, nonatomic) NSString *nick; // @synthesize nick=_nick;
@property(nonatomic) unsigned int age; // @synthesize age=_age;
@property(nonatomic) long long gender; // @synthesize gender=_gender;
@property(copy, nonatomic) NSString *uin; // @synthesize uin=_uin;
- (void).cxx_destruct;
@property(nonatomic) unsigned int birthday;
- (id)description;
@property(readonly) NSString *displayName;
- (id)initWithUIN:(id)arg1 JsonString:(id)arg2;
- (id)initWithUIN:(id)arg1;

@end

