//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MsfSDK, NSString, __MSFSDKCallback;

@interface BHSSOSession : NSObject
{
    MsfSDK *_MSFSDK;
    __MSFSDKCallback *_SDKCallback;
    id _callback;
    long long _appID;
}

+ (id)sharedSession;
@property(readonly, nonatomic) long long appID; // @synthesize appID=_appID;
@property(retain, nonatomic) id callback; // @synthesize callback=_callback;
- (void).cxx_destruct;
- (long long)sendRequest:(id)arg1 completion:(id)arg2;
- (id)hostArrayByDomainName:(id)arg1;
- (void)switchIPAddress:(id)arg1;
- (id)date;
@property(readonly, nonatomic) int serverTimeDiff;
@property(readonly, nonatomic) NSString *SSO_IP_Port;
@property(readonly, nonatomic) NSString *clientIP;
- (void)disconnect;
- (void)connect;
- (BOOL)connected;
- (void)setAppID:(long long)arg1 andAppSignature:(id)arg2;
- (void)setAppID:(long long)arg1 andAppBundle:(id)arg2 andAppVersion:(id)arg3;
@property(readonly, nonatomic) id MSFSDK;
- (long long)sendJCERequest:(id)arg1 completion:(id)arg2;
- (long long)sendOIDBRequest:(id)arg1 completion:(id)arg2;

@end

