//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BHStructMessagePicture.h"

@class NSString;

@interface BHStructMessageAudio : BHStructMessagePicture
{
    NSString *_src;
}

@property(copy, nonatomic) NSString *src; // @synthesize src=_src;
- (void).cxx_destruct;
- (id)node;
- (id)elementName;

@end

