//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDate, NSNumber, NSString;

@interface BHTipsMsgOption : NSObject
{
    BOOL _addToDb;
    BOOL _addToMsgList;
    BOOL _addUnRead;
    BOOL _inOut;
    int _tipsType;
    NSString *_nickName;
    NSString *_groupCode;
    NSString *_discussGroupUin;
    NSNumber *_msgSeq;
    NSString *_authKey;
    NSData *_pc_body;
    NSString *_senderUin;
    NSDate *_msgDate;
}

@property(retain, nonatomic) NSDate *msgDate; // @synthesize msgDate=_msgDate;
@property(copy, nonatomic) NSString *senderUin; // @synthesize senderUin=_senderUin;
@property(nonatomic) BOOL inOut; // @synthesize inOut=_inOut;
@property(copy, nonatomic) NSData *pc_body; // @synthesize pc_body=_pc_body;
@property(copy, nonatomic) NSString *authKey; // @synthesize authKey=_authKey;
@property(retain, nonatomic) NSNumber *msgSeq; // @synthesize msgSeq=_msgSeq;
@property(retain, nonatomic) NSString *discussGroupUin; // @synthesize discussGroupUin=_discussGroupUin;
@property(retain, nonatomic) NSString *groupCode; // @synthesize groupCode=_groupCode;
@property(nonatomic) int tipsType; // @synthesize tipsType=_tipsType;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(nonatomic) BOOL addUnRead; // @synthesize addUnRead=_addUnRead;
@property(nonatomic) BOOL addToMsgList; // @synthesize addToMsgList=_addToMsgList;
@property(nonatomic) BOOL addToDb; // @synthesize addToDb=_addToDb;
- (void).cxx_destruct;
- (id)init;

@end

