//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextFieldCell.h"

@class NSImage, NSString;

@interface BuddyTableCell : NSTextFieldCell
{
    NSImage *iImage;
    NSString *iTitle;
    NSString *iExtraInfo;
    NSString *iCount;
}

- (void).cxx_destruct;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawExitedInfo:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawUinWithSearchCount:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawUinWithDate:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)exitedInfoRectForBounds:(struct CGRect)arg1;
- (struct CGRect)titleRectForBoundsInSearch:(struct CGRect)arg1;
- (struct CGRect)searchCountRectForBounds:(struct CGRect)arg1;
- (struct CGRect)searchBackgroundRectForBounds:(struct CGRect)arg1;
- (struct CGRect)dateRectForBounds:(struct CGRect)arg1;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;
- (id)attributedExitedInfo;
- (id)attributedSearchCount;
- (id)attributedDate;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setCount:(id)arg1;
- (id)count;
- (void)setExtraInfo:(id)arg1;
- (id)extraInfo;
- (void)setTitle:(id)arg1;
- (id)title;
- (void)setImage:(id)arg1;
- (id)image;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

