//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CollectionUtils : NSObject
{
}

+ (id)getCollectionFilePath:(id)arg1;
+ (id)getCollectionPttPath:(id)arg1;
+ (id)getCollectionPicPath:(id)arg1;
+ (id)getCollectionFileSaveDirectory;
+ (id)getCollectionPttSaveDirectory;
+ (id)getCollectionPicSaveDirectory;

@end

