//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CollectionFactory : NSObject
{
}

+ (id)_buildCollectionRichMeidaInfo:(const struct RichMedia *)arg1;
+ (void)fillCollectionFileInfo:(id)arg1 with:(const FileInfo_d8b73abd *)arg2;
+ (id)buildCollectionFileInfo:(const FileInfo_d8b73abd *)arg1;
+ (void)fillCollectionPicInfo:(id)arg1 with:(const struct PicInfo *)arg2;
+ (id)buildCollectionPicInfo:(const struct PicInfo *)arg1;
+ (id)buildCollectionAuthor:(const struct Author *)arg1;
+ (void)_unPackCollectionRichMediaContent:(id)arg1 content:(const struct RichMediaContent *)arg2;
+ (void)_unPackCollectionAudioContent:(id)arg1 content:(const struct AudioContent *)arg2 withCollection:(id)arg3;
+ (void)_unPackCollectionTextContent:(id)arg1 content:(const struct TextContent *)arg2;
+ (void)fillCollectionModel:(id)arg1 withType:(int)arg2 withCollectionContent:(const struct CollectionContent *)arg3;
+ (void)_unPackCollectionVideoSummary:(id)arg1 summary:(const struct VideoSummary *)arg2;
+ (void)_unPackCollectionRichMediaSummary:(id)arg1 summary:(const struct RichMediaSummary *)arg2;
+ (void)_unPackCollectionFileSummary:(id)arg1 summary:(const struct FileSummary *)arg2;
+ (void)_unPackCollectionLocationSummary:(id)arg1 summary:(const struct LocationSummary *)arg2;
+ (void)_unPackCollectionAudioSummary:(id)arg1 summary:(const struct AudioSummary *)arg2;
+ (void)_unPackCollectionGallerySummary:(id)arg1 summary:(const struct GallerySummary *)arg2;
+ (void)_unPackCollectionLinkSummary:(id)arg1 summary:(const struct LinkSummary *)arg2;
+ (void)_unPackCollectionTextSummary:(id)arg1 summary:(const struct TextSummary *)arg2;
+ (void)_fillCollectionModel:(id)arg1 withType:(int)arg2 withCollectionSummary:(const struct CollectionSummary *)arg3;
+ (id)createCollectionModelWithCollectionMsg:(const struct Collection *)arg1;

@end

