//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

#import "QQAccountEventObserver.h"

@class CompatibleC2CMsgTableOperation, CompatibleDiscussMsgTableOperation, CompatibleGroupMsgTableOperation, NSString;

@interface CompatibleMsgDBService : QQBaseSingleton <QQAccountEventObserver>
{
    BOOL hasiPadCompatibleDB;
    CompatibleC2CMsgTableOperation *_C2CDBOperation;
    CompatibleGroupMsgTableOperation *_groupDBOperation;
    CompatibleDiscussMsgTableOperation *_discussDBOperation;
}

- (void).cxx_destruct;
- (id)messageWithUin:(long long)arg1 sessType:(int)arg2 maxMsgID:(int)arg3 withCondition:(id)arg4 withArguments:(id)arg5;
- (id)messageIDsByDayWithUin:(long long)arg1 sessType:(int)arg2 maxMsgID:(int)arg3 withCondition:(id)arg4 withArguments:(id)arg5;
- (id)getAllTBFileRecord;
- (id)getRecentMsgWithSessType:(int)arg1 identityUin:(long long)arg2;
- (id)getClusterMessageWithUin:(long long)arg1 sessType:(int)arg2 endSeq:(int)arg3 count:(int)arg4;
- (id)getClusterMessageWithUin:(long long)arg1 sessType:(int)arg2 startSeq:(int)arg3 endSeq:(int)arg4;
- (int)getMessageMaxSeq:(long long)arg1 sessType:(int)arg2;
- (id)getC2CMessageList:(long long)arg1 identityUin:(long long)arg2 startTime:(int)arg3 endTime:(int)arg4;
- (id)getC2CMessageList:(long long)arg1 identityUin:(long long)arg2 endTime:(int)arg3 exceptMsgId:(int)arg4 exceptBlankMsg:(BOOL)arg5 count:(unsigned int)arg6;
- (id)getMessageWithUin:(long long)arg1 sessType:(int)arg2 msgIds:(id)arg3;
- (id)mergeMessageSessType:(int)arg1 msgArray:(id)arg2 additionalMsg:(id)arg3 limitCount:(int)arg4;
- (id)mergeRecentMsgListSessType:(int)arg1 msgArray:(id)arg2 additionalMsg:(id)arg3;
- (int)getMaxMsgId:(long long)arg1 sessType:(int)arg2;
- (void)deleteMsgDBFile;
- (BOOL)deleteAllMsgsWithUin:(long long)arg1 sessType:(int)arg2 identityUin:(long long)arg3;
- (BOOL)deleteMessage:(id)arg1 containLargeMsg:(BOOL)arg2;
- (id)operationWithSessType:(int)arg1;
- (void)onDidChangeAccount;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

