//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class CornerImageView, NSImage, NSImageView;

@interface CornerChooseVIew : NSView
{
    CornerImageView *leftTopView;
    CornerImageView *rightTopView;
    CornerImageView *rightBottomView;
    CornerImageView *leftBottomView;
    NSImageView *blackImageView;
    NSImage *blackImage;
    NSImageView *backGroundView;
    struct CGRect leftTopRect;
    struct CGRect rightTopRect;
    struct CGRect rightBottomRect;
    struct CGRect leftBottomRect;
    NSImage *leftTopImage;
    NSImage *rightTopImage;
    NSImage *rightBottomImage;
    NSImage *leftBottomImage;
}

- (void).cxx_destruct;
- (id)rotatePicture:(id)arg1 degreses:(int)arg2;
- (void)onClickCorner:(int)arg1;
- (void)awakeFromNib;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

