//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@class NSMutableDictionary;

@interface CVWindow : NSWindow
{
    NSMutableDictionary *sliders;
    CDUnknownFunctionPointerType mouseCallback;
    void *mouseParam;
    BOOL autosize;
    BOOL firstContent;
    int status;
}

@property int status; // @synthesize status;
@property(retain) NSMutableDictionary *sliders; // @synthesize sliders;
@property BOOL firstContent; // @synthesize firstContent;
@property BOOL autosize; // @synthesize autosize;
@property void *mouseParam; // @synthesize mouseParam;
@property CDUnknownFunctionPointerType mouseCallback; // @synthesize mouseCallback;
- (id)contentView;
- (void)createSliderWithName:(const char *)arg1 maxValue:(int)arg2 value:(int *)arg3 callback:(CDUnknownFunctionPointerType)arg4;
- (void)mouseDown:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)otherMouseDown:(id)arg1;
- (void)otherMouseUp:(id)arg1;
- (void)otherMouseDragged:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)rightMouseUp:(id)arg1;
- (void)rightMouseDragged:(id)arg1;
- (void)keyDown:(id)arg1;
- (void)cvMouseEvent:(id)arg1;
- (void)cvSendMouseEvent:(id)arg1 type:(int)arg2 flags:(int)arg3;

@end

