//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IEngineDispatchDelegate.h"
#import "IQQMessageProcessor.h"

@class DiscussGroupMsgReadStorage, NSMutableArray, NSMutableDictionary, NSString;

@interface DiscussGroupChatEngine : NSObject <IEngineDispatchDelegate, IQQMessageProcessor>
{
    NSMutableArray *_sendingMsgQueue;
    NSMutableDictionary *_msgCacheDict;
    NSMutableDictionary *_lastTipArray;
    NSMutableDictionary *_excessMsgDic;
    NSMutableDictionary *_disSeqResultListDict;
    DiscussGroupMsgReadStorage *_msgReadStorage;
    NSMutableDictionary *_requestCountDic;
    int soundTime;
    NSMutableDictionary *_recordTipsFlag;
    BOOL _isNeedAudioTip;
}

+ (id)getInstance;
@property(nonatomic) BOOL isNeedAudioTip; // @synthesize isNeedAudioTip=_isNeedAudioTip;
- (void).cxx_destruct;
- (id)processMsgEncapsulation:(id)arg1;
- (id)getDiscussGroupReadStorage;
- (void)notifyError:(id)arg1;
- (void)didRecievedMsg:(CDStruct_a00ab4be)arg1;
- (void)onGetRoamDiscussGroupMsg:(id)arg1;
- (void)responseDiscussGroupMsg:(char *)arg1 DataLen:(int)arg2;
- (void)requestDiscussGroupMsg:(long long)arg1 endSeq:(long long)arg2 beginSeq:(long long)arg3 completion:(id)arg4;
- (void)requestDiscussGroupMsg:(long long)arg1 endSeq:(long long)arg2 beginSeq:(long long)arg3;
- (void)perform_handleAsyncGetDiscussGroupMsg:(unsigned long long)arg1 beforeSeq:(unsigned long long)arg2 msgArray:(id)arg3;
- (void)_requestDiscussGroupMsg:(long long)arg1 endSeq:(long long)arg2 beginSeq:(long long)arg3;
- (void)responseDiscussGroupMsgCount:(char *)arg1 DataLen:(int)arg2;
- (void)requestDiscussGroupMsgCount:(BOOL)arg1 DiscussGroupGroups:(id)arg2;
- (void)_clearRequestCountOfDiscuss:(id)arg1;
- (void)_increaseRequestCountOfDiscuss:(id)arg1;
- (unsigned long long)_requestCountOfDiscuss:(id)arg1;
- (id)getRecentMessage:(id)arg1 resultArray:(id)arg2;
- (id)getFirstPieceFromMultiMsg:(id)arg1;
- (int)parseSetMsgRead:(char *)arg1 dataLen:(int)arg2 response:(struct SvcResponseSetConfMsgRead *)arg3;
- (int)parseMsgDel:(char *)arg1 dataLen:(int)arg2 response:(struct SvcResponseDelDisMsg *)arg3;
- (char *)getDelMsgBuffer:(vector_fbf08522 *)arg1;
- (int)parseGetDiscussGroupMsg:(char *)arg1 dataLen:(int)arg2 response:(struct SvcResponseGetConfMsg *)arg3;
- (char *)getDiscussGroupMsgBuffer:(long long)arg1 BeginSeq:(long long)arg2 EndSeq:(long long)arg3;
- (int)parseResponsePullDisGroupSeq:(char *)arg1 dataLen:(int)arg2 response:(struct SvcResponsePullDisGroupSeq *)arg3;
- (int)parseGetDiscussGroupMsgSeq:(char *)arg1 dataLen:(int)arg2 response:(struct SvcResponsePullDisMsgSeq *)arg3;
- (char *)getDiscussGroupMsgSeqBuffer:(vector_6cfd7a25)arg1 verifyType:(BOOL)arg2;
- (int)parseGetDiscussGroupMsgNum:(char *)arg1 dataLen:(int)arg2 response:(struct SvcResponseGetConfMsgNum *)arg3;
- (char *)getDiscussGroupMsgNumBuffer:(vector_51758e2a)arg1 verifyType:(BOOL)arg2;
- (void)onDiscussGroupMessageReadNotify:(id)arg1;
- (void)clearTipMsgCache:(unsigned long long)arg1;
- (BOOL)addNotifyMsg:(long long)arg1 msgModel:(id)arg2 type:(int)arg3;
- (id)parseChangeDiscussNameTipMsg:(unsigned long long)arg1 msgData:(char *)arg2 withNickName:(id)arg3;
- (id)parsePrivacyTipMsg:(unsigned long long)arg1 msgData:(char *)arg2 withNickNames:(id)arg3;
- (id)parseTipMsg:(unsigned long long)arg1 cmdUIN:(unsigned long long)arg2 opType:(int)arg3 memArray:(id)arg4 extCmd:(int)arg5;
- (void)notifyRegProxyDiscussGroupSeq:(unsigned long long)arg1 memberSeq:(unsigned long long)arg2 maxSeq:(unsigned long long)arg3 target:(unsigned long long)arg4;
- (void)changeAccount;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

