//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EEImageComposer;

@interface EmotionEggsHandler : NSObject
{
    EEImageComposer *composer;
}

+ (id)shareHandler;
- (void).cxx_destruct;
- (id)allCaseComposeLayer:(id)arg1 scene:(id)arg2 baseImage:(id)arg3 uins:(id)arg4 currentIndex:(unsigned long long *)arg5;
- (id)generateEmotionWith:(id)arg1 uins:(id)arg2;
- (void)generateAllCaseEmotions;
- (id)allCaseComposeLayer:(id)arg1 scene:(id)arg2;
- (void)calculationSceneRandomSalt:(id)arg1;
- (long long)calculationAllSceneRandomSalt;
- (id)composeLayer:(id)arg1 scene:(id)arg2 baseImage:(id)arg3 uins:(id)arg4 currentIndex:(unsigned long long *)arg5;
- (id)generateEmotionWith:(id)arg1 sessionID:(id)arg2 uins:(id)arg3;
- (void)asyncGetEmotionsWithSessionID:(id)arg1 keyWord:(id)arg2 uins:(id)arg3 isAtCase:(BOOL)arg4 generatedBlock:(id)arg5;
- (id)getEmotionsWithSessionID:(id)arg1 keyWord:(id)arg2 uins:(id)arg3 isAtCase:(BOOL)arg4 sceneMode:(long long *)arg5;
- (id)matchedSceneWith:(id)arg1 uins:(id)arg2 isAtCase:(BOOL)arg3;
- (long long)supportMaxCount;
- (BOOL)hasEmotionEggsWithUins:(id)arg1;
- (id)keyWords;
- (unsigned long long)activityEntry;
- (id)activityTips;
- (id)activitySmallIcon;
- (id)activityLargeIcon;
- (id)activityIcon;
- (id)init;

@end

