//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTokenField;

@protocol ExtendedTokenFieldViewDelegate <NSObject>
- (void)setAbleHandleFirstResponderEvent:(BOOL)arg1;
- (BOOL)ableHandleFirstResponderEvent;
- (void)tokenFiledRecviedMousedown:(id)arg1;
- (BOOL)tokenField:(NSTokenField *)arg1 onCommand:(int)arg2;
@end

