//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FATaskInfoDownload, NSDate, NSError, NSMutableArray, NSMutableData, NSMutableURLRequest, NSString, NSURLConnection;

@interface FADownHttp : NSObject
{
    NSString *_tmpfileName;
    NSMutableURLRequest *_urlRequest;
    NSMutableArray *_arURL;
    FATaskInfoDownload *_fileInfo;
    BOOL _isLastHttpTry;
    int _alltryCount;
    int _tryCount;
    NSURLConnection *_connection;
    BOOL _bStop;
    int _ftnRetCode;
    int _httpStatusCode;
    NSMutableData *_responseData;
    unsigned long long _localFileSize;
    unsigned long long _realTransSize;
    NSDate *_lastNotifyTime;
    double _taskStartTime;
    int _logId;
    int _lastFailCode;
    NSString *_lastErrorDisc;
    BOOL _isWriteDataFail;
    NSString *_dataReportId;
    NSString *_dataReportDetailId;
    int _nextUrlRetryFlag;
    NSError *_globalErrInfo;
    id <FADownHttpDelegate> _delegate;
}

@property(nonatomic) __weak id <FADownHttpDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *dataReportDetailId; // @synthesize dataReportDetailId=_dataReportDetailId;
@property(copy, nonatomic) NSString *dataReportId; // @synthesize dataReportId=_dataReportId;
@property(retain, nonatomic) FATaskInfoDownload *fileInfo; // @synthesize fileInfo=_fileInfo;
@property(retain, nonatomic) NSMutableData *responseData; // @synthesize responseData=_responseData;
@property(retain, nonatomic) NSString *lastErrorDisc; // @synthesize lastErrorDisc=_lastErrorDisc;
@property(retain, nonatomic) NSDate *lastNotifyTime; // @synthesize lastNotifyTime=_lastNotifyTime;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSMutableArray *arURL; // @synthesize arURL=_arURL;
@property(retain, nonatomic) NSMutableURLRequest *urlRequest; // @synthesize urlRequest=_urlRequest;
@property(copy, nonatomic) NSString *tmpfileName; // @synthesize tmpfileName=_tmpfileName;
- (void).cxx_destruct;
- (void)dealloc;
- (void)dataReport:(BOOL)arg1 failCode:(int)arg2 errorDisc:(id)arg3 reportcollect:(BOOL)arg4 reportDetail:(BOOL)arg5;
- (void)confirmFail;
- (BOOL)tempFileMD5Check;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)tryFileMove;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (BOOL)tryNextURL;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)notifyProgress:(float)arg1;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)getErrMsg:(int)arg1 httpHeaders:(id)arg2 isWithFtnRetCode:(char *)arg3;
- (void)saveOfflineFileData:(BOOL)arg1;
- (int)appendWiteToFile:(id)arg1 Data:(id)arg2;
- (void)onComplete:(BOOL)arg1;
- (void)notifyComplete:(BOOL)arg1;
- (void)ThreadHttpGet;
- (BOOL)isCanRetry;
- (void)ThreadStop;
- (void)stop;
- (void)cancel;
- (void)startDown:(id)arg1 fileInfo:(id)arg2 tmpfileName:(id)arg3;
- (id)init:(int)arg1 delegate:(id)arg2 reportId:(id)arg3 reportDetailId:(id)arg4;

@end

