//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FADownRequest.h"

@interface FADownRequestC2C : FADownRequest
{
}

- (void)didRecievedMsg:(CDStruct_a00ab4be)arg1;
- (BOOL)onRspApplyDownload:(const basic_string_075b6133 *)arg1;
- (void)internalRequest;
- (id)init:(int)arg1 fileInfo:(id)arg2;

@end

