//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

@interface FAGroupProtocolHandler : QQBaseSingleton
{
}

- (int)_appid;
- (void)sendFeed:(id)arg1 completion:(id)arg2;
- (void)requestCmd6d6_SUBCMD_RESEND:(id)arg1 completion:(id)arg2;
- (void)requestCmd6d6_SUBCMD_APPLY_UPLOAD:(id)arg1 completion:(id)arg2;
- (void)requestCmd6d6_SUBCMD_APPLY_DOWNLOAD:(id)arg1 isThumbnail:(BOOL)arg2 completion:(id)arg3;

@end

