//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

@interface FAOfflineProtocolHandler : QQBaseSingleton
{
}

- (unsigned int)_getBusinessID:(id)arg1;
- (void)requestApplyDownloadPreview:(id)arg1 completion:(id)arg2;
- (struct RoutingHead *)_genRoutingHead:(id)arg1 cmd:(unsigned int)arg2;
- (id)_createNotifyData_0x211_0x7_MsgBody_FTNNotify:(id)arg1;
- (id)_createNotifyData_0x211_0x4_MsgBody:(id)arg1 msgType:(int)arg2;
- (void)_sendNotifyMessage4DataLine:(id)arg1 completion:(id)arg2;
- (void)_sendNotifyMessage4Offline:(id)arg1 completion:(id)arg2;
- (void)sendNotifyMessage:(id)arg1 completion:(id)arg2;
- (void)sendNotifyReceiptMessage:(id)arg1 completion:(id)arg2;
- (void)requestCmd346_CMD_REQ_RECALL:(id)arg1 compeltion:(id)arg2;
- (void)requestCmd346_CMD_REQ_UPLOAD_SUCC:(id)arg1 compeltion:(id)arg2;
- (void)requestCmd346_CMD_REQ_APPLY_DOWNLOAD:(id)arg1 completion:(id)arg2;
- (void)requestCmd346_CMD_REQ_APPLY_UPLOAD_V3:(id)arg1 completion:(id)arg2;
- (void)requestCmd346_CMD_REQ_APPLY_UPLOAD_V2:(id)arg1 completion:(id)arg2;

@end

