//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

#import "FADownloadDelegate.h"

@class NSLock, NSMutableArray, NSString;

@interface FATransferMgrDown : QQBaseSingleton <FADownloadDelegate>
{
    id <FAEventDelegate> _delegate;
    NSMutableArray *_downloadQueue;
    NSLock *_queueLock;
    int _concurrentDownloadingCount;
}

- (void).cxx_destruct;
- (void)onFAThumbnailFail:(id)arg1 size:(int)arg2;
- (void)onFAThumbnailSuccess:(id)arg1 size:(int)arg2;
- (void)OnFADownloadUpdate:(id)arg1 isFinish:(BOOL)arg2 withErr:(id)arg3;
- (id)findFADownloadTask:(unsigned long long)arg1;
- (void)executeNextDownload;
- (void)stopFADownloadTask:(int)arg1;
- (BOOL)FADownloadWithTaskInfo:(id)arg1;
- (BOOL)isFADownloadTaskRunning:(unsigned long long)arg1;
- (void)cancel:(id)arg1;
- (void)download:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

