//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQBaseTableView.h"

@interface FileAssistantTableView : MQBaseTableView
{
}

- (id)selectionBackgroundImage;
- (void)keyDown:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawGridInClipRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

