//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSThemeFrame.h"

@class NSColor, NSFont, NSGradient, NSShadow;

@interface GRCustomizableWindowFrame : NSThemeFrame
{
    double _titlebarHeight;
    NSColor *_titlebarColor;
    NSColor *_titleStringColor;
    NSColor *_separatorlineColor;
    NSFont *_titleStringFont;
    double _controlsXOffset;
    BOOL _shouldCenterControls;
    BOOL _shouldDrawGradients;
    NSColor *_titlebarColorNoKey;
    NSColor *_titlebarSeparatorColor;
    NSColor *_titlebarSeparatorColorNoKey;
    NSGradient *_titlebarOverlayGradient;
    NSColor *_titleStringColorNoKey;
    NSColor *_contentBorderHighlightColor;
    NSShadow *_titleStringShadow;
}

- (void).cxx_destruct;
- (BOOL)_shouldUseDarkShadow;
- (id)offsetColor:(id)arg1 by:(double)arg2;
- (id)_defaultTitleStringShadow;
- (double)_centeredTrafficLightsY;
- (struct CGPoint)_zoomButtonOrigin;
- (struct CGPoint)_closeButtonOrigin;
- (struct CGPoint)_fullScreenButtonOrigin;
- (double)_titlebarHeight;
- (struct CGRect)titlebarRect;
- (void)_setDrawGradients:(BOOL)arg1;
- (void)_setCenterControls:(BOOL)arg1;
- (void)_setControlsXOffset:(double)arg1;
- (void)_setTitleStringFont:(id)arg1;
- (void)_setSeparatorLineColor:(id)arg1;
- (void)_setTitleStringColor:(id)arg1;
- (void)_setTitlebarColor:(id)arg1;
- (void)_setTitlebarHeight:(double)arg1;
- (void)drawOverlayGradientInRect:(struct CGRect)arg1;
- (void)drawTitleString;
- (void)drawTexturedBackground:(struct CGRect)arg1;
- (void)drawContentBorder;
- (void)drawTitlebar;
- (void)drawRect:(struct CGRect)arg1;
- (id)_caWindow;
- (id)initWithFrame:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 owner:(id)arg3;

@end

