//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol IC2CTypeMsgRemoveDuplicateRelateMarkGenerator <NSObject>
- (void)GenRemoveDuplicateRelateMark:(struct _C2C_DUPLICATE_RELATEMARK *)arg1 GenInputParam:(struct _C2C_DUPLICATE_RELATEMARK_GEN_INPUT_PARAM *)arg2;
@end

