//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface imageTask2 : NSObject
{
    BOOL _bRunning;
    unsigned int _groupID;
    unsigned int _index;
    unsigned int _groupSize;
    int _deviceType;
    unsigned long long _sessionId;
    NSString *_strFilePath;
    NSString *_strThumbPath;
}

@property(nonatomic) int deviceType; // @synthesize deviceType=_deviceType;
@property(nonatomic) BOOL bRunning; // @synthesize bRunning=_bRunning;
@property(copy, nonatomic) NSString *strThumbPath; // @synthesize strThumbPath=_strThumbPath;
@property(copy, nonatomic) NSString *strFilePath; // @synthesize strFilePath=_strFilePath;
@property(nonatomic) unsigned int groupSize; // @synthesize groupSize=_groupSize;
@property(nonatomic) unsigned int index; // @synthesize index=_index;
@property(nonatomic) unsigned long long sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) unsigned int groupID; // @synthesize groupID=_groupID;
- (void).cxx_destruct;
- (void)dealloc;

@end

