//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@protocol IOnlineFileMsgChannelDelegate <NSObject>
- (void)addLog:(NSString *)arg1;
- (NSData *)getRelayKey;
- (NSData *)getRelaySignature;
- (unsigned long long)getUin;
- (BOOL)sendCCMsg:(NSData *)arg1 cmd:(unsigned int)arg2 seq:(unsigned int)arg3 toUin:(unsigned long long)arg4 completion:(void (^)(BOOL, NSError *))arg5;
@end

