//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LoginMonitor : NSObject
{
    unsigned long long _lastLoginScenario;
}

+ (id)shareInstance;
@property unsigned long long lastLoginScenario; // @synthesize lastLoginScenario=_lastLoginScenario;
- (void)finishLoginFor:(unsigned long long)arg1 result:(long long)arg2 withError:(id)arg3;
- (void)finishLogin:(long long)arg1 WithError:(id)arg2;
- (void)willLoginFor:(unsigned long long)arg1;

@end

