//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSColor, NSString;

@interface MAVBackView : NSView
{
    NSColor *color_;
    NSString *fileName_;
    BOOL transparent_;
}

@property(retain, nonatomic) NSString *fileName; // @synthesize fileName=fileName_;
@property(retain, nonatomic) NSColor *color; // @synthesize color=color_;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 file:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 color:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;

@end

