//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MAVBasicVideoViewController, NSTrackingArea;

@interface MAVEventBackView : NSView
{
    NSTrackingArea *trackingArea_;
    MAVBasicVideoViewController *controller_;
}

- (void)mouseUp:(id)arg1;
- (void)updateTrackingAreas;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 controller:(id)arg2;

@end

