//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class MCTableCellModel, NSImage;

@interface MCCellViewBase : NSTableCellView
{
    NSImage *_headerImage;
    MCTableCellModel *_cellModel;
    id <MCCellViewDelegate> _delegate;
}

@property(retain) id cellModel; // @synthesize cellModel=_cellModel;
@property __weak id <MCCellViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)mouseDown:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)clearDefault;
- (void)setElement:(id)arg1;
- (void)handleHeaderIconDownloadNotification:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithCoder:(id)arg1;

@end

