//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MCCellViewBase.h"

@class NSImageView, NSLayoutConstraint, NSTextField;

@interface MCListCellViewTwo : MCCellViewBase
{
    NSTextField *_lbTime;
    NSImageView *_headerPic;
    NSTextField *_lbPublicerName;
    NSTextField *_lbTitle;
    NSTextField *_lbBrief;
    NSLayoutConstraint *_ConstraintPublisherWidth;
    NSLayoutConstraint *_ConstraintTimeWidth;
}

@property __weak NSLayoutConstraint *ConstraintTimeWidth; // @synthesize ConstraintTimeWidth=_ConstraintTimeWidth;
@property __weak NSLayoutConstraint *ConstraintPublisherWidth; // @synthesize ConstraintPublisherWidth=_ConstraintPublisherWidth;
@property __weak NSTextField *lbBrief; // @synthesize lbBrief=_lbBrief;
@property __weak NSTextField *lbTitle; // @synthesize lbTitle=_lbTitle;
@property __weak NSTextField *lbPublicerName; // @synthesize lbPublicerName=_lbPublicerName;
@property __weak NSImageView *headerPic; // @synthesize headerPic=_headerPic;
@property __weak NSTextField *lbTime; // @synthesize lbTime=_lbTime;
- (void).cxx_destruct;
- (void)updateHeader:(id)arg1;
- (void)setElement:(id)arg1;
- (void)clearDefault;

@end

