//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MQAIOChatHeadViewController, MQAIOChatTootKitViewController, MQAIOMemberViewController, MQCircleCountViewController, MQSessionID;

@protocol MQAIOChatViewControllerDelegate <NSObject>
- (void)adjustSizeOnShowMemberList;
- (void)closeChatViewForSessionID:(MQSessionID *)arg1;
- (MQAIOMemberViewController *)infoViewControllerForSession:(MQSessionID *)arg1;
- (MQAIOChatTootKitViewController *)toolKitControllerForSession:(MQSessionID *)arg1;
- (MQCircleCountViewController *)theNewMsgRemindViewController;
- (MQAIOChatHeadViewController *)headViewControllerForSession:(MQSessionID *)arg1;
@end

