//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQAIOToolBox.h"

@class MQAIOSendFilesButton, MQAIOToolButton;

@interface MQAIONFBuddyToolBox : MQAIOToolBox
{
    MQAIOToolButton *_btnAddContact;
    MQAIOSendFilesButton *_btnSendFiles;
}

@property(nonatomic) MQAIOSendFilesButton *btnSendFiles; // @synthesize btnSendFiles=_btnSendFiles;
@property(nonatomic) MQAIOToolButton *btnAddContact; // @synthesize btnAddContact=_btnAddContact;
- (void)awakeFromNib;

@end

