//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQAIOToolButtonCell.h"

@class NSImage;

@interface MQAIOSendFileButtonCell : MQAIOToolButtonCell
{
    double _progress;
    NSImage *_imgProgress;
    NSImage *_imgProgressInActive;
    struct CGSize _sizeImgProgress;
    struct CGRect _drawRect;
    unsigned long long _curFrameIndex;
    BOOL _isFinished;
    struct CGPoint _drawPoint;
}

@property(retain, nonatomic) NSImage *imgProgressInActive; // @synthesize imgProgressInActive=_imgProgressInActive;
@property(retain, nonatomic) NSImage *imgProgress; // @synthesize imgProgress=_imgProgress;
@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)stopAnimation;
- (void)startAnimation;
- (void)nextKeyFrame;
- (void)removeFrameImage;
- (void)drawImage:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (void)removeFileProgress;
- (void)awakeFromNib;

@end

