//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProgressIndicator.h"

@class NSColor;

@interface MQCircleProgerssIndicator : NSProgressIndicator
{
    NSColor *_fillColor;
    double _strokeWidth;
    NSColor *_strokeColor;
}

+ (id)defaultAnimationForKey:(id)arg1;
@property(retain, nonatomic) NSColor *strokeColor; // @synthesize strokeColor=_strokeColor;
@property(nonatomic) double strokeWidth; // @synthesize strokeWidth=_strokeWidth;
@property(retain, nonatomic) NSColor *fillColor; // @synthesize fillColor=_fillColor;
- (void).cxx_destruct;
- (BOOL)isFlipped;
- (void)drawRect:(struct CGRect)arg1;

@end

