//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSMenuDelegate.h"

@class KBDelayedPopUpButton, NSMenu, NSString, TChatMenuController, TXColorView;

@interface MQContactsAddViewController : NSViewController <NSMenuDelegate>
{
    NSMenu *_addMenu;
    TXColorView *_bgView;
    TXColorView *_sepView;
    KBDelayedPopUpButton *_addContactBtn;
    TChatMenuController *_tchatMenu;
}

@property(nonatomic) __weak TChatMenuController *tchatMenu; // @synthesize tchatMenu=_tchatMenu;
@property KBDelayedPopUpButton *addContactBtn; // @synthesize addContactBtn=_addContactBtn;
@property TXColorView *sepView; // @synthesize sepView=_sepView;
@property TXColorView *bgView; // @synthesize bgView=_bgView;
- (void).cxx_destruct;
- (void)buildDiscuss:(id)arg1;
- (void)buildGroup:(id)arg1;
- (void)addContact:(id)arg1;
- (void)initWithMenu;
- (void)onClickMenuButton:(id)arg1;
- (void)viewDidLoad;
- (void)refreshAppearance;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

