//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MQDataLineUtils : NSObject
{
}

+ (unsigned long long)deviceTypeForDeviceUIN:(id)arg1;
+ (id)deviceUINForDeviceType:(unsigned long long)arg1;
+ (unsigned long long)groupSizeForMessageModel:(id)arg1;
+ (unsigned long long)groupIDForMessageModel:(id)arg1;
+ (unsigned long long)sessionIDForMessageModel:(id)arg1;

@end

