//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, NSString;

@interface MQEmojiStore : NSObject
{
    NSObject<OS_dispatch_group> *_downloadEmojiKeysGroup;
    NSObject<OS_dispatch_queue> *_downloadEmojiQueue;
    BOOL _createDirIfNotExist;
    BOOL _downloadEmojiKeySuccess;
    unsigned int _timestamp;
    NSString *_uin;
    NSMutableDictionary *_packageGroupInfoDic;
    NSMutableDictionary *_requestSSOContext;
    id _refreshStoreEmojiPackagesBlock;
    id _downloadEmojiImagesPackageBlock;
    NSMutableDictionary *_deleteBlocks;
    NSMutableArray *_roamTempArr;
}

@property(nonatomic) BOOL downloadEmojiKeySuccess; // @synthesize downloadEmojiKeySuccess=_downloadEmojiKeySuccess;
@property(retain, nonatomic) NSMutableArray *roamTempArr; // @synthesize roamTempArr=_roamTempArr;
@property(nonatomic) unsigned int timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) BOOL createDirIfNotExist; // @synthesize createDirIfNotExist=_createDirIfNotExist;
@property(retain, nonatomic) NSMutableDictionary *deleteBlocks; // @synthesize deleteBlocks=_deleteBlocks;
@property(copy, nonatomic) id downloadEmojiImagesPackageBlock; // @synthesize downloadEmojiImagesPackageBlock=_downloadEmojiImagesPackageBlock;
@property(copy, nonatomic) id refreshStoreEmojiPackagesBlock; // @synthesize refreshStoreEmojiPackagesBlock=_refreshStoreEmojiPackagesBlock;
@property(retain, nonatomic) NSMutableDictionary *requestSSOContext; // @synthesize requestSSOContext=_requestSSOContext;
@property(retain, nonatomic) NSMutableDictionary *packageGroupInfoDic; // @synthesize packageGroupInfoDic=_packageGroupInfoDic;
@property(copy, nonatomic) NSString *uin; // @synthesize uin=_uin;
- (void).cxx_destruct;
- (void)dealloc;
- (id)emojiStoreSourceDirPathWithPackageId:(unsigned long long)arg1 emojiId:(id)arg2;
- (id)emojiStoreConfigFilePath;
- (id)emojiPackageBriefFilePath:(unsigned long long)arg1;
- (id)emojiStoreDirPath;
- (id)emojiPackageDirPath:(id)arg1;
- (id)emojiPackageDirPathWithID:(unsigned long long)arg1;
- (void)notifyErrorFromMSF:(id)arg1;
- (char *)removeWupHead:(char *)arg1 bufferLength:(int)arg2;
- (void)didReceivedMessageFromMSF:(CDStruct_a00ab4be)arg1;
- (void)deleteStoreEmojiPackage:(id)arg1 completion:(id)arg2;
- (void)responseOnPackageRemoved:(struct CPBMessageDecoder *)arg1 ret:(int)arg2 context:(id)arg3;
- (void)deletePackageResource:(id)arg1;
- (void)responseOnPackageEmojiKeys:(struct CPBMessageDecoder *)arg1 ret:(int)arg2 context:(id)arg3;
- (void)requestPackageEmojiKeys:(id)arg1;
- (void)responseOnGetEmojiDownloadFlagsByUin:(char *)arg1 dataLen:(int)arg2 seq:(int)arg3;
- (void)requestEmojiDownloadFlagsByUin:(long long)arg1;
- (BOOL)sendWupBuffer:(struct CPBMessageEncoder *)arg1 cmd:(id)arg2 subCmd:(unsigned int)arg3 context:(id)arg4 timeout:(int)arg5;
- (void)downloadSingleEmojiResource:(id)arg1 completion:(id)arg2;
- (void)downloadEmojiImagesPackage:(id)arg1 completion:(id)arg2;
- (void)refreshStoreEmojiPackagesCompletion:(id)arg1;
- (BOOL)requestPackageGroupInfosBeginWithIOSSegment:(int)arg1 androidSegment:(int)arg2 context:(id)arg3;
- (void)responseOnPackageGroupInfos:(struct CPBMessageDecoder *)arg1 ret:(int)arg2 context:(id)arg3;
- (id)parseEmojiPackageInfo:(struct CPBMessageDecoder *)arg1;
- (void)packageGroupInfosDidReceivedCompletion;
- (void)downloadPackageJSONWithPackageID:(unsigned int)arg1 completion:(id)arg2;
- (void)convertToPackage:(id)arg1 fromJSON:(id)arg2;
- (void)saveJSONDic:(id)arg1 packageID:(unsigned long long)arg2;
- (void)downloadImage:(id)arg1 forType:(long long)arg2 compltion:(id)arg3;
- (id)emojiPackageWithId:(long long)arg1;
- (id)emojiWithId:(id)arg1 packageId:(long long)arg2;
- (id)emojiWithId:(id)arg1;
- (void)syncPackageGroupInfosToLocal;
- (void)initPackageGroupInfos;
- (id)initWithUin:(id)arg1;

@end

