//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FAModel, NSDate, NSString, QQDataLineFileObject;

@interface MQFileViewModel : NSObject
{
    double _datalineTimeInterval;
    BOOL _isDownLoad;
    BOOL _isCancelOperation;
    int _status;
    int _transmissionType;
    id <MQFileViewModelDelegate> _delegate;
    double _progress;
    double _speed;
    long long _fileSize;
    long long _errorCode;
    NSString *_fileName;
    NSString *_filePath;
    long long _uOutdatedTime;
    NSDate *_expireDate;
    FAModel *_fileModel;
    QQDataLineFileObject *_datalineModel;
    NSString *_datalineSessionId;
    long long _datalineGroupId;
    unsigned long long _groupTaskStatus;
}

@property(readonly, nonatomic) unsigned long long groupTaskStatus; // @synthesize groupTaskStatus=_groupTaskStatus;
@property(nonatomic) BOOL isCancelOperation; // @synthesize isCancelOperation=_isCancelOperation;
@property(readonly, nonatomic) long long datalineGroupId; // @synthesize datalineGroupId=_datalineGroupId;
@property(readonly, copy, nonatomic) NSString *datalineSessionId; // @synthesize datalineSessionId=_datalineSessionId;
@property(readonly, nonatomic) QQDataLineFileObject *datalineModel; // @synthesize datalineModel=_datalineModel;
@property(readonly, nonatomic) FAModel *fileModel; // @synthesize fileModel=_fileModel;
@property(readonly, nonatomic) int transmissionType; // @synthesize transmissionType=_transmissionType;
@property(readonly, nonatomic) NSDate *expireDate; // @synthesize expireDate=_expireDate;
@property(readonly, nonatomic) long long uOutdatedTime; // @synthesize uOutdatedTime=_uOutdatedTime;
@property(readonly, copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(readonly, copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(readonly, nonatomic) long long errorCode; // @synthesize errorCode=_errorCode;
@property(readonly, nonatomic) long long fileSize; // @synthesize fileSize=_fileSize;
@property(readonly, nonatomic) double speed; // @synthesize speed=_speed;
@property(readonly, nonatomic) BOOL isDownLoad; // @synthesize isDownLoad=_isDownLoad;
@property(readonly, nonatomic) int status; // @synthesize status=_status;
@property(readonly, nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) __weak id <MQFileViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)initWithGroupTask:(id)arg1 groupInfo:(id)arg2 msgModel:(id)arg3;
- (id)initWithGroupTask:(id)arg1 groupInfo:(id)arg2;
- (BOOL)isDownload;
- (void)onClickStart;
- (BOOL)isFefuse;
- (void)onClickCancel;
- (void)onClickResend;
- (void)onClickSwitchToOffline;
- (void)onShowFileInFinder;
- (void)clickedFileBtn:(id)arg1;
- (void)handleDataLineTransfer:(id)arg1;
- (int)convertMissionType:(id)arg1;
- (void)handleFileTransfer:(id)arg1;
- (void)updateFileModel;
- (void)updateDatalineModel;
- (void)dealloc;
- (id)_initWithFakeViewModel:(id)arg1;
- (id)initWithViewModel:(id)arg1;
- (id)initWithMessageModel:(id)arg1;

@end

