//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextAttachment.h"

@class MQFileTransmissionTaskInfo, RTXFileTransferCell;

@interface MQFileTransmissionTextAttachment : NSTextAttachment
{
    id <RTXFileTransferAttachmentDelegate> delegate;
    MQFileTransmissionTaskInfo *_taskInfo;
    RTXFileTransferCell *attachmentCell;
    BOOL _isDataLine;
}

+ (id)attachmentWithTaskInfo:(id)arg1;
+ (id)attachment;
@property(nonatomic) BOOL isDataLine; // @synthesize isDataLine=_isDataLine;
@property id <RTXFileTransferAttachmentDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (id)description;
@property(retain) MQFileTransmissionTaskInfo *taskInfo; // @synthesize taskInfo=_taskInfo;
- (void)onClickSwitchToOfflineFileArea:(id)arg1;
- (void)onClickResendArea:(id)arg1;
- (void)onClickShowInFinderArea:(id)arg1;
- (void)onDoubleClickArea:(id)arg1;
- (void)onClickCancelArea:(id)arg1;
- (void)onClickStartArea:(id)arg1;
- (void)notifyFileReadyToShow:(id)arg1 pathName:(id)arg2;
- (void)failTaskWithErrorCode:(long long)arg1;
- (void)startTransfer;
- (void)waitToStart;
- (void)cancelTask:(BOOL)arg1;
- (void)setFileIconWithFile:(id)arg1;
- (void)finishTaskWithFileSavedTo:(id)arg1;
- (void)setCropedThumbnailImage:(id)arg1;
- (void)loadThumbnailImage;
- (id)getLocalImageWithPath:(id)arg1;
- (id)getThumbForLocalVideo:(id)arg1;
- (BOOL)isBubbleMode;
@property unsigned long long speed;
@property unsigned long long maxValue;
@property unsigned long long currentValue;
- (void)setTextView:(id)arg1;
- (id)init;

@end

