//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSButton, NSImageView, NSView;

@interface MQJTSwitchControl : NSViewController
{
    BOOL _packUp;
    long long _JTStatus;
    id <MQJTSwitchControllerDelegate> _delegate;
    NSButton *_packUpButton;
    NSView *_backView;
    NSImageView *_backImage;
}

@property __weak NSImageView *backImage; // @synthesize backImage=_backImage;
@property __weak NSView *backView; // @synthesize backView=_backView;
@property __weak NSButton *packUpButton; // @synthesize packUpButton=_packUpButton;
@property(nonatomic) __weak id <MQJTSwitchControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) long long JTStatus; // @synthesize JTStatus=_JTStatus;
- (void).cxx_destruct;
- (void)packUpTabbar:(BOOL)arg1;
@property(nonatomic, getter=isPackUp) BOOL packUp;
- (void)packUpDidClicked:(id)arg1;
- (void)switchButtonDidClicked:(id)arg1;
- (void)changeBackImage;
- (void)awakeFromNib;
- (id)initWithJTControlStatus:(long long)arg1;

@end

