//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MQLocSelectedTableCellView;

@protocol MQLocSelectedRowViewDelegate <NSObject>
- (long long)indexOfRow:(MQLocSelectedTableCellView *)arg1;
- (void)mouseExitFromRow:(MQLocSelectedTableCellView *)arg1;
- (void)mouseEnteredInRow:(MQLocSelectedTableCellView *)arg1;
@end

