//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextBlock.h"

#import "MQMenuButtonDelegate.h"
#import "MQMouseHoverProtocol.h"

@class MQAIOMenuButton, NSString, NSTextAttachmentCell, TXBaseTextView;

@interface MQMsgTextBlock : NSTextBlock <MQMenuButtonDelegate, MQMouseHoverProtocol>
{
    BOOL _isSelected;
    TXBaseTextView *_superView;
    BOOL _showActionButton;
    id _actionMenuItems;
    long long _actionButtonPosition;
    MQAIOMenuButton *_menuBtn;
    NSTextAttachmentCell *_cell;
    struct _NSRange _messageRange;
    struct CGRect _layoutRect;
}

@property(nonatomic) __weak NSTextAttachmentCell *cell; // @synthesize cell=_cell;
@property(nonatomic) struct _NSRange messageRange; // @synthesize messageRange=_messageRange;
@property(retain, nonatomic) MQAIOMenuButton *menuBtn; // @synthesize menuBtn=_menuBtn;
@property long long actionButtonPosition; // @synthesize actionButtonPosition=_actionButtonPosition;
@property(copy) id actionMenuItems; // @synthesize actionMenuItems=_actionMenuItems;
@property BOOL showActionButton; // @synthesize showActionButton=_showActionButton;
@property struct CGRect layoutRect; // @synthesize layoutRect=_layoutRect;
@property TXBaseTextView *superView; // @synthesize superView=_superView;
@property BOOL isSelected; // @synthesize isSelected=_isSelected;
- (void).cxx_destruct;
- (void)showOrHideScheduleGuide:(id)arg1 isShow:(BOOL)arg2;
- (void)showMenuBtn;
- (struct CGRect)menuBtnFrame;
- (void)mouseExist:(id)arg1;
- (void)mouseEnter:(id)arg1;
- (void)onMenuMouseEnter:(id)arg1;
- (id)onPopUpMenuWithEvent:(id)arg1 forView:(id)arg2;
- (struct _NSRange)getTotalMsgRangeAtIndex:(long long)arg1;
- (struct CGRect)rectForLayoutAtPoint:(struct CGPoint)arg1 inRect:(struct CGRect)arg2 textContainer:(id)arg3 characterRange:(struct _NSRange)arg4;
- (void)drawBackgroundWithFrame:(struct CGRect)arg1 inView:(id)arg2 characterRange:(struct _NSRange)arg3 layoutManager:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

