//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MQMsgResendUtil : NSObject
{
}

+ (void)resendMessage:(id)arg1 sessionId:(id)arg2;
+ (id)resendMsgLinkInfoAttr:(id)arg1;
+ (void)resendMsgShutAttr:(id)arg1 block:(id)arg2;
+ (void)postMsgSendErrorNotification:(id)arg1;
+ (void)postPTTErrorNotification:(id)arg1 duration:(int)arg2 targetUin:(id)arg3 chatType:(int)arg4;
+ (BOOL)isPictureFileExist:(id)arg1;
+ (BOOL)isAudioFileExist:(id)arg1;
+ (id)getMsgRecordStr:(id)arg1;
+ (id)pttFilePath:(id)arg1;
+ (int)getChatTypeOfModel:(id)arg1;

@end

