//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface MQNetworkProxyObject : NSObject <NSCoding>
{
    unsigned long long _proxyType;
    NSString *_ip;
    NSString *_port;
    NSString *_account;
    NSString *_password;
}

@property(copy) NSString *password; // @synthesize password=_password;
@property(copy) NSString *account; // @synthesize account=_account;
@property(copy) NSString *port; // @synthesize port=_port;
@property(copy) NSString *ip; // @synthesize ip=_ip;
@property unsigned long long proxyType; // @synthesize proxyType=_proxyType;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

