//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "MQScreenCaptureComponentDelegate.h"
#import "MQScreenCaptureRectResizableDelegate.h"
#import "MQScreenCaptureViewDelegate.h"

@class MQSCControlContainView, MQSCReadingGlassView, MQScreenCaptureRectResizable, MQScreenCaptureView, NSImageView, NSString, TXColorView;

@interface MQScreenCaptureViewController : NSViewController <MQScreenCaptureViewDelegate, MQScreenCaptureComponentDelegate, MQScreenCaptureRectResizableDelegate>
{
    NSImageView *_backgroundImageView;
    MQScreenCaptureView *_captureView;
    MQSCReadingGlassView *_magnifierView;
    MQSCControlContainView *_sizeInfoView;
    TXColorView *_OCRTipsView;
    struct CGRect _sizeInfoRect;
    BOOL _needCaptureScreen;
    struct CGPoint _firstPoint;
    struct CGPoint _secondPoint;
    struct CGRect _selectedRect;
    MQScreenCaptureRectResizable *_markEditingView;
    BOOL _needShowMagnifier;
    id <MQScreenCaptureViewControllerDelegate> _delegate;
}

@property __weak id <MQScreenCaptureViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleDidConfirmSelection:(id)arg1;
- (void)setSizeInfo:(struct CGRect)arg1;
@property(readonly) MQScreenCaptureRectResizable *markEditingView;
- (struct CGPoint)findMagnifyPostionByMouseLocation:(struct CGPoint)arg1;
- (void)hideToolKit;
- (void)showToolKit;
- (void)hideMagnifier;
- (void)showMagnifierAtLocation:(struct CGPoint)arg1;
- (void)setupSizeInfoView;
- (void)setupTips;
- (void)setupScreenCaptureView;
- (void)setupMagnifier;
- (void)setupBackgroundImage;
- (void)captureRect:(struct CGRect)arg1 saveToFile:(BOOL)arg2;
- (void)didEndChangingFrame;
- (void)prepareForChangingFrame;
- (struct CGRect)autoFitRectForMouseLocation:(struct CGPoint)arg1;
- (void)mouseLocationDidUpdate:(struct CGPoint)arg1;
- (struct CGRect)selectedContentFrame;
- (void)didConfirmSelection;
- (void)didUpdateEndPoint:(struct CGPoint)arg1;
- (void)gotStartPoint:(struct CGPoint)arg1;
- (BOOL)needSelectRect;
- (void)cancelCapture;
- (void)setScreenImage:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

