//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QMSSView.h"

@class NSImageView;

@interface MQScreenSelectorItemView : QMSSView
{
    NSImageView *_imageView;
    unsigned int _displayID;
    id <MQScreenSelectorItemViewDelegate> _selectorDelegate;
}

@property(nonatomic) __weak id <MQScreenSelectorItemViewDelegate> selectorDelegate; // @synthesize selectorDelegate=_selectorDelegate;
- (void).cxx_destruct;
- (unsigned int)displayID;
- (void)loadScreenImage:(struct CGSize)arg1;
- (void)handleClickedEvent:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 displayID:(unsigned int)arg2;

@end

