//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQScreenShareMarkBase.h"

#import "MQHoverButtonDelegate.h"
#import "NSTextViewDelegate.h"

@class MQHoverButton, MQScreenShareMarkLabelTextView, NSImageView, NSString;

@interface MQScreenShareMarkLabel : MQScreenShareMarkBase <NSTextViewDelegate, MQHoverButtonDelegate>
{
    MQScreenShareMarkLabelTextView *_textComponent;
    BOOL _inTextEditingMode;
    MQHoverButton *_rotateBtn;
    NSImageView *_arrowImg;
    BOOL _isRotate;
}

- (struct CGSize)sizeFittingAttributedString:(id)arg1;
- (void)exitTextEditingMode;
- (void)enterTextEditingMode;
- (void)updateContentFrameSize:(struct CGSize)arg1;
- (void)setupTextComponent;
- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (void)textViewDidChangeTypingAttributes:(id)arg1;
- (id)textView:(id)arg1 shouldChangeTypingAttributes:(id)arg2 toAttributes:(id)arg3;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)valid;
- (int)type;
- (id)sizeControlTypeList;
- (void)setSelected:(BOOL)arg1;
- (void)setReady:(BOOL)arg1;
- (void)setEndPoint:(struct CGPoint)arg1;
- (void)setStartPoint:(struct CGPoint)arg1;
- (void)setFontSize:(double)arg1;
- (void)setLineColor:(id)arg1;
- (void)setContentFrame:(struct CGRect)arg1;
- (void)mouseDown:(id)arg1;
- (void)updateSubviewsOrigin;
- (void)updateSelectedFrame;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (void)addArrowView;
- (void)updateRotateContentFrame;
- (void)updateTextComponentAttributes;
- (void)rotate:(id)arg1;
- (void)hoverBtnMouseDrag:(id)arg1;
- (void)hoverBtnMouseDown:(id)arg1;
- (void)addRotateView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

