//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQScreenShareMarkBase.h"

@class NSMutableArray;

@interface MQScreenShareMarkBrush : MQScreenShareMarkBase
{
    NSMutableArray *_pointList;
    struct CGPoint _pointArray[1000];
    long long _currentIndex;
    struct CGPoint _minPoint;
    struct CGPoint _maxPoint;
}

- (void)setReady:(BOOL)arg1;
- (int)type;
- (BOOL)mouseInInterestRegion:(struct CGPoint)arg1;
- (id)sizeControlTypeList;
- (void)setEndPoint:(struct CGPoint)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)setMarkInfoFrame;
- (void)adjustMarkInfo;
- (void)viewDidMoveToSuperview;
- (BOOL)valid;
- (void)setHidden:(BOOL)arg1;
- (id)createMarkInfo;
- (struct CGPoint)transferScalePoint:(struct CGPoint)arg1 scale:(double)arg2;
- (void)markItemScale:(double)arg1;
- (void)updateWithMarkInfo:(id)arg1;
- (id)initWithMarkInfo:(id)arg1;
- (id)init;

@end

