//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MQSessionID, QQRecentMessageModel;

@interface MQSessionInfo : NSObject
{
    MQSessionID *_sessionID;
    QQRecentMessageModel *_msgModel;
    unsigned long long _topmostOrderValue;
    double _lastMessageTime;
    double _lastReorderTime;
    struct {
        unsigned int selected:1;
        unsigned int isInDB:1;
    } _flags;
    BOOL _isNeedShowRedDot;
    BOOL _isIllumined;
}

@property(nonatomic) BOOL isIllumined; // @synthesize isIllumined=_isIllumined;
@property(nonatomic) BOOL isNeedShowRedDot; // @synthesize isNeedShowRedDot=_isNeedShowRedDot;
@property(nonatomic) double lastReorderTime; // @synthesize lastReorderTime=_lastReorderTime;
@property(nonatomic) unsigned long long topmostOrderValue; // @synthesize topmostOrderValue=_topmostOrderValue;
@property(nonatomic) double lastMessageTime; // @synthesize lastMessageTime=_lastMessageTime;
@property(readonly, retain, nonatomic) MQSessionID *sessionID; // @synthesize sessionID=_sessionID;
- (void).cxx_destruct;
- (void)dealloc;
- (id)description;
- (id)name;
- (long long)compare:(id)arg1;
@property BOOL selected;
@property BOOL isInDB;
- (BOOL)isTopMost;
- (BOOL)isEqual:(id)arg1;
- (id)initWithChatType:(int)arg1 uin:(unsigned long long)arg2;
- (id)initWithRecentMessageModel:(id)arg1;
- (id)initWithSessionID:(id)arg1;

@end

