//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQBaseTableView.h"

@interface MQSearchResultTableView : MQBaseTableView
{
    long long _rowNum;
    long long _colNum;
    id <ExtendedTableViewDelegate> _extendedDelegate;
}

@property(nonatomic) long long colNum; // @synthesize colNum=_colNum;
@property(nonatomic) long long rowNum; // @synthesize rowNum=_rowNum;
@property(nonatomic) __weak id <ExtendedTableViewDelegate> extendedDelegate; // @synthesize extendedDelegate=_extendedDelegate;
- (void).cxx_destruct;
- (void)onDoubleClicked:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

