//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class MQAvatarImageView, NSButton, NSLayoutConstraint, NSTextField, NSTrackingArea, SurpriseButton;

@interface MQSearchedContactView : NSTableCellView
{
    NSTrackingArea *_trackArea;
    BOOL _showDetail;
    MQAvatarImageView *_headImgView;
    NSTextField *_nickNameTextField;
    NSTextField *_contactInfoTextField;
    id <ExtendedTableRowViewDelegate> _extendDelegate;
    NSButton *_gotoDetailBtn;
    NSLayoutConstraint *_nickNameTextFieldConstraint;
    SurpriseButton *_surpriseBtn;
    NSLayoutConstraint *_constraintContactInfoTextFieldWidth;
}

@property __weak NSLayoutConstraint *constraintContactInfoTextFieldWidth; // @synthesize constraintContactInfoTextFieldWidth=_constraintContactInfoTextFieldWidth;
@property __weak SurpriseButton *surpriseBtn; // @synthesize surpriseBtn=_surpriseBtn;
@property __weak NSLayoutConstraint *nickNameTextFieldConstraint; // @synthesize nickNameTextFieldConstraint=_nickNameTextFieldConstraint;
@property __weak NSButton *gotoDetailBtn; // @synthesize gotoDetailBtn=_gotoDetailBtn;
@property(nonatomic) __weak id <ExtendedTableRowViewDelegate> extendDelegate; // @synthesize extendDelegate=_extendDelegate;
@property __weak NSTextField *contactInfoTextField; // @synthesize contactInfoTextField=_contactInfoTextField;
@property __weak NSTextField *nickNameTextField; // @synthesize nickNameTextField=_nickNameTextField;
@property __weak MQAvatarImageView *headImgView; // @synthesize headImgView=_headImgView;
- (void).cxx_destruct;
- (id)getDisRemarkNameByMembers:(id)arg1 andDisName:(id)arg2;
- (void)setTitleAttrStr:(id)arg1 range:(struct _NSRange)arg2;
- (void)setInfoFieldAttrStr:(id)arg1 highlightRange:(struct _NSRange)arg2;
- (void)setBuddyDisplayNameStr:(id)arg1;
- (void)setContact:(id)arg1 withExtInfo:(id)arg2;
- (void)setOtherObject:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)createTrackingArea;
- (void)updateTrackingAreas;
- (void)dealloc;
- (void)setBackgroundStyle:(long long)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

