//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface MQTextBlockBaseView : NSView
{
    BOOL _isSelected;
    double _lastMouseDown;
    double _doubleClickInterval;
    struct NSEdgeInsets _margin;
}

@property(nonatomic) struct NSEdgeInsets margin; // @synthesize margin=_margin;
- (void)onSelectedChanged;
- (void)onOtherViewSelected:(id)arg1;
@property(nonatomic) BOOL isSelected;
- (void)topScrollViewDidEndScrollingWithFrame:(struct CGRect)arg1 inVisibleRect:(struct CGRect)arg2;
- (struct CGSize)layoutWithMaxSize:(struct CGSize)arg1 inVisibleRect:(struct CGRect)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (void)cancelSelected;
- (id)init;

@end

