//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BHMessageModel;

@interface MQUnreadMsgItem : NSObject
{
    unsigned long long _dwUin;
    int _chatType;
    long long _cbMsg;
    unsigned long long _time;
    BOOL _soundNotify;
    BOOL _bounceDockIcon;
    BOOL _showFloatHint;
    BHMessageModel *_msgModel;
}

@property(retain, nonatomic) BHMessageModel *msgModel; // @synthesize msgModel=_msgModel;
@property BOOL showFloatHint; // @synthesize showFloatHint=_showFloatHint;
@property BOOL bounceDockIcon; // @synthesize bounceDockIcon=_bounceDockIcon;
@property BOOL soundNotify; // @synthesize soundNotify=_soundNotify;
@property(nonatomic) unsigned long long time; // @synthesize time=_time;
@property(nonatomic) long long cbMsg; // @synthesize cbMsg=_cbMsg;
@property(nonatomic) int chatType; // @synthesize chatType=_chatType;
@property(nonatomic) unsigned long long dwUin; // @synthesize dwUin=_dwUin;
- (void).cxx_destruct;
- (id)addUserInfo:(id)arg1;
- (id)destURL;
- (void)resetAfterRead;
@property(readonly) struct _MESSAGE_RECORD_ID lastMsgRecordID;
- (void)removeMessageBefore:(unsigned long long)arg1;
- (int)addMessage:(id)arg1 MessageTail:(id)arg2;
- (BOOL)isMessageAlreadyExists:(id)arg1;
- (BOOL)isScheduleMsg;
- (BOOL)isRefResourceMsg;
- (BOOL)isAtMeMsg;
- (BOOL)isOfflineMsg;
- (id)textOfChatMsg;
- (unsigned long long)latestMsgTime;
- (id)messageArray;
- (unsigned long long)msgCountForDisplay;
- (unsigned long long)msgCount;
- (void)itemTitleCallBack:(id)arg1;
- (id)itemTitle;
- (id)itemIcon;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithUin:(unsigned long long)arg1 chatType:(int)arg2;

@end

