//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSImage, NSView, NSViewController;

@protocol MQWidgetInterface <NSObject>
- (void)didActivateNotificationWithUserInfo:(NSDictionary *)arg1;
- (NSImage *)logo;
- (void)clickWidget;
- (NSView *)badgeContainer;
- (void)modeChange:(unsigned long long)arg1;
- (NSViewController *)widgetController;
- (void)cleanup;
- (void)setDelegate:(id <MQWidgetDelegate>)arg1;
- (void)refresh;
- (id <MQWidgetInterface>)initWidget;

@optional
- (void)setAuthDelegate:(id <MQWidgetAuthDelegate>)arg1;
@end

