//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol MSFMPSubTcpDelegate <NSObject>
- (void)onConnect:(int)arg1 withState:(int)arg2 andExParam:(void *)arg3;

@optional
- (void)handleGoodNetwork:(int)arg1;
- (void)handleBadnetwork:(int)arg1;
@end

