//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSFWifiWebAuthDetectorInternal;

@interface MSFWifiWebAuthDetectorItem : NSObject
{
    int _lastResult;
    MSFWifiWebAuthDetectorInternal *_detector1;
    MSFWifiWebAuthDetectorInternal *_detector2;
}

@property(nonatomic) int lastResult; // @synthesize lastResult=_lastResult;
@property(retain, nonatomic) MSFWifiWebAuthDetectorInternal *detector2; // @synthesize detector2=_detector2;
@property(retain, nonatomic) MSFWifiWebAuthDetectorInternal *detector1; // @synthesize detector1=_detector1;
- (void)dealloc;

@end

