//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AddGroup, DelGroup, ModFriendGroup, ModGroupName, ModGroupSort;

@interface MsgType0x210SubMsgType0x17 : NSObject
{
    unsigned int dwOpType;
    AddGroup *stAddGroup;
    DelGroup *stDelGroup;
    ModGroupName *stModGroupName;
    ModGroupSort *stModGroupSort;
    ModFriendGroup *stModFriendGroup;
}

+ (void)parseMsgType0x210SubMsgType0x17:(struct MsgType0x210SubMsgType0x17 *)arg1;
@property(retain, nonatomic) ModFriendGroup *stModFriendGroup; // @synthesize stModFriendGroup;
@property(retain, nonatomic) ModGroupSort *stModGroupSort; // @synthesize stModGroupSort;
@property(retain, nonatomic) ModGroupName *stModGroupName; // @synthesize stModGroupName;
@property(retain, nonatomic) DelGroup *stDelGroup; // @synthesize stDelGroup;
@property(retain, nonatomic) AddGroup *stAddGroup; // @synthesize stAddGroup;
@property(nonatomic) unsigned int dwOpType; // @synthesize dwOpType;
- (void).cxx_destruct;

@end

