//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface MsgType0x211SubMsgType0x7_FTNNotify : NSObject
{
    long long _uSessionID;
    NSString *_strFileName;
    NSString *_strFileIndex;
    NSData *_strFileMd5;
    NSData *_strFileKey;
    long long _uFileLen;
    NSData *_strOriginfile_md5;
    unsigned int _uOriginfiletype;
    unsigned int _uGroupID;
    unsigned int _uGroupSize;
    unsigned int _uGroupCurrentIndex;
    unsigned int _uBatchID;
    unsigned int _uGroupFlag;
}

+ (id)parseFromMsgBodyPack:(struct CPBMessageDecoder *)arg1;
@property(nonatomic) unsigned int uBatchID; // @synthesize uBatchID=_uBatchID;
@property(nonatomic) unsigned int uGroupFlag; // @synthesize uGroupFlag=_uGroupFlag;
@property(nonatomic) unsigned int uGroupCurrentIndex; // @synthesize uGroupCurrentIndex=_uGroupCurrentIndex;
@property(nonatomic) unsigned int uGroupSize; // @synthesize uGroupSize=_uGroupSize;
@property(nonatomic) unsigned int uGroupID; // @synthesize uGroupID=_uGroupID;
@property(nonatomic) unsigned int uOriginfiletype; // @synthesize uOriginfiletype=_uOriginfiletype;
@property(retain, nonatomic) NSData *strOriginfile_md5; // @synthesize strOriginfile_md5=_strOriginfile_md5;
@property(nonatomic) long long uFileLen; // @synthesize uFileLen=_uFileLen;
@property(retain, nonatomic) NSData *strFileKey; // @synthesize strFileKey=_strFileKey;
@property(retain, nonatomic) NSData *strFileMd5; // @synthesize strFileMd5=_strFileMd5;
@property(retain, nonatomic) NSString *strFileIndex; // @synthesize strFileIndex=_strFileIndex;
@property(retain, nonatomic) NSString *strFileName; // @synthesize strFileName=_strFileName;
@property(nonatomic) long long uSessionID; // @synthesize uSessionID=_uSessionID;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

