//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface MsgType0x210SubMsgType0x24 : NSObject
{
    NSArray *_pluginFeedCountArray;
}

+ (id)parseFromMsgBodyPack:(struct MsgType0x210SubMsgType0x24 *)arg1;
@property(retain, nonatomic) NSArray *pluginFeedCountArray; // @synthesize pluginFeedCountArray=_pluginFeedCountArray;
- (void).cxx_destruct;

@end

