//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "HoverButtonDelegate.h"

@class NSArray, NSButton, NSDate, NSLayoutConstraint, NSMutableArray, NSPopover, NSString, NSTimer, NSView, NScheduleBaseView, NScheduleCreateViewController, NScheduleDetailViewController, NScheduleMonthViewController, NScheduleWeakViewController, ScheduleHotTipView, ScheduleModel, SelectMonthPopoverController, TXColorView, TXHoverButton;

@interface NScheduleMainViewController : NSViewController <HoverButtonDelegate>
{
    TXHoverButton *_closeButton;
    TXHoverButton *_createButton;
    TXColorView *_colorView;
    TXHoverButton *_headDayTitleView;
    TXHoverButton *_headMonthTitleView;
    TXHoverButton *_headYearTitleView;
    NSTimer *timer;
    NSDate *changeData;
    NSMutableArray *tipButtons;
    NSLayoutConstraint *tipViewHeightConstraint;
    BOOL tipOpened;
    NSArray *hotEvents;
    BOOL isMonthViewInited;
    BOOL isWeakViewInited;
    BOOL isHasOp;
    BOOL isDetailShowing;
    BOOL isFirstAddMonthPanel;
    BOOL isFirstAddWeakPanel;
    NSView *_lastDetailDependView;
    BOOL _isShowWeakPanel;
    BOOL _isShowDetailOrCreatePanel;
    BOOL _isCreating;
    BOOL _isDetailShowing;
    BOOL _isSelectMonthView;
    BOOL _isOpenScheduleCaseShowing;
    NSDate *_currentDate;
    NScheduleCreateViewController *_createViewController;
    NScheduleDetailViewController *_detailViewController;
    NScheduleWeakViewController *_weakViewController;
    NScheduleMonthViewController *_monthViewController;
    SelectMonthPopoverController *_selectMonthPopoverController;
    NSPopover *_selectMonthPopover;
    NSPopover *_detailPopover;
    NSArray *_schedules;
    NSLayoutConstraint *_gifWidthConstraint;
    TXColorView *_headBackgroundView;
    NSButton *_selectMonthButton;
    ScheduleHotTipView *_tipView;
    NSButton *_tipExpButton;
    NScheduleBaseView *_tipBgView;
    TXHoverButton *_backToday;
    ScheduleModel *_openScheduleCaseModel;
}

+ (id)shareMainViewController;
@property(retain, nonatomic) ScheduleModel *openScheduleCaseModel; // @synthesize openScheduleCaseModel=_openScheduleCaseModel;
@property(nonatomic) BOOL isOpenScheduleCaseShowing; // @synthesize isOpenScheduleCaseShowing=_isOpenScheduleCaseShowing;
@property BOOL isSelectMonthView; // @synthesize isSelectMonthView=_isSelectMonthView;
@property(retain) TXHoverButton *backToday; // @synthesize backToday=_backToday;
@property __weak NScheduleBaseView *tipBgView; // @synthesize tipBgView=_tipBgView;
@property __weak NSButton *tipExpButton; // @synthesize tipExpButton=_tipExpButton;
@property __weak ScheduleHotTipView *tipView; // @synthesize tipView=_tipView;
@property __weak NSButton *selectMonthButton; // @synthesize selectMonthButton=_selectMonthButton;
@property __weak TXColorView *headBackgroundView; // @synthesize headBackgroundView=_headBackgroundView;
@property __weak NSLayoutConstraint *gifWidthConstraint; // @synthesize gifWidthConstraint=_gifWidthConstraint;
@property(retain, nonatomic) NSArray *schedules; // @synthesize schedules=_schedules;
@property(retain, nonatomic) NSPopover *detailPopover; // @synthesize detailPopover=_detailPopover;
@property(retain, nonatomic) NSPopover *selectMonthPopover; // @synthesize selectMonthPopover=_selectMonthPopover;
@property(retain, nonatomic) SelectMonthPopoverController *selectMonthPopoverController; // @synthesize selectMonthPopoverController=_selectMonthPopoverController;
@property(retain, nonatomic) NScheduleMonthViewController *monthViewController; // @synthesize monthViewController=_monthViewController;
@property(retain, nonatomic) NScheduleWeakViewController *weakViewController; // @synthesize weakViewController=_weakViewController;
@property(retain, nonatomic) NScheduleDetailViewController *detailViewController; // @synthesize detailViewController=_detailViewController;
@property(retain, nonatomic) NScheduleCreateViewController *createViewController; // @synthesize createViewController=_createViewController;
@property(retain, nonatomic) NSDate *currentDate; // @synthesize currentDate=_currentDate;
@property(nonatomic) BOOL isDetailShowing; // @synthesize isDetailShowing=_isDetailShowing;
@property(nonatomic) BOOL isCreating; // @synthesize isCreating=_isCreating;
@property(nonatomic) BOOL isShowDetailOrCreatePanel; // @synthesize isShowDetailOrCreatePanel=_isShowDetailOrCreatePanel;
@property(nonatomic) BOOL isShowWeakPanel; // @synthesize isShowWeakPanel=_isShowWeakPanel;
- (void).cxx_destruct;
- (void)keyDown:(id)arg1;
- (void)delayTips:(id)arg1;
- (void)delaySelectScheduleWithModel:(id)arg1;
- (void)openScheduleWithScheduleId:(id)arg1 beginDate:(id)arg2 needShowCurrentDate:(BOOL)arg3;
- (void)handleCancelScheduleFailedNotification:(id)arg1;
- (void)handleCancelScheduleSuccessNotification;
- (void)handleDeleteScheduleFailedNotification:(id)arg1;
- (void)handleDeleteScheduleSuccessNotification;
- (void)handleModifyScheduleFailedNotification:(id)arg1;
- (void)handleModifyScheduleSuccessNotification;
- (void)handleCreateScheduleFailedNotification:(id)arg1;
- (void)handleCreateScheduleSuccessNotification:(id)arg1;
- (void)cancel:(id)arg1;
- (void)windowWillClose;
- (void)editSchedule:(id)arg1 needExAnimation:(BOOL)arg2;
- (void)viewSchedule:(id)arg1 dependView:(id)arg2;
- (void)deleteSchedule:(id)arg1 dependWindow:(id)arg2;
- (void)cancelSchedule:(id)arg1 dependWindow:(id)arg2;
- (void)createSchedule:(id)arg1 needShowHotScheduleTip:(BOOL)arg2 createSourceType:(unsigned long long)arg3;
- (void)createSchedule:(id)arg1 createSourceType:(unsigned long long)arg2;
- (void)createButtonClick:(id)arg1;
- (void)tipButtonClick:(id)arg1;
- (void)tipExp:(id)arg1;
- (void)backTodayClick;
- (void)viewDidLoad;
- (void)selectMonthClick:(id)arg1;
- (void)dealloc;
- (void)handleDateChanged:(id)arg1;
- (long long)lastDayOfTheMonth;
- (double)monthEndTimeStamp:(id)arg1;
- (double)monthStartTimeStamp:(id)arg1;
- (void)handleScheduleListChangedNotification;
- (void)refreshScheduleData:(id)arg1;
- (void)setDefaultDate:(id)arg1;
- (void)refreshSystemSchedules;
- (void)onImportSystemScheduleChanged:(id)arg1;
- (void)innerRefreshScheduleInfo;
- (void)refreshScheduleInfo;
- (void)checkNeedRefreshScheduleInfo;
- (void)handleHotTips;
- (void)handleScheduleBanner;
- (id)viewByIdentifier:(id)arg1;
- (BOOL)weekIsEqual:(id)arg1 and:(id)arg2;
- (void)setHeadYearTitle;
- (void)onExitHover:(id)arg1;
- (void)onEnterHover:(id)arg1;
- (void)handlePopoverWillCloseNotification:(id)arg1;
- (void)initNotification;
- (void)hasAnyOp;
- (void)removeWeakView;
- (void)removeMonthView;
- (void)addWeakViewRelativeTo:(id)arg1;
- (void)addMonthViewRelativeTo:(id)arg1;
- (void)initWeakView;
- (void)initMonthView;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

