//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImage.h"

@interface NSImage (MCStretchableImageExtensions)
- (void)setCacheImage:(BOOL)arg1;
- (void)drawInRect:(struct CGRect)arg1 isFlipped:(BOOL)arg2;
- (id)stretchableImageWithLeftCapWidth:(double)arg1 topCapHeight:(double)arg2;
@end

