//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MQSessionID, NSTimer, TChatBaseViewModel;

@interface OAConverter : NSObject
{
    TChatBaseViewModel *_viewModel;
    MQSessionID *_sessionId;
    NSTimer *_convertTimer;
    int _source;
}

+ (id)filePathOfMessageModel:(id)arg1;
+ (BOOL)existLocalFile:(id)arg1;
+ (BOOL)canBeConvertedToQQDoc:(id)arg1;
@property(nonatomic) int source; // @synthesize source=_source;
- (void).cxx_destruct;
- (void)refreshTChatMessageModel;
- (void)updateConvertStatus;
- (void)convertFinished:(BOOL)arg1 obj:(id)arg2;
- (BOOL)isSuccess:(BOOL)arg1 obj:(id)arg2;
- (void)convertToQQDoc;
- (id)initWithViewModel:(id)arg1 andSessionId:(id)arg2;

@end

