//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol OAResultProtocol <NSObject>

@optional
- (void)onRemoveOAResultViewModel:(id)arg1;
- (void)onShareClicked:(id)arg1;
- (void)onRetryClicked:(id)arg1;
- (void)onOpenUrlClicked:(id)arg1;
@end

