//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

#import "IOnlineFileDelegate.h"
#import "IOnlineFileMsgChannelDelegate.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface OnlineFileTransmissionProxy : QQBaseSingleton <IOnlineFileMsgChannelDelegate, IOnlineFileDelegate>
{
    NSObject<OS_dispatch_queue> *_queue;
}

- (void).cxx_destruct;
- (void)addLog:(id)arg1;
- (id)getRelayKey;
- (id)getRelaySignature;
- (unsigned long long)getUin;
- (BOOL)sendCCMsg:(id)arg1 cmd:(unsigned int)arg2 seq:(unsigned int)arg3 toUin:(unsigned long long)arg4 completion:(id)arg5;
- (void)setProxyType:(unsigned long long)arg1 address:(id)arg2 port:(unsigned short)arg3 account:(id)arg4 pwd:(id)arg5;
- (void)onCCMsgFromSDK:(unsigned long long)arg1 toUin:(unsigned long long)arg2 cmd:(unsigned short)arg3 seq:(unsigned short)arg4 time:(unsigned long long)arg5 data:(id)arg6;
- (BOOL)cancelFolder:(unsigned long long)arg1 sessionID:(unsigned long long)arg2;
- (BOOL)refuseFolder:(unsigned long long)arg1 sessionID:(unsigned long long)arg2;
- (BOOL)recvFolder:(unsigned long long)arg1 sessionID:(unsigned long long)arg2 taskInfo:(id)arg3;
- (BOOL)sendFolder:(id)arg1 toUin:(unsigned long long)arg2 taskInfo:(id)arg3;
- (BOOL)cancelFile:(unsigned long long)arg1 sessionID:(unsigned long long)arg2 reason:(unsigned long long)arg3;
- (BOOL)refuseFile:(unsigned long long)arg1 sessionID:(unsigned long long)arg2;
- (BOOL)recvFile:(unsigned long long)arg1 sessionID:(unsigned long long)arg2 taskInfo:(id)arg3;
- (BOOL)sendFile:(id)arg1 toUin:(unsigned long long)arg2 taskInfo:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

