//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextFieldCell.h"

@class NSImage;

@interface PluginsTableCell : NSTextFieldCell
{
    NSImage *_image;
    BOOL _pluginEnable;
    BOOL _isMouseOver;
    struct CGRect _enableStrRect;
}

@property BOOL isMouseOver; // @synthesize isMouseOver=_isMouseOver;
@property BOOL pluginEnable; // @synthesize pluginEnable=_pluginEnable;
@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (struct CGRect)pluginEnableRect:(struct CGRect)arg1;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)addTrackingAreasForView:(id)arg1 inRect:(struct CGRect)arg2 withUserInfo:(id)arg3 mouseLocation:(struct CGPoint)arg4;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

