//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProfileBaseViewController.h"

#import "GroupInfoDelegate.h"

@class NSString, ProfileGroupInfoViewController, ProfileGroupPreferenceViewController;

@interface ProfileGroupViewController : ProfileBaseViewController <GroupInfoDelegate>
{
    ProfileGroupInfoViewController *_groupInfoController;
    ProfileGroupPreferenceViewController *_groupPrefController;
    BOOL memberListViewAdd;
}

- (void).cxx_destruct;
- (void)scrollToBottom;
- (void)updateHeaderName:(id)arg1;
- (void)hideSetttingBtn;
- (void)updatePreference;
- (void)memberListBackClick;
- (void)manangerBtnClick:(BOOL)arg1;
- (void)onSettingBtnClick:(id)arg1;
- (void)hideGroupMemberListPage;
- (void)updateData:(unsigned long long)arg1 groupCode:(unsigned long long)arg2;
- (void)updateGroup:(id)arg1;
- (void)updateData:(unsigned long long)arg1;
- (void)updateData:(unsigned long long)arg1 withMemberUin:(id)arg2;
- (void)updateMemberUin:(id)arg1;
- (void)onAvatarChange:(id)arg1 imageColor:(long long)arg2;
- (id)createActiveHeaderView;
- (id)createPreferenceContent;
- (id)createInfoViewController;
- (void)initViewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

