//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProfileBaseViewController.h"

@class ProfileDisInfoViewController, ProfileDisPreferenceViewController;

@interface ProfileDiscussViewController : ProfileBaseViewController
{
    ProfileDisInfoViewController *_disInfoController;
    ProfileDisPreferenceViewController *_disPrefController;
    long long lastDicussCount;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)reloadData;
- (void)reloadDiscussProfileDataWithDelay;
- (void)doDestory;
- (void)handleDiscussEventNotification:(id)arg1;
- (void)willQuitDiscuss;
- (void)updateProfileEntityWithUin:(unsigned long long)arg1;
- (id)createPreferenceContent;
- (void)onAvatarChange:(id)arg1 imageColor:(long long)arg2;
- (id)createActiveHeaderView;
- (id)createInfoViewController;
- (void)initViewController;

@end

