//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BHMessageModel, NSArray, NSMutableArray;

@interface QC2CRoamMessageTask : NSObject
{
    int _targetMsgTime;
    int _state;
    int _requestCount;
    int _ssoSeq;
    int _loadCount;
    int _svrMinRoamTime;
    id <QC2CRoamMessageDelegate> _delegate;
    long long _uin;
    NSArray *_minMsgArray;
    BHMessageModel *_minModel;
    NSMutableArray *_cachedMessageArray;
}

@property(retain, nonatomic) NSMutableArray *cachedMessageArray; // @synthesize cachedMessageArray=_cachedMessageArray;
@property(retain, nonatomic) BHMessageModel *minModel; // @synthesize minModel=_minModel;
@property(retain, nonatomic) NSArray *minMsgArray; // @synthesize minMsgArray=_minMsgArray;
@property(nonatomic) int svrMinRoamTime; // @synthesize svrMinRoamTime=_svrMinRoamTime;
@property(nonatomic) int loadCount; // @synthesize loadCount=_loadCount;
@property(nonatomic) int ssoSeq; // @synthesize ssoSeq=_ssoSeq;
@property(nonatomic) int requestCount; // @synthesize requestCount=_requestCount;
@property(nonatomic) int state; // @synthesize state=_state;
@property(readonly) long long uin; // @synthesize uin=_uin;
@property(nonatomic) int targetMsgTime; // @synthesize targetMsgTime=_targetMsgTime;
@property(nonatomic) __weak id <QC2CRoamMessageDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getValidMessageList:(id)arg1;
- (id)getMinMessage:(id)arg1;
- (id)filterDeleteMsgList:(id)arg1;
- (void)storeServerResponseMsg:(id)arg1;
- (void)actionGetC2CRoamMessage:(id)arg1;
- (void)requestRoamMessageInOneDay;
- (void)loadMsgFromLocalOrRoam;
- (void)getMessageWithMinMsgArray:(id)arg1;
- (const char *)identityStr;
- (id)initWithUin:(long long)arg1;

@end

