//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableSet;

@interface QClusterMsgDS : NSObject
{
    int _sessType;
    int _requestBeginSeq;
    int _requestEndSeq;
    int _requestCount;
    int _state;
    int _serverMinSeq;
    int _roamMsgCount;
    id <QClusterMsgDSProtocol> _delegate;
    long long _clusterUin;
    NSMutableSet *_seqSet;
    NSMutableArray *_tmpLoadMessageCache;
    id _completionBlock;
}

@property(nonatomic) int roamMsgCount; // @synthesize roamMsgCount=_roamMsgCount;
@property(copy, nonatomic) id completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain) NSMutableArray *tmpLoadMessageCache; // @synthesize tmpLoadMessageCache=_tmpLoadMessageCache;
@property(retain) NSMutableSet *seqSet; // @synthesize seqSet=_seqSet;
@property(nonatomic) int serverMinSeq; // @synthesize serverMinSeq=_serverMinSeq;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) int requestCount; // @synthesize requestCount=_requestCount;
@property(nonatomic) int requestEndSeq; // @synthesize requestEndSeq=_requestEndSeq;
@property(nonatomic) int requestBeginSeq; // @synthesize requestBeginSeq=_requestBeginSeq;
@property(nonatomic) int sessType; // @synthesize sessType=_sessType;
@property(nonatomic) long long clusterUin; // @synthesize clusterUin=_clusterUin;
@property(nonatomic) __weak id <QClusterMsgDSProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cancleRequest;
- (void)notifyToUIWithGroupCode:(long long)arg1 onlyContinuity:(BOOL)arg2 error:(id)arg3;
- (void)insertMessageArray:(int)arg1 clusterUin:(long long)arg2 msgArray:(id)arg3;
- (BOOL)handleServerResponseMessage:(id)arg1;
- (int)requestGetGroupMessageWithBegin:(long long)arg1 end:(long long)arg2;
- (void)onGetMoreMessageOnlyLocal:(BOOL)arg1;
- (void)getCompleteMessageWithBegin:(int)arg1 end:(int)arg2 onlyLocal:(BOOL)arg3;
- (void)getClusterMessageWithBegin:(int)arg1 end:(int)arg2 onlyLocal:(BOOL)arg3;
- (void)syncRoamMessageWithCount:(int)arg1 complete:(id)arg2;
- (void)getLastMessageWithCount:(int)arg1 minSeq:(int)arg2 onlyLocal:(BOOL)arg3;
- (int)checkMessageContinuity:(id)arg1 begin:(int)arg2 end:(int)arg3 continuityCount:(int *)arg4;
- (id)getConsecutiveMsg:(id)arg1;
- (const char *)identityStr;
- (void)dealloc;
- (id)initWithClusterUin:(long long)arg1 sessType:(int)arg2;

@end

