//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQAVSetting : NSObject
{
}

+ (id)sharedSetting;
- (void)saveHasShowAVDecorate;
- (BOOL)isFirstShowAVDecorate;
- (BOOL)isFirstUseGroupAVIn3G;
- (BOOL)isFirstShowBeautyTipsAcceptAudio;
- (void)setValueOfAVBeautify:(float)arg1;
- (float)valueOfAVBeautify;
- (BOOL)isFirstUseAVBeautify;

@end

