//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQAVServiceProvider : NSObject
{
}

+ (BOOL)isDiscussGroupExist:(id)arg1;
+ (BOOL)isHRConfDiscussFinishedOnce:(id)arg1;
+ (BOOL)isHRConfDiscussReactivated:(id)arg1;
+ (BOOL)isHRConfCandidateInDiscussGroup:(id)arg1;
+ (BOOL)isHRGroupMeetingDiscussGroup:(id)arg1;
+ (BOOL)isQQConferenceDiscussGroup:(id)arg1;
+ (BOOL)isHRConferenceDiscussGroup:(id)arg1;
+ (BOOL)enableAddMemberForDiscussGroup:(id)arg1;
+ (int)networkTypeForReachabilityStatus:(long long)arg1;
+ (void)getGroupSilenceForGroupCode:(id)arg1 isGroupSilent:(char *)arg2 isBeSilent:(char *)arg3;
+ (id)sharedProvider;
- (void)recordNewModel:(id)arg1;
- (void)prepareUIForAVChating;
- (BOOL)isChatDisabledForPhoneNumber:(id)arg1;
- (BOOL)isInNotDisturbMode;
- (BOOL)isOnline;
- (BOOL)isConnected;
- (const char *)license;
- (id)IMEI;
- (id)defaultImageNamed:(id)arg1;
- (id)imageNamed:(id)arg1;
- (BOOL)isFriendNetworkWellWithUINString:(id)arg1;
- (BOOL)isFriendOnlineWithUINString:(id)arg1;
- (BOOL)isInDiscussGroup:(unsigned long long)arg1;
- (BOOL)isInGroup:(unsigned long long)arg1;
- (long long)groupUINForGroupCode:(unsigned long long)arg1;
- (BOOL)isFriendWithUIN:(unsigned long long)arg1;
- (id)displayNameForProfileModel:(id)arg1;
- (id)nameForCreateDiscussGroupWithMembers:(id)arg1;
- (void)updateInfoForDiscussGroupUIN:(unsigned long long)arg1 completion:(id)arg2;
- (unsigned long long)maximumMemberCountOfDiscussGroup;
- (id)membersForDiscussGroupUIN:(unsigned long long)arg1;
- (id)nameForDiscussGroupUIN:(unsigned long long)arg1;
- (unsigned long long)memberCountForDiscussGroupUIN:(unsigned long long)arg1;
- (id)nickForUIN:(unsigned long long)arg1 inGroupCode:(unsigned long long)arg2;
- (id)nickForUIN:(unsigned long long)arg1 inDiscussGroupUIN:(unsigned long long)arg2;
- (id)nickWithoutRemarkForUINString:(id)arg1;
- (id)nickForUINString:(id)arg1;
- (id)nickForUIN:(unsigned long long)arg1;
- (id)contactNameWithPhoneNumber:(id)arg1;
- (unsigned long long)temporaryUINForMobilePhone:(id)arg1 makeIfNotExist:(BOOL)arg2;
- (unsigned long long)lastLoginUIN;
- (unsigned long long)currentUIN;
- (id)currentUINString;
- (double)serverTimeInterval;

@end

