//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate;

@interface QQChatHistoryDayItem : NSObject
{
    NSDate *_day;
    NSArray *_messageIDs;
}

@property(retain, nonatomic) NSArray *messageIDs; // @synthesize messageIDs=_messageIDs;
@property(retain, nonatomic) NSDate *day; // @synthesize day=_day;
- (void).cxx_destruct;
- (id)description;

@end

