//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

@interface QQMessageDeleteEngine : QQBaseSingleton
{
}

- (void)deleteGroupMessage:(long long)arg1 completion:(id)arg2;
- (void)deleteDiscussMessage:(long long)arg1 completion:(id)arg2;
- (void)deleteC2CRoamMessage:(long long)arg1 completion:(id)arg2;
- (void)deleteAllMessage:(id)arg1 sessionType:(int)arg2 withRoam:(BOOL)arg3 completion:(id)arg4;
- (void)deleteAllMessage;
- (void)setClusterReqWithMsgArray:(id)arg1 drawReq:(struct PbMsgWithDrawReq *)arg2;
- (void)setC2CReqWithMsgArray:(id)arg1 drawReq:(struct PbMsgWithDrawReq *)arg2;
- (void)handleDeleteGroupMsgResp:(const struct PbGroupMsgWithDrawResp *)arg1 completion:(id)arg2;
- (void)handleDeleteC2CMsgResp:(const struct PbC2CMsgWithDrawResp *)arg1 completion:(id)arg2;
- (void)deleteRoamMessage:(id)arg1 completion:(id)arg2;
- (void)deleteMessage:(id)arg1 isRoam:(BOOL)arg2 completion:(id)arg3;

@end

