//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface QQNewsWidgetInfo : NSObject <NSCoding>
{
    NSString *_localTitle1;
    NSString *_localTitle2;
    NSString *_localTime1;
    NSString *_localTime2;
}

@property(copy, nonatomic) NSString *localTime2; // @synthesize localTime2=_localTime2;
@property(copy, nonatomic) NSString *localTime1; // @synthesize localTime1=_localTime1;
@property(copy, nonatomic) NSString *localTitle2; // @synthesize localTitle2=_localTitle2;
@property(copy, nonatomic) NSString *localTitle1; // @synthesize localTitle1=_localTitle1;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

