//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQSDK : NSObject
{
}

+ (void)swizzleMethods;
+ (const char *)sdkVersion;
+ (void)appWillTerminate;
+ (id)debugLevelString;
+ (int)debugLevel;
+ (void)setDebugLevel:(int)arg1;
+ (void)initWithDebugLevel:(int)arg1;

@end

