//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WloginTlv.h"

@class NSString;

@interface QRCodeTlv_4 : WloginTlv
{
    unsigned short wAccountType;
    NSString *sAccount;
}

@property(copy) NSString *sAccount; // @synthesize sAccount;
@property(nonatomic) unsigned short wAccountType; // @synthesize wAccountType;
- (void)dealloc;
- (int)decode:(char **)arg1 andBuffLen:(int *)arg2;

@end

