//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSData;

@interface QSDataVersionMgr : NSObject <NSCoding>
{
    int _dataVersion;
    NSData *_dataKey;
}

+ (id)GetInstance;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isVersionUpdateCanceled;
- (void)cancelToUpdateLatestDataVersion;
- (int)getLatestDataVersion;
- (void)updateToLatestDataVersion;
- (id)init;
@property(readonly, nonatomic) NSData *dataKey;
@property(nonatomic) int dataVersion; // @synthesize dataVersion=_dataVersion;

@end

