//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QSEngineManager : NSObject
{
    id _fileStorageEngine;
}

+ (id)instance;
- (void).cxx_destruct;
- (id)fileStorageEngine;
- (void)dealloc;
- (id)init;

@end

