//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class MQAIOWindow2, NSLayoutConstraint, NSString, NSView, QUIWindowTitleView;

@interface QUIWindowController : NSWindowController <NSWindowDelegate>
{
    unsigned long long _mode;
    QUIWindowTitleView *_titleViewContainer;
    NSView *_contentViewContainer;
    NSLayoutConstraint *_constraintTitleViewHeight;
    NSView *_nibContentView;
    MQAIOWindow2 *_mqWindow;
}

@property(retain, nonatomic) MQAIOWindow2 *mqWindow; // @synthesize mqWindow=_mqWindow;
@property(retain, nonatomic) NSView *nibContentView; // @synthesize nibContentView=_nibContentView;
@property(retain, nonatomic) NSLayoutConstraint *constraintTitleViewHeight; // @synthesize constraintTitleViewHeight=_constraintTitleViewHeight;
@property(retain, nonatomic) NSView *contentViewContainer; // @synthesize contentViewContainer=_contentViewContainer;
@property(retain, nonatomic) QUIWindowTitleView *titleViewContainer; // @synthesize titleViewContainer=_titleViewContainer;
- (void).cxx_destruct;
- (void)setContentView:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setTitleView:(id)arg1;
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
- (void)_initUI;
- (void)_initData;
- (id)initWithWindowNibName:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)windowDidLoad;
- (void)dealloc;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

