//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TXFloatWindowController.h"

@class NSImageView, NSLayoutConstraint, NSMutableArray, NSTextField, NSTimer, TXColorView, TXHoverButton;

@interface RedPackPushWindowController : TXFloatWindowController
{
    TXHoverButton *_closeBtn;
    NSMutableArray *_msgArr;
    BOOL _isShowShieldMenu;
    NSTimer *_timer;
    long long _autoCloseClock;
    TXColorView *_bgColorView;
    TXHoverButton *_btnShieldPush;
    NSImageView *_redpackLogoView;
    NSTextField *_nicknameText;
    NSTextField *_msgTipsText;
    NSTextField *_singleTipsText;
    TXColorView *_shieldView;
    TXHoverButton *_cancelBtn;
    TXHoverButton *_okBtn;
    NSTextField *_shieldTitleText;
    NSTextField *_shieldTipsText;
    NSLayoutConstraint *_shieldViewBottomConstraints;
    NSLayoutConstraint *_shieldViewWidth;
    TXColorView *_TipsView;
}

+ (BOOL)isRedPackWindowExist;
+ (id)defaultRedPackWindowController;
@property(retain) TXColorView *TipsView; // @synthesize TipsView=_TipsView;
@property __weak NSLayoutConstraint *shieldViewWidth; // @synthesize shieldViewWidth=_shieldViewWidth;
@property __weak NSLayoutConstraint *shieldViewBottomConstraints; // @synthesize shieldViewBottomConstraints=_shieldViewBottomConstraints;
@property __weak NSTextField *shieldTipsText; // @synthesize shieldTipsText=_shieldTipsText;
@property __weak NSTextField *shieldTitleText; // @synthesize shieldTitleText=_shieldTitleText;
@property __weak TXHoverButton *okBtn; // @synthesize okBtn=_okBtn;
@property __weak TXHoverButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain) TXColorView *shieldView; // @synthesize shieldView=_shieldView;
@property __weak NSTextField *singleTipsText; // @synthesize singleTipsText=_singleTipsText;
@property __weak NSTextField *msgTipsText; // @synthesize msgTipsText=_msgTipsText;
@property __weak NSTextField *nicknameText; // @synthesize nicknameText=_nicknameText;
@property __weak NSImageView *redpackLogoView; // @synthesize redpackLogoView=_redpackLogoView;
@property __weak TXHoverButton *btnShieldPush; // @synthesize btnShieldPush=_btnShieldPush;
@property __weak TXColorView *bgColorView; // @synthesize bgColorView=_bgColorView;
- (void).cxx_destruct;
- (void)handleRedpackPushPreferenceCheckState:(id)arg1;
- (void)removeMsgByUin:(long long)arg1;
- (void)addNewUnreadMsgOfBHMsgModel:(id)arg1 chatType:(int)arg2;
- (void)clickOKBtn:(id)arg1;
- (void)clickCancelBtn:(id)arg1;
- (void)clickShieldBtn:(id)arg1;
- (void)handleClickTips:(id)arg1;
- (void)timerUpdate;
- (void)resetAutoCloseTimer;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)delayCloseWindow;
- (void)hideShieldViewAnimation;
- (void)showShieldViewAnimation;
- (void)updateTipsByUnreadNum:(long long)arg1;
- (void)updateWindowHideState:(BOOL)arg1 byUIPart:(int)arg2;
- (id)loadCloseBtn;
- (void)loadShieldView;
- (void)loadContainerView;
- (void)_onClose:(id)arg1;
- (void)setWindowPosition;
- (void)prepareUI;
- (void)prepareData;
- (void)redPackWindowWillClose:(id)arg1;
- (void)windowDidLoad;
- (void)dealloc;
- (id)init;

@end

