//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RevokePushHandler : NSObject
{
}

+ (void)handleOnlinePushOidb0x20c:(const void *)arg1 DataLen:(unsigned long long)arg2;
+ (void)handleOnlinePushOidb0x2dc:(const void *)arg1 DataLen:(unsigned long long)arg2;
+ (void)handleOnlinePushMsgType0x210:(const void *)arg1 DataLen:(unsigned long long)arg2 msgSubType:(unsigned int)arg3;

@end

