//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TXColorView.h"

@class NSButton, NSImageView, NSTextField, ScheduleModel, TXHoverButton;

@interface SelectMemberView : TXColorView
{
    NSImageView *iconImageView;
    TXHoverButton *iconButtonView;
    NSTextField *titleTextField;
    NSButton *addButton;
    unsigned long long _uin;
    BOOL _isAdd;
    BOOL _isDelete;
    unsigned long long _groupCode;
    unsigned long long _sourceType;
    unsigned long long _discussUin;
    BOOL _editable;
    id <SelectMemberViewDelegate> _delegate;
    ScheduleModel *_schedule;
}

@property(retain, nonatomic) ScheduleModel *schedule; // @synthesize schedule=_schedule;
@property(nonatomic) __weak id <SelectMemberViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL editable; // @synthesize editable=_editable;
- (void).cxx_destruct;
- (void)handleHeaderIconDownloadNotification:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)mouseDown:(id)arg1;
- (void)buttonClick:(id)arg1;
- (void)setUin:(unsigned long long)arg1 groupCode:(unsigned long long)arg2 sourceCode:(long long)arg3 discussUin:(long long)arg4 isAdd:(BOOL)arg5;
- (void)setDeleteAll;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)buildView;
- (void)awakeFromNib;

@end

