//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface TaskDistinctUtil : NSObject
{
    NSMutableDictionary *_taskDict;
}

@property(retain) NSMutableDictionary *taskDict; // @synthesize taskDict=_taskDict;
- (void).cxx_destruct;
- (void)taskCompleteWithObjCallback:(id)arg1 sucessed:(BOOL)arg2 obj:(id)arg3 err:(id)arg4;
- (void)taskCompleteCallback:(id)arg1 sucessed:(BOOL)arg2 err:(id)arg3;
- (void)taskProgressCallback:(id)arg1 progressObj:(id)arg2 progress:(float)arg3;
- (BOOL)_tryAddNewTask:(id)arg1 completion:(id)arg2 completionWithObj:(id)arg3 progress:(id)arg4;
- (BOOL)tryAddNewTask:(id)arg1 completionHandler:(id)arg2 progress:(id)arg3;
- (BOOL)tryAddNewTask:(id)arg1 completionHandlerWithObj:(id)arg2 progress:(id)arg3;
- (BOOL)tryAddNewTask:(id)arg1 completion:(id)arg2 progress:(id)arg3;
- (BOOL)tryAddNewTask:(id)arg1 completionWithObj:(id)arg2 progress:(id)arg3;
- (id)init;

@end

