//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChatVirtualView.h"

@class NSString, NSTextField;

@interface TChatTextSectionView : TChatVirtualView
{
    NSString *_headerStr;
    NSTextField *_headerTextField;
}

@property(retain, nonatomic) NSTextField *headerTextField; // @synthesize headerTextField=_headerTextField;
@property(retain, nonatomic) NSString *headerStr; // @synthesize headerStr=_headerStr;
- (void).cxx_destruct;
- (id)viewAttributedDescription;
- (void)drawBackgroundInRect:(struct CGRect)arg1;
- (id)init;

@end

