//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TChatImageReferenceProtocol.h"
#import "TChatLoadImageOperationDelegate.h"
#import "TChatTextAttachmentCellProtocol.h"

@class BHMessageModel, NSString, QQImageMsgContentPart;

@interface TChatHistoryPictureViewModel : NSObject <TChatLoadImageOperationDelegate, TChatImageReferenceProtocol, TChatTextAttachmentCellProtocol>
{
    NSString *_referenceID;
    NSString *_localFilePath;
    long long _state;
    QQImageMsgContentPart *_imagePart;
    BHMessageModel *_msgModel;
    long long _imagePartIndex;
    id _loadCompleteBlock;
}

@property(copy, nonatomic) id loadCompleteBlock; // @synthesize loadCompleteBlock=_loadCompleteBlock;
@property(nonatomic) long long imagePartIndex; // @synthesize imagePartIndex=_imagePartIndex;
@property(retain, nonatomic) BHMessageModel *msgModel; // @synthesize msgModel=_msgModel;
- (void).cxx_destruct;
- (void)cancel;
- (void)reloadImage;
- (void)loadImageIfNeeded;
- (long long)imageState;
- (id)cellImage;
- (void)loadImage;
- (void)handleRefreshImageNotification:(id)arg1;
@property(readonly, nonatomic) NSString *picturePath;
- (id)fileKeyForPath:(id)arg1;
- (id)localFilePath;
- (id)fileKey;
- (id)referenceID;
@property(readonly, nonatomic) QQImageMsgContentPart *imagePart; // @synthesize imagePart=_imagePart;
- (id)ownerMsgModel;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

