//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChatListBasePresenter.h"

@class NSMutableArray;

@interface TChatCommonPickPresenter : TChatListBasePresenter
{
    NSMutableArray *_expandedItemUins;
}

- (void).cxx_destruct;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (BOOL)outlineView:(id)arg1 shouldCollapseItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldExpandItem:(id)arg2;
- (BOOL)canSelectAll:(id)arg1;
- (BOOL)outlineView:(id)arg1 isGroupItem:(id)arg2;
- (id)outlineView:(id)arg1 rowViewForItem:(id)arg2;
- (void)outlineView:(id)arg1 actionWithItem:(id)arg2;
- (void)onClickOutlineView:(id)arg1;
- (void)refreshOutlineView:(id)arg1;
- (void)configOutlineView:(id)arg1;
- (void)setExpandedItemUin:(id)arg1;
- (void)setDataArray:(id)arg1;
- (id)init;

@end

