//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSImageView, TXHoverButton;

@interface TChatTranslateHandler : NSView
{
    NSImageView *_loadingIcon;
    BOOL _isAIOMode;
    BOOL _isLoading;
    TXHoverButton *_retryBtn;
    id <TChatTranslateHandlerDelegate> _delegate;
}

@property(nonatomic) __weak id <TChatTranslateHandlerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) BOOL isLoading; // @synthesize isLoading=_isLoading;
@property(readonly, nonatomic) TXHoverButton *retryBtn; // @synthesize retryBtn=_retryBtn;
@property(nonatomic) BOOL isAIOMode; // @synthesize isAIOMode=_isAIOMode;
- (void).cxx_destruct;
- (void)didRetry;
- (void)showRetryButton;
- (void)stopLoading;
- (void)startLoading;
- (void)_initUI;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

