//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableView.h"

@class NSTrackingArea;

@interface TChatMenuTable : NSTableView
{
    NSTrackingArea *_trackingArea;
    id <TChatMenuTableDelegate> _menuDelegate;
}

@property(nonatomic) __weak id <TChatMenuTableDelegate> menuDelegate; // @synthesize menuDelegate=_menuDelegate;
- (void).cxx_destruct;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)updateTrackingAreas;
- (id)init;

@end

