//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChatAIOTipViewModel.h"

@interface TChatTranslateTipViewModel : TChatAIOTipViewModel
{
    id <TChatTranslateTipDelegate> _delegate;
}

@property(nonatomic) __weak id <TChatTranslateTipDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)outputMessageWithInformativeText:(id)arg1 time:(double)arg2 chatUIStyle:(int)arg3 background:(BOOL)arg4;
- (id)buildAttributeString;
- (id)text;

@end

