//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "WebDownloadDelegate.h"
#import "WebFrameLoadDelegate.h"
#import "WebPolicyDelegate.h"
#import "WebResourceLoadDelegate.h"
#import "WebUIDelegate.h"

@class MQSessionID, NSString, WebView;

@interface TChatHistoryRoamWindowController : NSWindowController <WebFrameLoadDelegate, WebUIDelegate, WebPolicyDelegate, WebDownloadDelegate, WebResourceLoadDelegate>
{
    MQSessionID *_sessionId;
    WebView *_roamMsgWebView;
}

+ (id)webScriptNameForSelector:(SEL)arg1;
+ (BOOL)isSelectorExcludedFromWebScript:(SEL)arg1;
@property(nonatomic) __weak WebView *roamMsgWebView; // @synthesize roamMsgWebView=_roamMsgWebView;
@property(retain, nonatomic) MQSessionID *sessionId; // @synthesize sessionId=_sessionId;
- (void).cxx_destruct;
- (void)RefreshRoamWebView;
- (BOOL)IfNeedValidate2M;
- (void)OnMoamMsgConfig:(id)arg1;
- (BOOL)bIsOnline;
- (BOOL)isMemberOpenRoam;
- (BOOL)isQQMember;
- (id)OnGetNickNames;
- (void)onSaveSig:(id)arg1;
- (void)OnVipConfig;
- (int)IsWanderRegistered;
- (void)windowDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

