//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TChatDayModel : NSObject
{
    BOOL _hasMessage;
    BOOL _inCurrentMonth;
    BOOL _showRedDot;
    long long _day;
    double _timeInterval;
}

@property(nonatomic) BOOL showRedDot; // @synthesize showRedDot=_showRedDot;
@property(nonatomic) BOOL inCurrentMonth; // @synthesize inCurrentMonth=_inCurrentMonth;
@property(nonatomic) BOOL hasMessage; // @synthesize hasMessage=_hasMessage;
@property(nonatomic) double timeInterval; // @synthesize timeInterval=_timeInterval;
@property(nonatomic) long long day; // @synthesize day=_day;

@end

