//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MQSessionID, NSMenu, NSView, TChatBaseViewModel, TChatCellBuilderOption, TXMenuItem;

@interface TChatAvatarAction : NSObject
{
    TChatCellBuilderOption *_option;
    BOOL _isSelf;
    TXMenuItem *_itemSendMsg;
    TXMenuItem *_itemCardItem;
    TXMenuItem *_itemAt;
    TXMenuItem *_itemQzone;
    TXMenuItem *_itemAddBuddyFromGroup;
    TXMenuItem *_itemDeleteFromGroup;
    TXMenuItem *_itemChangeRemark;
    TXMenuItem *_itemCreateDiscuss;
    NSMenu *_menu;
    MQSessionID *_sessionID;
    TChatBaseViewModel *_viewModel;
    NSView *_viewMenuIn;
}

@property(nonatomic) NSView *viewMenuIn; // @synthesize viewMenuIn=_viewMenuIn;
@property(nonatomic) BOOL isSelf; // @synthesize isSelf=_isSelf;
@property(retain, nonatomic) TChatBaseViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) MQSessionID *sessionID; // @synthesize sessionID=_sessionID;
@property(retain, nonatomic) NSMenu *menu; // @synthesize menu=_menu;
@property(retain, nonatomic) TXMenuItem *itemCreateDiscuss; // @synthesize itemCreateDiscuss=_itemCreateDiscuss;
@property(retain, nonatomic) TXMenuItem *itemChangeRemark; // @synthesize itemChangeRemark=_itemChangeRemark;
@property(retain, nonatomic) TXMenuItem *itemDeleteFromGroup; // @synthesize itemDeleteFromGroup=_itemDeleteFromGroup;
@property(retain, nonatomic) TXMenuItem *itemAddBuddyFromGroup; // @synthesize itemAddBuddyFromGroup=_itemAddBuddyFromGroup;
@property(retain, nonatomic) TXMenuItem *itemQzone; // @synthesize itemQzone=_itemQzone;
@property(retain, nonatomic) TXMenuItem *itemAt; // @synthesize itemAt=_itemAt;
@property(retain, nonatomic) TXMenuItem *itemCardItem; // @synthesize itemCardItem=_itemCardItem;
@property(retain, nonatomic) TXMenuItem *itemSendMsg; // @synthesize itemSendMsg=_itemSendMsg;
- (void).cxx_destruct;
- (void)onCreateDiscuss:(id)arg1;
- (void)onDeleteFromGroup:(id)arg1;
- (void)onAddBuddyFromGroup:(id)arg1;
- (void)onQzone:(id)arg1;
- (void)onAt:(id)arg1;
- (void)onProfileCard:(id)arg1;
- (void)onSendMsg:(id)arg1;
- (BOOL)_canRemark;
- (BOOL)_canRemoveUinFromGroup:(id)arg1;
- (void)jumpEditGroupCard;
- (id)_createMenuForGroup;
- (void)mouseDown:(id)arg1 inView:(id)arg2;
- (void)setViewModel:(id)arg1 andSessionID:(id)arg2 option:(id)arg3;

@end

