//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

#import "TChatHistoryFileViewModelDelegate.h"

@class EIMProgressView, MQSessionID, NSImageView, NSLayoutConstraint, NSString, NSTableView, NSTextField, TChatHistoryFileViewModel, TChatMenuController, TXHoverButton;

@interface TChatHistoryFileCellView : NSTableCellView <TChatHistoryFileViewModelDelegate>
{
    BOOL _isDataLine;
    NSTableView *_tableView;
    MQSessionID *_sessionID;
    NSImageView *_iconImageView;
    NSTextField *_nameTextField;
    NSTextField *_sizeTextField;
    NSTextField *_dateTextField;
    NSTextField *_senderTextField;
    NSTextField *_stateTextField;
    TXHoverButton *_operationBtn;
    TXHoverButton *_moreActionBtn;
    EIMProgressView *_progressView;
    NSLayoutConstraint *_dateLabelWidth;
    TChatHistoryFileViewModel *_fileViewModel;
    TChatMenuController *_tchatMenu;
}

@property(nonatomic) __weak TChatMenuController *tchatMenu; // @synthesize tchatMenu=_tchatMenu;
@property(nonatomic) __weak TChatHistoryFileViewModel *fileViewModel; // @synthesize fileViewModel=_fileViewModel;
@property(nonatomic) __weak NSLayoutConstraint *dateLabelWidth; // @synthesize dateLabelWidth=_dateLabelWidth;
@property(nonatomic) __weak EIMProgressView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) __weak TXHoverButton *moreActionBtn; // @synthesize moreActionBtn=_moreActionBtn;
@property(nonatomic) __weak TXHoverButton *operationBtn; // @synthesize operationBtn=_operationBtn;
@property(nonatomic) __weak NSTextField *stateTextField; // @synthesize stateTextField=_stateTextField;
@property(nonatomic) __weak NSTextField *senderTextField; // @synthesize senderTextField=_senderTextField;
@property(nonatomic) __weak NSTextField *dateTextField; // @synthesize dateTextField=_dateTextField;
@property(nonatomic) __weak NSTextField *sizeTextField; // @synthesize sizeTextField=_sizeTextField;
@property(nonatomic) __weak NSTextField *nameTextField; // @synthesize nameTextField=_nameTextField;
@property(nonatomic) __weak NSImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) MQSessionID *sessionID; // @synthesize sessionID=_sessionID;
@property(nonatomic) BOOL isDataLine; // @synthesize isDataLine=_isDataLine;
@property(retain, nonatomic) NSTableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)OnSaveImageToCustomiseFacesByMenu:(id)arg1;
- (void)doubleClick;
- (void)deleteItem:(id)arg1;
- (void)collectItem:(id)arg1;
- (void)onForward:(id)arg1;
- (BOOL)showForward;
- (void)opetateItem:(id)arg1;
- (void)showInFolder:(id)arg1;
- (void)refuseOnlineFile:(id)arg1;
- (void)cancelOnlineFile:(id)arg1;
- (void)addCommonMenuItem:(id)arg1;
- (void)addOnlineFileMenuItem:(id)arg1;
- (void)moreBtnClick:(id)arg1;
- (void)operateBtnClick:(id)arg1;
- (id)cellMenuForEvent:(id)arg1;
- (void)fileViewModelUpdated:(id)arg1;
- (void)updateWithViewModel:(id)arg1;
- (void)awakeFromNib;
- (void)setIsEditing:(BOOL)arg1;
- (void)drawRect:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

