//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@protocol TChatCalendarMsgDateServiceDelegate <NSObject>
- (void)getMessageDayListFromDate:(NSDate *)arg1 toDate:(NSDate *)arg2 complete:(void (^)(id, NSError *))arg3;
@end

