//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableRowView.h"

@class NSButton, NSColor;

@interface TChatPickerTableRowView : NSTableRowView
{
    NSButton *_expandBtn;
    NSColor *_selectionBackgroundColor;
}

@property(retain, nonatomic) NSColor *selectionBackgroundColor; // @synthesize selectionBackgroundColor=_selectionBackgroundColor;
- (void).cxx_destruct;
- (void)handleExpand;
- (void)didAddSubview:(id)arg1;
- (void)addSubview:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)isEmphasized;
- (void)drawSelectionInRect:(struct CGRect)arg1;
- (void)drawBackgroundInRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

