//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSEvent, NSMenu, TChatSelectPoint;

@protocol TChatEventProtocol <NSObject>
- (void)refreshWithType:(unsigned long long)arg1;
- (id)previeWithEvent:(NSEvent *)arg1;
- (void)clearSelection;
- (NSArray *)handleDragEvent:(NSEvent *)arg1;
- (unsigned long long)isPointInSelectedArea:(struct CGPoint)arg1;
- (void)handleHover:(struct CGPoint)arg1 enter:(BOOL)arg2;
- (void)handleTripleClick:(struct CGPoint)arg1;
- (id)handleDoubleClick:(struct CGPoint)arg1;
- (void)handleClick:(struct CGPoint)arg1;
- (NSMenu *)handleMenuEvent:(NSEvent *)arg1;
- (void)handleSelectEvent:(TChatSelectPoint *)arg1;
@end

