//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChatBaseContentView.h"

@class MQForwardMsgAttachment, MQForwardMsgAttachmentCell;

@interface TChatForwardMsgView : TChatBaseContentView
{
    MQForwardMsgAttachmentCell *_cell;
    MQForwardMsgAttachment *_attachment;
}

@property(retain) MQForwardMsgAttachment *attachment; // @synthesize attachment=_attachment;
@property(retain) MQForwardMsgAttachmentCell *cell; // @synthesize cell=_cell;
- (void).cxx_destruct;
- (id)handleMenuEvent:(id)arg1;
- (BOOL)TryDblClk:(id)arg1;
- (void)clickeEvent:(id)arg1;
- (BOOL)isFlipped;
- (void)updateCell;
- (void)mouseDown:(id)arg1;
- (void)update:(id)arg1 sessionID:(id)arg2;
- (id)dragImage;
- (void)setDrawSelectedRange:(BOOL)arg1;
- (BOOL)drawSelectedRange;
- (id)initWithOption:(id)arg1;
- (struct CGSize)bubbleSize;
- (double)currentScale;
- (void)drawCell;
- (void)drawRect:(struct CGRect)arg1;

@end

