//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, TChatCacheImage;

@interface TChatImageCacheModel : NSObject
{
    TChatCacheImage *_image;
    NSMutableDictionary *_operationDict;
    NSMutableArray *_referenceIDArray;
}

@property(retain, nonatomic) NSMutableArray *referenceIDArray; // @synthesize referenceIDArray=_referenceIDArray;
@property(retain, nonatomic) NSMutableDictionary *operationDict; // @synthesize operationDict=_operationDict;
@property(retain) TChatCacheImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)cancelOperationForReferenceObject:(id)arg1;
- (id)operationForReferenceObject:(id)arg1;
@property(readonly, nonatomic) BOOL releasable;
- (void)unRegisiterReferenceObject:(id)arg1;
- (void)regisiterReferenceObject:(id)arg1;
- (id)init;
- (void)dealloc;

@end

