//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChatAIOTipViewModel.h"

@interface TChatConfGroupTipsViewModel : TChatAIOTipViewModel
{
}

- (id)createGroupMemberListString:(id)arg1;
- (id)getGroupMemberUinList:(id)arg1;
- (void)initData;
- (id)outputMessageWithInformativeText:(id)arg1 time:(double)arg2 chatUIStyle:(int)arg3 background:(BOOL)arg4;
- (id)text;
- (id)initWithMessageModel:(id)arg1;

@end

