//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSArray, NSString;

@interface TChatPickerSearchOperation : NSOperation
{
    BOOL _isExecuting;
    BOOL _isFinished;
    BOOL _isCancelled;
    long long _searchItemCount;
    NSString *_keyword;
    NSArray *_allItemArray;
    id _completeBlock;
}

@property(copy, nonatomic) id completeBlock; // @synthesize completeBlock=_completeBlock;
@property(copy, nonatomic) NSArray *allItemArray; // @synthesize allItemArray=_allItemArray;
@property(copy, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
- (void).cxx_destruct;
- (id)getSearchResult;
- (void)changeValueForKeys:(id)arg1 withBlock:(id)arg2;
- (void)finishOperation;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (BOOL)isCancelled;
- (void)cancel;
- (void)start;
- (BOOL)isAsynchronous;
- (BOOL)isConcurrent;
- (void)dealloc;

@end

