//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSAttributedString, NSImage, NSString, NSTimer, NSTrackingArea, TXGIFImage;

@interface TXAudioView : NSView
{
    NSString *mRefGUID;
    unsigned long long mUin;
    int mTimeLen;
    NSAttributedString *strTimeLen;
    NSString *mAudioPath;
    TXGIFImage *gifImage;
    struct CGSize strSize;
    double _bgwidth;
    double _bgheight;
    double widthOfStrTimeLenInPix;
    struct CGPoint drawPoint;
    BOOL bIsSelf;
    BOOL _bIsAudioFileExist;
    BOOL _available;
    NSImage *bgImage;
    int audioViewStatus;
    BOOL bIsBeenShowing;
    BOOL bResend;
    NSTrackingArea *_trackingArea;
    int audioState;
    NSTimer *animateTimer;
    BOOL bIsAudioFileExist;
    BOOL isDownloading;
    double width;
    double height;
}

+ (id)createAudioImage:(id)arg1;
@property BOOL isDownloading; // @synthesize isDownloading;
@property BOOL bResend; // @synthesize bResend;
@property BOOL bIsBeenShowing; // @synthesize bIsBeenShowing;
@property int audioViewStatus; // @synthesize audioViewStatus;
@property struct CGPoint drawPoint; // @synthesize drawPoint;
@property(retain) NSString *mAudioPath; // @synthesize mAudioPath;
@property int mTimeLen; // @synthesize mTimeLen;
@property unsigned long long mUin; // @synthesize mUin;
@property NSString *mRefGUID; // @synthesize mRefGUID;
- (void).cxx_destruct;
- (void)needsDisplayOnTimer:(id)arg1;
- (void)stopAnimate;
- (void)startAnimate;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (void)stopAudioPlaying;
- (void)stopAudioPlaying:(id)arg1;
- (void)stopAudioPlayingWithTabClose:(id)arg1;
- (void)stopAudioPlayingWithWindowClose:(id)arg1;
- (void)stopAudioPlayingWithPlayEnded:(id)arg1;
- (void)stopAudioPlayingWithAnotherWillPlay:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (float)expandLength;
- (void)refreshWithTime:(int)arg1;
@property(readonly) BOOL bIsAudioFileExist; // @synthesize bIsAudioFileExist;
@property(readonly) double width; // @synthesize width;
@property(readonly) double height; // @synthesize height;
- (id)initWithUin:(unsigned long long)arg1 andAudioPath:(id)arg2 andTimeLength:(int)arg3 isSelf:(_Bool)arg4 withGUID:(id)arg5;

@end

