//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NSCursor, NSMutableDictionary, NSString, NSTrackingArea;

@interface TXButton : NSButton
{
    NSString *_buttonTitle;
    NSMutableDictionary *_buttonTitleAttributes;
    NSCursor *_buttonCursor;
    NSCursor *_buttonPreCursor;
    BOOL _needsTrackingArea;
    NSTrackingArea *_trackingArea;
}

@property(retain, nonatomic) NSMutableDictionary *buttonTitleAttributes; // @synthesize buttonTitleAttributes=_buttonTitleAttributes;
@property(retain, nonatomic) NSCursor *buttonPreCursor; // @synthesize buttonPreCursor=_buttonPreCursor;
@property(retain, nonatomic) NSCursor *buttonCursor; // @synthesize buttonCursor=_buttonCursor;
- (void).cxx_destruct;
- (void)mouseMoved:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (void)resetCursorRects;
- (void)setButtonCursor:(id)arg1 needsUpdateWhenMoved:(BOOL)arg2;
- (void)_refreshButtonAttributedTitle;
- (void)setTitleColor:(id)arg1;
- (void)setTitleFont:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)_initButton;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

