//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TXAudioView.h"

@interface TXBubbleAudioView : TXAudioView
{
    long long represent;
}

- (void)bubbleAudioImageUpateOthers:(id)arg1;
- (void)bubbleAudioImageUpateSelf:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (void)setBubbleImage:(BOOL)arg1;
- (BOOL)bIsAudioFileExist;
- (id)initWithUin:(unsigned long long)arg1 andAudioPath:(id)arg2 andTimeLength:(int)arg3 isSelf:(_Bool)arg4 withGUID:(id)arg5;
- (void)setAudioViewStatus:(int)arg1;

@end

