//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPanel.h"

@class NSMutableArray;

@interface TXItemPopPanel : NSPanel
{
    NSMutableArray *_itemArray;
}

- (void).cxx_destruct;
- (void)onTouchItemIndex:(long long)arg1;
- (struct CGRect)makePannelRect:(struct CGRect)arg1 items:(id)arg2;
- (id)createItems:(id)arg1 Rect:(struct CGRect)arg2;
- (id)createBlurView:(struct CGRect)arg1;
- (id)initWithContentRect:(struct CGRect)arg1 items:(id)arg2;

@end

