//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQEventTextView.h"

@class NSAttributedString;

@interface TXPlaceholderTextView : MQEventTextView
{
    NSAttributedString *placeHolderString;
    unsigned long long maxLength;
    unsigned long long stringEncodingFormat;
    struct CGPoint placeHolderPoint;
}

- (void).cxx_destruct;
- (void)adjustTextToLimitLength:(id)arg1;
- (void)didChangeText;
- (void)setMaxLength:(unsigned long long)arg1 stringEncodingFormat:(unsigned long long)arg2;
- (void)setPlaceHolderString:(id)arg1;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)setPlaceHolderString:(id)arg1 color:(id)arg2 startPoint:(struct CGPoint)arg3;
- (void)drawRect:(struct CGRect)arg1;
- (id)init;

@end

