//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TXColorView.h"

#import "NSGestureRecognizerDelegate.h"

@class NSButton, NSMutableArray, NSString, TXItemPopPanel;

@interface TXTouchBarView : TXColorView <NSGestureRecognizerDelegate>
{
    NSButton *_longPressBtn;
    long long _touchBarItemMode;
    TXItemPopPanel *_panelWin;
    id <TXTouchBarViewDelegate> _barDelegate;
    NSMutableArray *_touchButtonArray;
    NSMutableArray *_unReadSessionArray;
}

@property(retain, nonatomic) NSMutableArray *unReadSessionArray; // @synthesize unReadSessionArray=_unReadSessionArray;
@property(retain, nonatomic) NSMutableArray *touchButtonArray; // @synthesize touchButtonArray=_touchButtonArray;
@property(nonatomic) __weak id <TXTouchBarViewDelegate> barDelegate; // @synthesize barDelegate=_barDelegate;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)slideBtnString:(id)arg1;
- (id)changeString:(id)arg1 Status:(BOOL)arg2;
- (long long)slideTouchBarItem:(struct CGPoint)arg1;
- (void)onTouchDownItem:(struct CGPoint)arg1;
- (void)onTouchUpItem:(struct CGPoint)arg1;
- (void)onSlide:(id)arg1;
- (void)onClick:(id)arg1;
- (void)onLongPress:(id)arg1;
- (void)popUpPannelWindow;
- (void)orderOutPannelWindow;
- (id)createPanelWindow;
- (void)changeTouchBarItemMode:(long long)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (BOOL)isSampleMode;
- (void)onClickModeButton:(id)arg1;
- (void)onClickSearchButton:(id)arg1;
- (void)onClickMessageButton:(id)arg1;
- (void)addSubview:(id)arg1;
- (id)createModeButton;
- (id)createSearchButton;
- (id)createMessageButton;
- (void)onSlideClick:(id)arg1;
- (id)createSlideButton:(id)arg1 withRect:(struct CGRect)arg2;
- (void)createTouchBarViewSlideMode;
- (void)createTouchBarViewNormalMode;
- (void)removeAllSubViews;
- (void)hideAllSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

