//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UploadDataWrapper : NSObject
{
}

+ (id)decodeData:(id)arg1 sid:(int)arg2;
+ (id)getEchoPacket:(int)arg1 timestamp:(unsigned long long)arg2;
+ (id)getUploadPacketData:(id)arg1 segMent:(id)arg2;
+ (id)getQureyPacket:(id)arg1 segMent:(id)arg2;

@end

