//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BDHUploadSession, BDHUploadSessionMgr, NSDictionary;

@protocol UpSessionMgrDelegate <NSObject>

@optional
- (void)NotifySessionClear;
- (void)NotifyNoSessionAvailable;
- (void)sessionMgrNotifyApnChanged:(BDHUploadSessionMgr *)arg1 session:(BDHUploadSession *)arg2 info:(NSDictionary *)arg3;
- (void)sessionMgrNotifySendResultState:(BDHUploadSessionMgr *)arg1 session:(BDHUploadSession *)arg2 info:(NSDictionary *)arg3;
- (void)sessionMgrNotifyData:(BDHUploadSessionMgr *)arg1 session:(BDHUploadSession *)arg2 info:(NSDictionary *)arg3;
- (void)sessionMgrNotifyEvent:(BDHUploadSessionMgr *)arg1 session:(BDHUploadSession *)arg2 info:(NSDictionary *)arg3;
- (void)sessionMgrNotifyFail:(BDHUploadSessionMgr *)arg1 session:(BDHUploadSession *)arg2 info:(NSDictionary *)arg3;
- (void)sessionMgrNotifySuccess:(BDHUploadSessionMgr *)arg1 session:(BDHUploadSession *)arg2 info:(NSDictionary *)arg3;
@end

