//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WloginTlv.h"

@class NSString;

@interface WloginTlv_0x196 : WloginTlv
{
    unsigned char ucBackMobileState;
    NSString *sCountryCode;
    NSString *sBakMobile;
}

@property(copy) NSString *sBakMobile; // @synthesize sBakMobile;
@property(copy) NSString *sCountryCode; // @synthesize sCountryCode;
@property unsigned char ucBackMobileState; // @synthesize ucBackMobileState;
- (void)dealloc;
- (int)decode:(char **)arg1 andBuffLen:(int *)arg2;

@end

