//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMsgObserver.h"

@class NSString;

@interface QQBaseMsgHandler : NSObject <IMsgObserver>
{
}

+ (id)getFormattedTimeStringForQUint:(unsigned long long)arg1 dataAndTime:(BOOL)arg2;
- (void)processForSchedule:(const struct Elem *)arg1 toModel:(id)arg2;
- (void)processForYunPan:(const struct Elem *)arg1 toModel:(id)arg2;
- (void)processForImage:(const struct Elem *)arg1 toModel:(id)arg2 withDiction:(id)arg3;
- (void)dumpMessageData:(id)arg1 msg:(const struct Msg *)arg2;
- (void)commonHandleForProcosser:(id)arg1 msg:(const struct Msg *)arg2;
- (id)handleMsg:(const struct Msg *)arg1;
- (BOOL)parseMsgBody:(const MsgBody_1bee2359 *)arg1 msgType:(int)arg2 c2cCmd:(int)arg3 toModel:(id)arg4;
- (BOOL)parseContentHead:(const struct ContentHead *)arg1 toModel:(id)arg2;
- (BOOL)parseMsgHead:(const struct MsgHead *)arg1 toModel:(id)arg2;
- (id)peekOldOfflinePttAndPic:(const struct NotOnlineFile *)arg1 msgType:(int *)arg2;
- (id)peekTmpPttContent:(const struct TmpPtt *)arg1 msgType:(int *)arg2;
- (id)peekPttContent:(const struct Ptt *)arg1 msgType:(int *)arg2;
- (void)parseRichTextReserv:(const struct Ptt *)arg1 toModel:(id)arg2;
- (id)parseTransElement:(const struct TransElem *)arg1 msgType:(int *)arg2 toModel:(id)arg3;
- (id)parseTransElement:(const struct TransElem *)arg1 msgType:(int *)arg2;
- (void)handleEimInfo:(const struct EIMInfo *)arg1 toModel:(id)arg2;
- (BOOL)parseSrcMsg:(const struct RichText *)arg1 toDict:(id)arg2 srcSenderUin:(long long *)arg3;
- (void)parseRichText:(const struct RichText *)arg1 toModel:(id)arg2;
- (id)parseStructuredXMLMessage:(const struct RichText *)arg1 contentType:(int *)arg2;
- (id)parseNotOnlineImage:(const struct NotOnlineImage *)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

