//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureSession, NSObject<OS_dispatch_queue>, NSString;

@interface AVBaseCam : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate>
{
    AVCaptureSession *_session;
    NSObject<OS_dispatch_queue> *_sessionQueue;
    CScopePtr_1dd346cc _pCamCallBack;
    int _inputType;
    unsigned long long _state;
}

@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(nonatomic) int inputType; // @synthesize inputType=_inputType;
@property(nonatomic) CScopePtr_1dd346cc pCamCallBack; // @synthesize pCamCallBack=_pCamCallBack;
@property(nonatomic) NSObject<OS_dispatch_queue> *sessionQueue; // @synthesize sessionQueue=_sessionQueue;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onError:(id)arg1;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (id)MakeError:(id)arg1;
- (id)GetCaptureDevice;
- (id)InitSession;
- (void)SnapShot:(id)arg1 error:(id *)arg2;
- (void)setCaptureInfo:(int)arg1:(int)arg2:(int)arg3;
- (void)setCamCallBack:(struct IAVCameraCallBack *)arg1;
- (void)StopCam;
- (id)StartCam;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

