//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface BDHUploadSegMentHelper : NSObject
{
    long long _fileSize;
    int _curIndex;
    NSMutableArray *_holeArray;
    long long _curoffset;
}

@property(retain, nonatomic) NSMutableArray *holeArray; // @synthesize holeArray=_holeArray;
@property(nonatomic) long long fileSize; // @synthesize fileSize=_fileSize;
- (void)reset;
- (void)setStartRange:(long long)arg1;
- (void)setStartOffset:(long long)arg1;
- (id)getNextHole2:(int)arg1;
- (void)updateSvrHoleArray:(id)arg1;
- (BOOL)updateHoleState:(id)arg1;
- (id)getNextHole:(int)arg1;
- (void)updateHole:(id)arg1;
- (void)updateIndex:(id)arg1;
- (void)initHoleArray;
- (int)getHoleIndexMax:(id)arg1;
- (int)getHoleIndexMin:(id)arg1;
- (int)getHoleCount;
- (void)dealloc;

@end

