//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSTimer;

@interface BDHWritePacket : NSObject
{
    NSData *buffer;
    long long seqNo;
    double timeout;
    id target;
    NSTimer *_timer;
}

@property(nonatomic) id target; // @synthesize target;
@property(nonatomic) double timeout; // @synthesize timeout;
@property(nonatomic) long long seqNo; // @synthesize seqNo;
@property(retain, nonatomic) NSData *buffer; // @synthesize buffer;
- (void)dealloc;
- (void)invalidTimer;
- (id)initWithData:(id)arg1 delegate:(id)arg2 seqNo:(long long)arg3;

@end

