//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

@class NSMutableDictionary;

@interface BHAvatarManager : QQBaseSingleton
{
    NSMutableDictionary *_userAvatarDict;
    NSMutableDictionary *_groupAvatarDict;
}

- (void).cxx_destruct;
- (void)deleteFaceIdWithGroupCode:(unsigned long long)arg1 faceId:(unsigned int)arg2 completion:(id)arg3;
- (void)setDefaultFaceIdWithGroupCode:(unsigned long long)arg1 faceId:(unsigned int)arg2 completion:(id)arg3;
- (void)uploadFaceFileWithGroupCode:(unsigned long long)arg1 filePath:(id)arg2 completion:(id)arg3 progress:(id)arg4;
- (void)uploadMyNewAvatarWithPath:(id)arg1 progress:(id)arg2 completion:(id)arg3;
- (id)imageFilePath:(id)arg1 type:(long long)arg2;
- (void)_refreshAvatarMax20:(id)arg1 fromIndex:(int)arg2 type:(long long)arg3 download:(BOOL)arg4 notification:(id)arg5;
- (void)_refreshAvatar:(id)arg1 type:(long long)arg2 notification:(id)arg3 download:(BOOL)arg4 completion:(id)arg5;
- (void)downloadGroupAvatarWithGroupCode:(id)arg1 completion:(id)arg2;
- (void)downloadUserAvatarWithUIN:(id)arg1 completion:(id)arg2;
- (id)groupAvatarPathWithGroupCode:(id)arg1;
- (id)userAvatarPathWithUIN:(id)arg1 faceID:(int *)arg2;
- (id)userAvatarPathWithUIN:(id)arg1;
- (void)getUserAvatarInfoWithUIN:(id)arg1 completion:(id)arg2;
- (void)getUserAvatarURLWithUIN:(id)arg1 completion:(id)arg2;
- (id)init;

@end

