//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQModel_Internal.h"

@class BHCollectionAnchor, BHCollectionParagraph, BHCollectionPicInfo;

@interface BHCollectionItem : QQModel_Internal
{
    unsigned long long _type;
    BHCollectionParagraph *_paragraph;
    BHCollectionAnchor *_anchor;
    BHCollectionPicInfo *_picInfo;
}

@property(retain, nonatomic) BHCollectionPicInfo *picInfo; // @synthesize picInfo=_picInfo;
@property(retain, nonatomic) BHCollectionAnchor *anchor; // @synthesize anchor=_anchor;
@property(retain, nonatomic) BHCollectionParagraph *paragraph; // @synthesize paragraph=_paragraph;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

