//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQModel_Internal.h"

@class NSString;

@interface BHCollectionStyle : QQModel_Internal
{
    NSString *_color;
    NSString *_font_family;
    NSString *_font_weight;
    NSString *_font_size;
}

@property(copy, nonatomic) NSString *font_size; // @synthesize font_size=_font_size;
@property(copy, nonatomic) NSString *font_weight; // @synthesize font_weight=_font_weight;
@property(copy, nonatomic) NSString *font_family; // @synthesize font_family=_font_family;
@property(copy, nonatomic) NSString *color; // @synthesize color=_color;
- (void).cxx_destruct;

@end

