//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

#import "QQAccountEventObserver.h"

@class NSMutableDictionary, NSString;

@interface BHGroupFileListManager : QQBaseSingleton <QQAccountEventObserver>
{
    NSMutableDictionary *_cache;
}

- (void).cxx_destruct;
- (int)_appid;
- (void)requestDeleteFile:(id)arg1 completion:(id)arg2;
- (id)_convertFrom:(const struct FileInfo *)arg1 groupCode:(unsigned long long)arg2;
- (void)_getFileList:(unsigned long long)arg1 startIndex:(unsigned int)arg2 count:(unsigned int)arg3 sortBy:(unsigned int)arg4 completion:(id)arg5;
- (void)resumeDownload:(id)arg1 completion:(id)arg2 progress:(id)arg3;
- (void)downloadThumbnail:(id)arg1 completion:(id)arg2;
- (void)cancelDownload:(id)arg1;
- (void)downloadFAModel:(id)arg1 completion:(id)arg2 progress:(id)arg3;
- (void)loadMoreGroupFileList:(unsigned long long)arg1 completion:(id)arg2;
- (void)refreshGroupFileList:(unsigned long long)arg1 sortBy:(unsigned long long)arg2 completion:(id)arg3;
- (void)onDidChangeAccount;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

