//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IQQSMNode.h"

@class NSArray, NSDictionary, NSString;

@interface BHSMItemElementBase : NSObject <IQQSMNode>
{
    NSString *_elementName;
    NSDictionary *_attributes;
    NSString *_innerText;
    NSArray *_subElements;
    struct CGRect layoutFrame;
}

+ (id)SMNodeForElementName:(id)arg1;
@property(nonatomic) struct CGRect layoutFrame; // @synthesize layoutFrame;
@property(retain, nonatomic) NSArray *subElements; // @synthesize subElements=_subElements;
@property(retain, nonatomic) NSString *innerText; // @synthesize innerText=_innerText;
@property(retain, nonatomic) NSDictionary *attributes; // @synthesize attributes=_attributes;
@property(retain, nonatomic) NSString *elementName; // @synthesize elementName=_elementName;
- (void).cxx_destruct;
- (id)findElementWithName:(id)arg1 resursion:(BOOL)arg2;
- (id)valueForUndefinedKey:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)handleSubNodes:(id)arg1;
- (void)handleInnerText:(id)arg1;
- (void)handleAttrs:(id)arg1;
- (id)initWithElementName:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

