//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BHSMItemElementTextBase.h"

@interface BHSMItemElementTitle : BHSMItemElementTextBase
{
    long long _insetH;
    long long _insetV;
    BOOL isBlackBg;
    BOOL _isBlackBg;
}

@property(nonatomic) BOOL isBlackBg; // @synthesize isBlackBg=_isBlackBg;
@property(nonatomic) long long insetV; // @synthesize insetV=_insetV;
@property(nonatomic) long long insetH; // @synthesize insetH=_insetH;

@end

