//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BHSMItemElementBase.h"

@class NSString;

@interface BHSMItemElementTextBase : BHSMItemElementBase
{
    NSString *_color;
    NSString *_style;
    NSString *_size;
    int _numberOfLines;
}

@property(nonatomic) int numberOfLines; // @synthesize numberOfLines=_numberOfLines;
@property(retain, nonatomic) NSString *style; // @synthesize style=_style;
@property(retain, nonatomic) NSString *size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (BOOL)isBold;
- (void)dealloc;

@end

