//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

#import "BHMsgHandlerProtocol.h"

@class NSArray, NSLock, NSMutableSet, NSString;

@interface BHSystemMsgManager : QQBaseSingleton <BHMsgHandlerProtocol>
{
    unsigned long long _latest_friend_seq;
    unsigned long long _latest_group_seq;
    unsigned long long _following_friend_seq;
    unsigned long long _following_group_seq;
    unsigned int _unread_friend_count;
    unsigned int _unread_group_count;
    NSLock *_friendlock;
    NSLock *_grouplock;
    NSMutableSet *msgFilter;
    long long _language;
    NSArray *_friendSysMsgList;
    NSArray *_groupSysMsgList;
}

@property(readonly, copy, nonatomic) NSArray *groupSysMsgList; // @synthesize groupSysMsgList=_groupSysMsgList;
@property(readonly, copy, nonatomic) NSArray *friendSysMsgList; // @synthesize friendSysMsgList=_friendSysMsgList;
@property(nonatomic) long long language; // @synthesize language=_language;
- (void).cxx_destruct;
- (void)__didReceiveOnlinePush0x210_0x44:(id)arg1;
- (void)didReceiveRawData:(id)arg1;
- (BOOL)C2CMessageDidReceive:(id)arg1 fromPB:(const struct Msg *)arg2;
- (BOOL)C2CMessageWillReceive:(id)arg1 fromPB:(const struct Msg *)arg2;
- (void)clickButton:(id)arg1 completion:(id)arg2;
- (void)_reportReadedWithType:(unsigned int)arg1 checkType:(int)arg2 completion:(id)arg3;
- (void)clearGroupSystemMsgWithCompletion:(id)arg1;
- (void)clearFriendSystemMsgWithCompletion:(id)arg1;
- (void)reportReaded4GroupSysMsgWithCompletion:(id)arg1;
- (void)reportReaded4FriendSysMsgWithCompletion:(id)arg1;
- (id)_createSystemMsgBySturctMsg:(const struct StructMsg *)arg1;
- (void)_getSysMsgList:(int)arg1 appendMode:(BOOL)arg2 fromPush:(BOOL)arg3 completion:(id)arg4;
- (void)getGroupSysMsgListWithAppendMode:(BOOL)arg1 completion:(id)arg2;
- (void)getFriendSysMsgListWithAppendMode:(BOOL)arg1 completion:(id)arg2;
- (void)_createGroupSessionWithUIN:(unsigned long long)arg1 groupName:(id)arg2 isCreateGroup:(BOOL)arg3;
- (void)_createFriendSessionWithUIN:(unsigned long long)arg1 name:(id)arg2;
- (void)_createRecentTabForSystemMsg:(id)arg1 structMsg:(struct StructMsg *)arg2 content:(id)arg3 fromPush:(BOOL)arg4;
- (void)_networkDidReconnected:(id)arg1;
- (void)onDidChangeAccount;
- (BOOL)isMsgExist:(const struct MsgHead *)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

