//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDataDelegate.h"

@class NSMutableDictionary, NSString, NSURLSession, TaskDistinctUtil;

@interface BHURLTaskManager : NSObject <NSURLSessionDataDelegate>
{
    NSMutableDictionary *_taskCache;
    NSMutableDictionary *_tmpFileCache;
    NSURLSession *_uploadUrlSession;
    NSURLSession *_downloadUrlSession;
    TaskDistinctUtil *_taskFilter;
}

+ (id)fileManager;
+ (id)defaultManager;
- (void).cxx_destruct;
- (void)test;
- (void)_doUploadCompletionBlock:(unsigned long long)arg1 successed:(BOOL)arg2 object:(id)arg3 error:(id)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;
- (id)_uploadUrlRequest:(id)arg1 body:(id)arg2 completion:(id)arg3;
- (id)uploadWithUrl:(id)arg1 reqHeaders:(id)arg2 packetBlock:(id)arg3 packetResultBlock:(id)arg4 completionBlock:(id)arg5;
- (id)uploadWithUrl:(id)arg1 fromFilePath:(id)arg2 reqHeaders:(id)arg3 completionBlock:(id)arg4 progressBlock:(id)arg5;
- (unsigned long long)_appendWrite2File:(id)arg1 data:(id)arg2 err:(id *)arg3;
- (unsigned long long)_getTotalFileSize:(id)arg1;
- (id)_getTmpFilePathWithFilePath:(id)arg1;
- (void)_doCompletionBlock:(id)arg1 suc:(BOOL)arg2 retry:(BOOL)arg3 err:(id)arg4;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (unsigned long long)_getTaskID;
- (id)_downloadWithUrl:(id)arg1 toFilePath:(id)arg2 reqHeaders:(id)arg3 taskID:(unsigned long long)arg4 completionBlock:(id)arg5 progressBlock:(id)arg6;
- (id)downloadWithUrlList:(id)arg1 toFilePath:(id)arg2 reqHeaders:(id)arg3 completionBlock:(id)arg4 progressBlock:(id)arg5;
- (id)downloadWithURL:(id)arg1 toFilePath:(id)arg2 reqHeaders:(id)arg3 completionBlock:(id)arg4 progressBlock:(id)arg5;
- (void)prepareProxyConfiguration:(id)arg1;
- (id)initWithTimeOutInterval:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

