//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Catcher : NSObject
{
    Class _origClass;
}

@property(nonatomic) Class origClass; // @synthesize origClass=_origClass;
- (id)autorelease;
- (oneway void)release;
- (id)mutableCopy;
- (id)copy;
- (id)retain;
- (void)dealloc;
- (id)forwardingTargetForSelector:(SEL)arg1;

@end

