//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class ConfComplicateViewController, NSTrackingArea;

@interface ConfComplicateView : NSView
{
    NSTrackingArea *_trackingArea;
    BOOL _isMouseIn;
    ConfComplicateViewController *_controller;
}

@property(nonatomic) BOOL isMouseIn; // @synthesize isMouseIn=_isMouseIn;
@property(nonatomic) ConfComplicateViewController *controller; // @synthesize controller=_controller;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (BOOL)mouseDownCanMoveWindow;
- (void)updateTrackingAreas;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)init;

@end

