//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSArray, NSString, single_count;

@interface count_info : JceObjectV2
{
    single_count *jcev2_p_0_o_stCount;
    NSArray *jcev2_p_1_o_vecUinList__b0x9i_VOfeed_host_info;
    NSString *jcev2_p_2_o_trace_info;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_trace_info, setter=setJce_trace_info:) NSString *jcev2_p_2_o_trace_info; // @synthesize jcev2_p_2_o_trace_info;
@property(retain, nonatomic, getter=jce_vecUinList, setter=setJce_vecUinList:) NSArray *jcev2_p_1_o_vecUinList__b0x9i_VOfeed_host_info; // @synthesize jcev2_p_1_o_vecUinList__b0x9i_VOfeed_host_info;
@property(retain, nonatomic, getter=jce_stCount, setter=setJce_stCount:) single_count *jcev2_p_0_o_stCount; // @synthesize jcev2_p_0_o_stCount;
- (void).cxx_destruct;
- (id)init;

@end

