//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DataLineFileStorage : NSObject
{
}

+ (id)getInstance;
- (void)onDBChanged:(id)arg1;
- (BOOL)deleteAllinDb:(id)arg1;
- (BOOL)deleteAll;
- (BOOL)DeleteFileListByGroupID:(unsigned int)arg1 inDb:(id)arg2;
- (BOOL)DeleteFileListByGroupID:(unsigned int)arg1;
- (id)GetGroupListByGroupID:(unsigned int)arg1 inDb:(id)arg2;
- (id)GetGroupListByGroupID:(unsigned int)arg1;
- (_Bool)updateFileDirectdownloadUrl:(id)arg1 sessionID:(unsigned long long)arg2 inDb:(id)arg3;
- (BOOL)updateFileDirectdownloadUrl:(id)arg1 sessionID:(unsigned long long)arg2;
- (_Bool)updateFileIndex:(id)arg1 sessionID:(unsigned long long)arg2 inDb:(id)arg3;
- (BOOL)updateFileIndex:(id)arg1 sessionID:(unsigned long long)arg2;
- (_Bool)updateFileStatus:(unsigned int)arg1 sessionID:(unsigned long long)arg2 inDb:(id)arg3;
- (BOOL)updateFileStatus:(unsigned int)arg1 sessionID:(unsigned long long)arg2;
- (BOOL)addFileItem:(id)arg1 FilePath:(id)arg2 FileName:(id)arg3 FileSize:(id)arg4 FileStatus:(id)arg5 FileMD5:(id)arg6 ThumbFileMd5:(id)arg7 GroupID:(id)arg8 GroupIndex:(id)arg9 MsgTime:(id)arg10 isSend:(id)arg11;
- (_Bool)addFileItem:(id)arg1 FilePath:(id)arg2 FileName:(id)arg3 FileSize:(id)arg4 FileStatus:(id)arg5 FileMD5:(id)arg6 ThumbFileMd5:(id)arg7 GroupID:(id)arg8 GroupIndex:(id)arg9 MsgTime:(id)arg10 isSend:(id)arg11 inDb:(id)arg12;
- (void)creatFileManageTable:(id)arg1 withVersion:(id)arg2;
- (unsigned long long)getTableSign;
- (void)creatFileManageTable:(id)arg1;
- (id)init;

@end

