//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface EIMMenuItemModel : NSObject
{
    BOOL _enable;
    NSString *_Title;
    NSString *_Key;
}

@property(nonatomic) BOOL enable; // @synthesize enable=_enable;
@property(retain, nonatomic) NSString *Key; // @synthesize Key=_Key;
@property(retain, nonatomic) NSString *Title; // @synthesize Title=_Title;
- (void).cxx_destruct;
- (id)init;

@end

