//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface EmojiSSORequest : NSObject
{
    int _seq;
    id _context;
}

@property(nonatomic) int seq; // @synthesize seq=_seq;
@property(retain, nonatomic) id context; // @synthesize context=_context;
- (void).cxx_destruct;
- (void)dealloc;

@end

