//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface EmotionEggs : NSObject
{
    NSArray *_keyword;
    NSArray *_scenes;
    long long _allEmotionCount;
}

@property(nonatomic) long long allEmotionCount; // @synthesize allEmotionCount=_allEmotionCount;
@property(retain, nonatomic) NSArray *scenes; // @synthesize scenes=_scenes;
@property(retain, nonatomic) NSArray *keyword; // @synthesize keyword=_keyword;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

