//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

#import "QQAccountEventObserver.h"

@class FAEventHandler, FATransferMgrDown, FATransferMgrUp, NSString, NSThread;

@interface FATransferMgr : QQBaseSingleton <QQAccountEventObserver>
{
    FAEventHandler *_delegate;
    NSString *_selfUin;
    NSThread *_httpThread;
    FATransferMgrUp *_upMgr;
    FATransferMgrDown *_downMgr;
}

- (void).cxx_destruct;
- (void)stopComponent;
- (void)donothingatall;
- (void)httpThreadProc;
- (void)stopHttpThread;
- (id)httpThread;
- (BOOL)cancelFile:(id)arg1;
- (void)resumeSendFile:(id)arg1 completion:(id)arg2 progress:(id)arg3;
- (void)recvFile:(id)arg1 completion:(id)arg2 progress:(id)arg3;
- (id)sendFile:(id)arg1 toTraget:(id)arg2 completion:(id)arg3 progress:(id)arg4;
- (void)reForwardFile:(id)arg1 completion:(id)arg2 progress:(id)arg3;
- (id)forwardFile:(id)arg1 toTarget:(id)arg2 completion:(id)arg3;
- (BOOL)cancel:(id)arg1;
- (void)resumeSend:(id)arg1 completion:(id)arg2 progress:(id)arg3;
- (id)send:(id)arg1 toTraget:(id)arg2 completion:(id)arg3 progress:(id)arg4;
- (void)resumeRecv:(id)arg1 completion:(id)arg2 progress:(id)arg3;
- (void)recv:(id)arg1 completion:(id)arg2 progress:(id)arg3;
- (void)onDidChangeAccount;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

