//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IEngineDispatchDelegate.h"

@class FATaskInfoUpload, IEngineDispatchDelegateNonRetian, NSMutableURLRequest, NSString, NSTimerNonRetain;

@interface FAUpRequest : NSObject <IEngineDispatchDelegate>
{
    int _logId;
    unsigned long long _nRetryCount;
    int _reqSeq;
    int _lastFailCode;
    double _startTime;
    unsigned int _requestCount;
    FATaskInfoUpload *_fileInfo;
    NSTimerNonRetain *_downloadTimeOutTimer;
    NSString *_dataReportId;
    NSString *_dataReportDetailId;
    NSMutableURLRequest *_urlRequest;
    NSString *_lastErrorDisc;
    IEngineDispatchDelegateNonRetian *_csDelegate;
    id <FAUpRequestDelegate> _delegate;
}

@property(nonatomic) __weak id <FAUpRequestDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) IEngineDispatchDelegateNonRetian *csDelegate; // @synthesize csDelegate=_csDelegate;
@property(retain, nonatomic) NSString *lastErrorDisc; // @synthesize lastErrorDisc=_lastErrorDisc;
@property(retain, nonatomic) NSMutableURLRequest *urlRequest; // @synthesize urlRequest=_urlRequest;
@property(copy, nonatomic) NSString *dataReportDetailId; // @synthesize dataReportDetailId=_dataReportDetailId;
@property(copy, nonatomic) NSString *dataReportId; // @synthesize dataReportId=_dataReportId;
@property(retain, nonatomic) NSTimerNonRetain *downloadTimeOutTimer; // @synthesize downloadTimeOutTimer=_downloadTimeOutTimer;
@property(retain, nonatomic) FATaskInfoUpload *fileInfo; // @synthesize fileInfo=_fileInfo;
- (void).cxx_destruct;
- (BOOL)canBeDelete;
- (void)notifyError:(id)arg1;
- (void)didRecievedMsg:(CDStruct_a00ab4be)arg1;
- (void)OnRequestSend:(unsigned int)arg1;
- (void)dataReport:(int)arg1 errorDisc:(id)arg2 reportcollect:(BOOL)arg3 reportDetail:(BOOL)arg4;
- (void)dealloc;
- (void)stop;
- (void)cancel;
- (void)setTimeoutTimer;
- (void)stopTimer;
- (void)onTimedOut;
- (void)internalRequest;
- (void)OnComplete:(BOOL)arg1 serverTip:(id)arg2;
- (BOOL)isCanRetry;
- (void)request:(id)arg1;
- (id)init:(int)arg1 fileInfo:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

