//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@interface feed_info : JceObjectV2
{
    unsigned int jcev2_p_0_o_uOrgFeedTime;
    unsigned int jcev2_p_1_o_uFeedCTime;
    unsigned int jcev2_p_2_o_uOrgFeedUin;
}

+ (id)jceType;
+ (void)initialize;
@property(nonatomic, getter=jce_uOrgFeedUin, setter=setJce_uOrgFeedUin:) unsigned int jcev2_p_2_o_uOrgFeedUin; // @synthesize jcev2_p_2_o_uOrgFeedUin;
@property(nonatomic, getter=jce_uFeedCTime, setter=setJce_uFeedCTime:) unsigned int jcev2_p_1_o_uFeedCTime; // @synthesize jcev2_p_1_o_uFeedCTime;
@property(nonatomic, getter=jce_uOrgFeedTime, setter=setJce_uOrgFeedTime:) unsigned int jcev2_p_0_o_uOrgFeedTime; // @synthesize jcev2_p_0_o_uOrgFeedTime;
- (id)init;

@end

