//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "FSRPresenterDelegate.h"
#import "MQContactTableRowViewDelegate.h"
#import "MQContactsViewControllerDelegate.h"
#import "NSOutlineViewDataSource.h"
#import "NSOutlineViewDelegate.h"
#import "OnFocusChangeDelegate.h"
#import "OnTextChangeDelegate.h"

@class BorderEditText, FSRelationCommonPresenter, FSRelationSearchPresenter, ForwardSelectorRelationViewController, NSButton, NSLayoutConstraint, NSMutableArray, NSOutlineView, NSString, NSTextField, NSView, TXColorView;

@interface ForwardSelectorViewController : NSViewController <MQContactsViewControllerDelegate, NSOutlineViewDelegate, NSOutlineViewDataSource, OnFocusChangeDelegate, OnTextChangeDelegate, FSRPresenterDelegate, MQContactTableRowViewDelegate>
{
    BOOL _isContainSelf;
    BOOL _isExceptSelf;
    BOOL _isDeletable;
    long long _selectedMaxCount;
    NSString *_footerText;
    id _okBlock;
    id _cancelBlock;
    NSButton *_btnOK;
    NSButton *_btnCancel;
    NSView *_leftContainer;
    NSView *_rightContainer;
    NSTextField *_selectedCountTitle;
    BorderEditText *_searchBox;
    NSOutlineView *_selectedOutlineView;
    TXColorView *_verLine;
    TXColorView *_horLine;
    NSTextField *_lbFooterText;
    NSLayoutConstraint *_footerTextHeightConstraint;
    NSMutableArray *_selectedDataSource;
    ForwardSelectorRelationViewController *_contactViewController;
    ForwardSelectorRelationViewController *_searchViewController;
    FSRelationSearchPresenter *_searchPresenter;
    FSRelationCommonPresenter *_commonPresenter;
    NSView *_searchView;
    NSView *_contactView;
}

@property BOOL isDeletable; // @synthesize isDeletable=_isDeletable;
@property(retain) NSView *contactView; // @synthesize contactView=_contactView;
@property(retain) NSView *searchView; // @synthesize searchView=_searchView;
@property(retain) FSRelationCommonPresenter *commonPresenter; // @synthesize commonPresenter=_commonPresenter;
@property(retain) FSRelationSearchPresenter *searchPresenter; // @synthesize searchPresenter=_searchPresenter;
@property(retain) ForwardSelectorRelationViewController *searchViewController; // @synthesize searchViewController=_searchViewController;
@property(retain) ForwardSelectorRelationViewController *contactViewController; // @synthesize contactViewController=_contactViewController;
@property(retain) NSMutableArray *selectedDataSource; // @synthesize selectedDataSource=_selectedDataSource;
@property __weak NSLayoutConstraint *footerTextHeightConstraint; // @synthesize footerTextHeightConstraint=_footerTextHeightConstraint;
@property __weak NSTextField *lbFooterText; // @synthesize lbFooterText=_lbFooterText;
@property __weak TXColorView *horLine; // @synthesize horLine=_horLine;
@property __weak TXColorView *verLine; // @synthesize verLine=_verLine;
@property __weak NSOutlineView *selectedOutlineView; // @synthesize selectedOutlineView=_selectedOutlineView;
@property __weak BorderEditText *searchBox; // @synthesize searchBox=_searchBox;
@property __weak NSTextField *selectedCountTitle; // @synthesize selectedCountTitle=_selectedCountTitle;
@property __weak NSView *rightContainer; // @synthesize rightContainer=_rightContainer;
@property __weak NSView *leftContainer; // @synthesize leftContainer=_leftContainer;
@property __weak NSButton *btnCancel; // @synthesize btnCancel=_btnCancel;
@property __weak NSButton *btnOK; // @synthesize btnOK=_btnOK;
@property(copy) id cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(copy) id okBlock; // @synthesize okBlock=_okBlock;
- (void).cxx_destruct;
- (void)deleteButtonClicked:(id)arg1;
- (void)controlTextDidEndEditing:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)controlTextDidBeginEditing:(id)arg1;
- (void)onFocusChange:(id)arg1 hasFocus:(BOOL)arg2;
- (BOOL)didSelectedItem:(id)arg1;
- (void)_removeSelectedItem:(id)arg1;
- (BOOL)_linkageContainsObject:(id)arg1;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)_delButtonClick:(id)arg1;
- (void)didSelectedFolderItem:(id)arg1;
- (void)btnOKClick:(id)arg1;
- (void)btnCancelClick:(id)arg1;
- (void)_setFooter;
- (void)_setTitle;
- (void)setSelectedItems:(id)arg1 isDeletable:(BOOL)arg2;
@property BOOL isContainSelf; // @synthesize isContainSelf=_isContainSelf;
@property BOOL isExceptSelf; // @synthesize isExceptSelf=_isExceptSelf;
@property long long selectedMaxCount; // @synthesize selectedMaxCount=_selectedMaxCount;
@property(copy) NSString *footerText; // @synthesize footerText=_footerText;
- (void)_setOKBtnEnable:(BOOL)arg1;
- (void)_initData;
- (void)awakeFromNib;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

