//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface GroupAudioChatModel : NSObject
{
    NSMutableArray *_memSpeakCache;
    unsigned long long _prepareRequestViewUin;
    int _prepareRequestViewType;
    char *_pVideoBuffer;
    BOOL _isSelfIn;
    BOOL _isFriendIn;
    BOOL _isRoomConnected;
    int _groupChatType;
    int _requestViewType;
    id <GAChatStateChangeProtocal> _delegate;
    NSMutableArray *_memUinArray;
    long long _groupUin;
    unsigned long long _selfUin;
    unsigned long long _requestViewUin;
}

@property(nonatomic) BOOL isRoomConnected; // @synthesize isRoomConnected=_isRoomConnected;
@property(nonatomic) BOOL isFriendIn; // @synthesize isFriendIn=_isFriendIn;
@property(nonatomic) BOOL isSelfIn; // @synthesize isSelfIn=_isSelfIn;
@property(nonatomic) int requestViewType; // @synthesize requestViewType=_requestViewType;
@property(nonatomic) unsigned long long requestViewUin; // @synthesize requestViewUin=_requestViewUin;
@property(nonatomic) unsigned long long selfUin; // @synthesize selfUin=_selfUin;
@property(nonatomic) int groupChatType; // @synthesize groupChatType=_groupChatType;
@property(nonatomic) long long groupUin; // @synthesize groupUin=_groupUin;
@property(retain, nonatomic) NSMutableArray *memUinArray; // @synthesize memUinArray=_memUinArray;
@property(nonatomic) id <GAChatStateChangeProtocal> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (int)getMainVideoCount;
- (long long)indexForUin:(unsigned long long)arg1;
- (id)memberForUin:(unsigned long long)arg1;
- (void)replaceObjectAtIndexByProxy:(unsigned long long)arg1 withObject:(id)arg2;
- (void)removeObjectAtIndexByProxy:(unsigned long long)arg1;
- (void)removeLastObjectByProxy;
- (void)insertObjectByProxy:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addObjectByProxy:(id)arg1;
- (int)findMemberIndex:(unsigned long long)arg1;
- (BOOL)findSpeakCache:(unsigned long long)arg1;
- (int)getVideoCountWithScreenShare:(BOOL)arg1;
- (void)updateAllMember;
- (void)memberPosChange:(id)arg1;
- (void)memberAudioOut:(id)arg1;
- (void)memberAudioIn:(id)arg1;
- (void)memberScreenOut:(id)arg1;
- (void)memberScreenIn:(id)arg1;
- (void)memberPPTOut:(id)arg1;
- (void)memberPPTIn:(id)arg1;
- (void)memberVideoOut:(id)arg1;
- (void)memberVideoIn:(id)arg1;
- (void)memberStopSpeaking:(id)arg1;
- (void)memberStartSpeaking:(id)arg1;
- (void)memberGetOut:(id)arg1;
- (void)memberGetIn:(id)arg1;
- (void)roomConnected;
- (void)onGroupAudioChatNotification:(id)arg1;
- (void)setTerminalType:(int)arg1 atIndex:(int)arg2;
- (void)setMicOffBySelf:(BOOL)arg1 withIndex:(int)arg2;
- (BOOL)getMicOffStateAtIndex:(int)arg1;
- (void)setMicOffState:(BOOL)arg1 withIndex:(int)arg2;
- (BOOL)getShareStateAtIndex:(int)arg1;
- (void)setShareState:(int)arg1 withIndex:(int)arg2;
- (BOOL)getAVStateAtIndex:(int)arg1;
- (void)setAVState:(int)arg1 withIndex:(int)arg2;
- (BOOL)getSpeakStateAtIndex:(int)arg1;
- (void)setSpeakState:(BOOL)arg1 withIndex:(int)arg2;
- (void)dealloc;
- (void)unInitNotification;
- (void)initNotification;
- (char *)getVideoBuffer;
- (void)setVideoBuffer:(char *)arg1;
- (id)initWithGroupUin:(long long)arg1;

@end

