//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet;

@interface HFEngine : NSObject
{
    NSMutableSet *_loadedBundles;
    NSMutableDictionary *_bundleRelpacedClasses;
    NSMutableDictionary *_classAddedSelectors;
    NSMutableDictionary *_classReplacedSelectors;
}

+ (void)logAndReportFailed:(id)arg1 subEvent:(long long)arg2;
+ (void)unloadLogAndReport:(id)arg1;
+ (id)bundleURL;
+ (id)defaultEncryptBundlePath;
+ (id)bundlesFolderPath:(BOOL)arg1;
+ (id)tempPathFrom:(id)arg1 extension:(id)arg2;
+ (id)sharedEngine;
@property(retain) NSMutableDictionary *classReplacedSelectors; // @synthesize classReplacedSelectors=_classReplacedSelectors;
@property(retain) NSMutableDictionary *classAddedSelectors; // @synthesize classAddedSelectors=_classAddedSelectors;
@property(retain) NSMutableDictionary *bundleRelpacedClasses; // @synthesize bundleRelpacedClasses=_bundleRelpacedClasses;
@property(retain) NSMutableSet *loadedBundles; // @synthesize loadedBundles=_loadedBundles;
- (void).cxx_destruct;
- (BOOL)restoreSelector:(id)arg1 inClass:(id)arg2;
- (BOOL)restoreClass:(id)arg1;
- (BOOL)restoreAllClasses;
- (BOOL)unloadBundleWithPath:(id)arg1;
- (BOOL)unloadAllBundles;
- (id)jsContext;
- (id)jsInitAndLoad:(id)arg1;
- (id)jsInitAndLoadByCallOC:(id)arg1;
- (id)nativeInitAndLoadInJS:(id)arg1;
- (id)nativeInitAndLoad:(id)arg1;
- (BOOL)loadBundleWithPath:(id)arg1;
- (void)onSelectorChanged:(id)arg1;
- (void)onBundleLoaded:(id)arg1;
- (id)unzipBundle:(id)arg1;
- (id)decryptBundle:(id)arg1;
- (BOOL)unloadBundleWithIdentifier:(id)arg1;
- (BOOL)loadBundleWithIdentifier:(id)arg1;
- (id)bundlePathWithIdentifier:(id)arg1;
- (void)downloadBundleIfNeeded:(id)arg1 complete:(id)arg2;
- (void)handleLoadConfig:(id)arg1 fromCache:(BOOL)arg2;
- (void)handleUnloadConfig:(id)arg1 fromCache:(BOOL)arg2;
- (void)onManageConfigLoaded:(id)arg1 fromCache:(BOOL)arg2;

@end

