//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSExport.h"

@class NSString, NSURL;

@protocol HFJSExport <JSExport>
+ (id)bundleWithURL:(NSURL *)arg1;
+ (id)bundleWithPath:(NSString *)arg1;
- (BOOL)load;
- (BOOL)isValidForCurrentQQAppId;
- (BOOL)isSignatureValid;
@end

