//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, NSData, NSDictionary, NSMutableParagraphStyle, NSString, NSTextStorage, NSView;

@protocol HistoryHelperDelegate <NSObject>

@optional
- (NSString *)getFaceText:(int)arg1;
- (void)gotoCreateMessageModel:(NSDictionary *)arg1;
- (void)didLoadDatabaseBuffer:(NSData *)arg1;
- (void)OnSearchResultUin:(unsigned long long)arg1 type:(int)arg2 target:(int)arg3 matchNick:(BOOL)arg4 time:(unsigned long long)arg5 rand:(unsigned long long)arg6;
- (void)UpdateProgressBar:(unsigned long long)arg1 totalNum:(unsigned long long)arg2;
- (void)OnAllSearchMsgEnd;
- (NSAttributedString *)getFileAttributedStringWithFileData:(NSDictionary *)arg1;
- (NSMutableParagraphStyle *)MsgParagraphStyleWithAudioView:(id)arg1 bIsSelf:(BOOL)arg2 superView:(NSView *)arg3;
- (id)createAudioView:(unsigned long long)arg1 andAudioPath:(NSString *)arg2 andTimeLength:(int)arg3 isSelf:(_Bool)arg4 withGUID:(NSString *)arg5;
- (NSAttributedString *)AddPicture:(NSString *)arg1 AbsolutePath:(NSString *)arg2 withGUID:(NSString *)arg3;
- (NSAttributedString *)AddPicture:(NSString *)arg1;
- (NSAttributedString *)AddSysFace:(unsigned char)arg1;
- (NSAttributedString *)OutputMsgDate:(NSString *)arg1;
- (NSTextStorage *)getTopViewTextStorage;
- (NSAttributedString *)OutPutLine;
- (id)createTXTextAttachmentCell;
@end

