//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

@class HotFixConfigInfo;

@interface HotFixConfig : QQBaseSingleton
{
    HotFixConfigInfo *_configInfo;
}

- (void).cxx_destruct;
- (id)getConfigInfo;
- (void)deleteOldConfig;
- (void)handleConfig:(id)arg1 version:(int)arg2;
- (void)handleConfigNoChange;
- (void)loadConfigFromCache;
- (void)onSSOResponse:(id)arg1 response:(id)arg2 error:(id)arg3 localVersion:(int)arg4;
- (void)checkHotFixConfig;

@end

