//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ImageUtil : NSObject
{
}

+ (id)_getImageTempDir;
+ (id)saveImageToTempDir:(id)arg1;
+ (id)getGifFirstFrame:(id)arg1;
+ (id)imageTileNamed:(id)arg1 size:(struct CGSize)arg2 radius:(double)arg3;

@end

