//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "NSAnimationDelegate.h"

@class NSButton, NSString, NSTrackingArea, TXHoverImageView;

@interface ImageAndButtonView : NSView <NSAnimationDelegate>
{
    NSButton *deleteButton;
    NSButton *imageButton;
    TXHoverImageView *maskView;
    NSString *account;
    int iUserIndex;
    NSTrackingArea *trackingArea;
    id <ImageAndButtonViewDelegate> delegate;
    BOOL isAnimating;
}

@property(readonly) BOOL isAnimating; // @synthesize isAnimating;
@property int iUserIndex; // @synthesize iUserIndex;
@property id <ImageAndButtonViewDelegate> delegate; // @synthesize delegate;
@property(retain) NSString *account; // @synthesize account;
- (void).cxx_destruct;
- (void)setIsAnimating:(BOOL)arg1;
- (void)mouseDown:(id)arg1;
- (void)refresh;
- (void)animationDidEnd:(id)arg1;
- (void)selectBtnClick:(id)arg1;
- (void)deleteSelfClick:(id)arg1;
- (void)moveViewAnimation:(id)arg1 atStartFrame:(struct CGRect)arg2 toEndFrame:(struct CGRect)arg3 withDuration:(double)arg4;
- (void)setIndex:(unsigned long long)arg1 newPosition:(struct CGRect)arg2 animate:(BOOL)arg3;
- (void)dealloc;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)setBackgroundImage:(id)arg1 Account:(id)arg2 Index:(int)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

