//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol ISynInfoService <NSObject>
- (void)removeDelegateForIncrUpdateType:(int)arg1;
- (void)setDelegate:(id <IIncrUpdateDelegate>)arg1 IncrUpdateType:(int)arg2;
- (void)saveTimestamps:(int)arg1 from:(BOOL)arg2;
- (void)respPushUpdate:(const void *)arg1 DataLen:(int)arg2 subMsgType:(unsigned int)arg3;
- (void)requestIncreasedUpdate;
@end

