//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface MAVEventModel : NSObject
{
    int _eventId;
    int _relationType;
    int _AVType;
    int _AVSubType;
    unsigned long long _relationID;
    unsigned long long _param;
    NSData *_dataBuf;
    const char *_pAVDataBuf;
}

@property(nonatomic) const char *pAVDataBuf; // @synthesize pAVDataBuf=_pAVDataBuf;
@property(retain, nonatomic) NSData *dataBuf; // @synthesize dataBuf=_dataBuf;
@property(nonatomic) unsigned long long param; // @synthesize param=_param;
@property(nonatomic) int AVSubType; // @synthesize AVSubType=_AVSubType;
@property(nonatomic) int AVType; // @synthesize AVType=_AVType;
@property(nonatomic) unsigned long long relationID; // @synthesize relationID=_relationID;
@property(nonatomic) int relationType; // @synthesize relationType=_relationType;
@property(nonatomic) int eventId; // @synthesize eventId=_eventId;
- (void).cxx_destruct;
- (struct AudioFrame *)audioFrameData;
- (struct _stNewVideoStruct *)videoDecFrameData;
- (id)memInOutEventInfo;
- (id)speakingEventInfo;
- (struct tagMAVAInviteInfo *)inventEventInfo;

@end

