//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MCDetailViewForBase.h"

@class NSTextField;

@interface MCDetailViewForVideo : MCDetailViewForBase
{
    NSTextField *_lbContent;
}

@property __weak NSTextField *lbContent; // @synthesize lbContent=_lbContent;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

