//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MCCellViewDelegate.h"
#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"

@class MCTableCellModel, NSMutableArray, NSString, NSTableView, TChatMenuController;

@interface MCTablePresenter : NSObject <NSTableViewDelegate, NSTableViewDataSource, MCCellViewDelegate>
{
    BOOL _isCmdDown;
    NSMutableArray *_dataSource;
    id <MCTablePresenterDelegate> _delegate;
    NSTableView *_tableView;
    NSMutableArray *_mutipleSelectedItem;
    MCTableCellModel *_rightClickSelectedModel;
    MCTableCellModel *_leftClickSelectedModel;
    TChatMenuController *_rightClickMenu;
}

@property(retain) TChatMenuController *rightClickMenu; // @synthesize rightClickMenu=_rightClickMenu;
@property(retain) MCTableCellModel *leftClickSelectedModel; // @synthesize leftClickSelectedModel=_leftClickSelectedModel;
@property(retain) MCTableCellModel *rightClickSelectedModel; // @synthesize rightClickSelectedModel=_rightClickSelectedModel;
@property(retain) NSMutableArray *mutipleSelectedItem; // @synthesize mutipleSelectedItem=_mutipleSelectedItem;
@property __weak NSTableView *tableView; // @synthesize tableView=_tableView;
@property __weak id <MCTablePresenterDelegate> delegate; // @synthesize delegate=_delegate;
@property BOOL isCmdDown; // @synthesize isCmdDown=_isCmdDown;
@property __weak NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)_createRightClickMenu:(struct CGPoint)arg1 andView:(id)arg2;
- (id)tableView:(id)arg1 rowViewForRow:(long long)arg2;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)cellViewMouseDown:(id)arg1 event:(id)arg2;
- (void)cellViewRightClick:(id)arg1 event:(id)arg2;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)reloadData;
- (void)clear;
- (void)configTableView:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

