//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MQAddTipArgs : NSObject
{
    BOOL _isNeedBackground;
    int _style;
    NSString *_string;
    double _time;
}

@property(nonatomic) BOOL isNeedBackground; // @synthesize isNeedBackground=_isNeedBackground;
@property(nonatomic) int style; // @synthesize style=_style;
@property(nonatomic) double time; // @synthesize time=_time;
@property(retain, nonatomic) NSString *string; // @synthesize string=_string;
- (void).cxx_destruct;

@end

