//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQAIOToolsControllerV5.h"

#import "MQEventForwardViewDelegate.h"
#import "MQFaceButtonDelegate.h"
#import "MQSwitchButtonDelegate.h"
#import "NSMenuDelegate.h"

@class MQFaceButton, MQMenuButton, MQSwitchButton, NSString, TXHoverButton;

@interface MQAIOChatTootKitViewController : MQAIOToolsControllerV5 <NSMenuDelegate, MQEventForwardViewDelegate, MQFaceButtonDelegate, MQSwitchButtonDelegate>
{
    int _currentMode;
    MQFaceButton *_faceBtn;
    MQMenuButton *_grabBtn;
    TXHoverButton *_shakeBtn;
    TXHoverButton *_pictureBtn;
    TXHoverButton *_historyBtn;
    MQMenuButton *_disruptBtn;
    MQMenuButton *_switchBtn;
    MQMenuButton *_fileBtn;
    TXHoverButton *_pttBtn;
    MQMenuButton *_avBtn;
}

- (void).cxx_destruct;
- (void)setGroupMessageReceiveTypeNoAlert;
- (void)showBatchGroupSettingWindow;
- (void)setGroupMessageReceiveTypeBlockAll;
- (void)setGroupMessageReceiveTypeNoTip;
- (void)setGroupMessageReceiveTypeNormal;
- (void)onClickSwitchButton:(id)arg1;
- (void)onChangeStateButton:(id)arg1 state:(int)arg2;
- (void)hoverShowFaceBtn;
- (void)onFaceButtonClick;
- (void)insertEmojiFacesAtIndex:(int)arg1;
- (void)insertCustomFace:(id)arg1;
- (void)insertSyetemFacesAtIndex:(int)arg1;
- (void)selectStoreFace:(id)arg1;
- (void)didMouseDown:(id)arg1;
- (unsigned long long)currentBlockStateMentItemIndex;
- (void)showVoiceInputMovedTips:(id)arg1;
- (void)handleBlockStatusDidChange:(int)arg1 notification:(id)arg2;
- (void)handleDiscussEventNotification:(id)arg1;
- (void)handleGroupEventNotification:(id)arg1;
- (void)handleIMInfoEventNotification:(id)arg1;
- (void)onBlock:(id)arg1;
- (void)onOCRScreenCapture:(id)arg1;
- (void)onVideoScreen:(id)arg1;
- (void)onGrabScreen:(id)arg1;
- (void)onPicture:(id)arg1;
- (void)onShakeWindow:(id)arg1;
- (void)onMsgRecord:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)showOATemplateTipsAndReport;
- (void)setSessionId:(id)arg1;
- (int)modeOfSession:(id)arg1;
- (void)setIsVoiceInputting:(BOOL)arg1;
- (void)setToolKitEnabled:(BOOL)arg1;
- (struct CGPoint)faceButtonPosition;
- (void)dealloc;
- (id)init;
- (void)reportOAToolbarEvent:(BOOL)arg1;
- (id)parseMenuItems:(id)arg1 isSubMenuItem:(BOOL)arg2;
- (id)oaMenuBtnItems;
- (id)disruptMenuBtnItems;
- (id)avMenuBtnItems;
- (id)grabMenuBtnItems;
- (id)fileMenuBtnItems:(BOOL)arg1;
- (void)setDisruptState:(id)arg1 tag:(long long)arg2;
- (void)updateDisruptState:(id)arg1;
- (id)oaSubMenuBtnItems:(id)arg1;
- (void)onMenuItemMouseEnter:(id)arg1;
- (void)onMenuMouseEnter:(id)arg1;
- (id)currentBlockStateDescription;
- (BOOL)isCurrentSessionInNoAlertState;
- (BOOL)isCurrentSessionInBlockState;
- (void)updateBlockButton;
- (void)setupUI:(int)arg1;
- (id)topAlignView:(id)arg1 andView:(id)arg2;
- (void)onClickOAButton:(id)arg1;
@property(readonly) MQSwitchButton *switchBtn;
@property(readonly) TXHoverButton *disruptBtn;
@property(readonly) TXHoverButton *historyBtn;
- (void)onClickedAvBtn;
@property(readonly) MQMenuButton *avBtn;
@property(readonly) MQMenuButton *fileBtn;
@property(readonly) TXHoverButton *pictureBtn;
@property(readonly) TXHoverButton *shakeBtn;
- (id)menuItemOfName:(id)arg1 size:(struct CGSize)arg2;
- (void)onScreenCapture;
@property(readonly) MQMenuButton *grabBtn;
@property(readonly) MQFaceButton *faceBtn;
- (void)setConstraintsForButton:(id)arg1;
- (id)buttonOfClass:(Class)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property __weak id <MQAIOChatTootKitViewControllerDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) TXHoverButton *pttBtn;
@property(readonly) Class superclass;

@end

