//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FullSizeContentWindow.h"

@class NSButton;

@interface MQAIOWindow2 : FullSizeContentWindow
{
    BOOL shouldHideTitle_;
    BOOL hasTabStrip_;
    NSButton *closeButton_;
    NSButton *miniaturizeButton_;
    NSButton *zoomButton_;
    BOOL styleMaskLock_;
    double windowButtonsInterButtonSpacing_;
    id <MQAIOWindowDelegate> _aioDelegate;
    unsigned long long _mode;
    double _titleHeight;
}

@property double titleHeight; // @synthesize titleHeight=_titleHeight;
@property __weak id <MQAIOWindowDelegate> aioDelegate; // @synthesize aioDelegate=_aioDelegate;
- (void).cxx_destruct;
- (void)sendEvent:(id)arg1;
- (void)keyDown:(id)arg1;
- (BOOL)performKeyEquivalent:(id)arg1;
- (void)adjustButton:(id)arg1 ofKind:(unsigned long long)arg2;
- (void)adjustZoomButton:(id)arg1;
- (void)adjustMiniaturizeButton:(id)arg1;
- (void)adjustCloseButton:(id)arg1;
- (void)dealloc;
- (void)adjustButtons;
@property unsigned long long mode; // @synthesize mode=_mode;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4 screen:(id)arg5;
- (void)awakeFromNib;

@end

