//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BHSystemMsg_Friend, BHSystemMsg_Group;

@interface MQAIOValidateCellObjectValue : NSObject
{
    BHSystemMsg_Friend *_friendSystemMsg;
    BHSystemMsg_Group *_groupSystemMsg;
    BOOL _needsHighlight;
    BOOL _inTreating;
    double _menuButtonTopEdge;
}

@property(retain) BHSystemMsg_Group *groupSystemMsg; // @synthesize groupSystemMsg=_groupSystemMsg;
@property(retain) BHSystemMsg_Friend *friendSystemMsg; // @synthesize friendSystemMsg=_friendSystemMsg;
@property double menuButtonTopEdge; // @synthesize menuButtonTopEdge=_menuButtonTopEdge;
@property BOOL inTreating; // @synthesize inTreating=_inTreating;
@property BOOL needsHighlight; // @synthesize needsHighlight=_needsHighlight;
- (void).cxx_destruct;

@end

