//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class NSTextField;

@interface MQAIOTitleCellView : NSTableCellView
{
    NSTextField *_titleLabel;
}

@property NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)awakeFromNib;

@end

