//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQAIOToolBox.h"

@class MQAIOSendFilesButton, MQAIOToolButton, TXHoverButton;

@interface MQAIOTempToolBox : MQAIOToolBox
{
    TXHoverButton *_btnAddContact;
    TXHoverButton *_btnShieldContact;
    MQAIOToolButton *_btnAudio;
    MQAIOToolButton *_btnVideo;
    MQAIOSendFilesButton *_btnSendFiles;
}

@property(nonatomic) MQAIOSendFilesButton *btnSendFiles; // @synthesize btnSendFiles=_btnSendFiles;
@property(nonatomic) MQAIOToolButton *btnVideo; // @synthesize btnVideo=_btnVideo;
@property(nonatomic) MQAIOToolButton *btnAudio; // @synthesize btnAudio=_btnAudio;
@property(nonatomic) TXHoverButton *btnShieldContact; // @synthesize btnShieldContact=_btnShieldContact;
@property(nonatomic) TXHoverButton *btnAddContact; // @synthesize btnAddContact=_btnAddContact;
- (void)awakeFromNib;

@end

