//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextField.h"

@interface MQAutoSizeTextField : NSTextField
{
    double _minFontSize;
    double _maxFontSize;
    double _maxBoundsWidth;
    double _maxBoundsHeight;
}

@property double maxBoundsHeight; // @synthesize maxBoundsHeight=_maxBoundsHeight;
@property double maxBoundsWidth; // @synthesize maxBoundsWidth=_maxBoundsWidth;
@property double maxFontSize; // @synthesize maxFontSize=_maxFontSize;
@property double minFontSize; // @synthesize minFontSize=_minFontSize;
- (void)setStringValue:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

