//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQBaseMarkInfo.h"

#import "NSCopying.h"

@class NSArray;

@interface MQBezierPathMarkInfo : MQBaseMarkInfo <NSCopying>
{
    NSArray *_movePoints;
}

@property(retain, nonatomic) NSArray *movePoints; // @synthesize movePoints=_movePoints;
- (void)transferToNewBackgroundSize:(struct CGSize)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

