//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BHFriendGroupModel, NSArray, NSString;

@interface MQContacts : NSObject
{
    NSString *_rootName;
    long long _rootIndex;
    unsigned long long _contactType;
    NSArray *_children;
    BHFriendGroupModel *_friendGroupModel;
}

+ (BOOL)isSelectedPhone:(id)arg1;
+ (BOOL)isSelectedPad:(id)arg1;
+ (BOOL)isItemExpandable:(id)arg1;
+ (BOOL)isSelectedDevice:(id)arg1;
+ (id)itemOfSessionId:(id)arg1;
+ (id)imageOfItem:(id)arg1;
+ (id)nameOfItem:(id)arg1;
+ (id)debugSessionName:(id)arg1;
+ (id)uinOfItem:(id)arg1;
+ (id)sortFriends:(id)arg1;
+ (id)getDeviceList;
+ (id)getDiscussList;
+ (id)getGroupList;
+ (id)getRecentListOnlyFriend;
+ (id)getRecentList;
+ (id)getFriendFolder;
+ (id)getTempUinsArray;
+ (id)filterSessionOnlyFriend;
+ (id)filterSessionWithSingleChatArr;
+ (id)filterSessionArr;
+ (id)itemOfUin:(id)arg1 contactType:(unsigned long long)arg2;
@property(retain, nonatomic) BHFriendGroupModel *friendGroupModel; // @synthesize friendGroupModel=_friendGroupModel;
@property(retain, nonatomic) NSArray *children; // @synthesize children=_children;
@property(nonatomic) unsigned long long contactType; // @synthesize contactType=_contactType;
@property(nonatomic) long long rootIndex; // @synthesize rootIndex=_rootIndex;
@property(copy, nonatomic) NSString *rootName; // @synthesize rootName=_rootName;
- (void).cxx_destruct;
- (void)clearContactItems;
- (void)setupRootArray;
- (id)initContactsWithOrdered:(id)arg1;
- (id)initWithContacts:(id)arg1;
- (id)searchContacts:(id)arg1;
- (id)init;

@end

