//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MQDeviceUtility : NSObject
{
}

+ (long long)APPID;
+ (id)APPBuildVersion;
+ (id)APPShortVersion;
+ (id)getIPAddress2;
+ (id)getIPAddress;
+ (unsigned int)getIPAddressUint32;
+ (id)MacAddress;
+ (id)OSVersion;
+ (id)OSBuildVersion;
+ (id)CPUInfo;
+ (id)model;
+ (id)getCTL:(char *)arg1;
+ (id)hardwareUUID;
+ (id)serialNumber;

@end

