//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@interface MQEventBaseWindowController : NSWindowController
{
}

- (void)windowKeyUp:(id)arg1;
- (void)windowKeyDown:(id)arg1;
- (void)windowLeftMouseDown:(id)arg1;
- (void)modalInWindow:(id)arg1 delegate:(id)arg2 didEndSelector:(SEL)arg3;
- (void)windowDidLoad;

@end

