//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MQFaceUnitProtocol.h"
#import "NSCoding.h"

@class MQStoreEmoji, NSImage, NSString;

@interface MQFaceUnit : NSObject <NSCoding, MQFaceUnitProtocol>
{
    int index_;
    NSString *fileNameB_;
    NSString *fileFixNameB_;
    NSString *fileName_;
    NSString *fileFixName_;
    NSString *faceId_;
    NSImage *faceImage_;
    NSImage *preFaceImage_;
    unsigned long long dwGroupId_;
    int count_;
    NSString *_md5;
    int _faceType;
    MQStoreEmoji *_storeEmoji;
    NSString *_faceIdentifier;
}

+ (id)bigFaceFromStoreEmoji:(id)arg1;
+ (id)emojiConvertFromBigFace:(id)arg1;
+ (id)emojiStringConvertByIndex:(int)arg1;
+ (int)systemFacesIndexConvertToIndex:(unsigned long long)arg1;
+ (long long)emojiFaceTotalCount;
+ (long long)systemFaceTotalCount;
+ (id)emojiFaceUnitWithIndex:(int)arg1;
+ (id)systemFaceUnitWithIndex:(int)arg1;
+ (id)storeFaceUnitWithStoreEmoji:(id)arg1;
+ (id)customFaceUnitWithFileName:(id)arg1 fixFileNameB:(id)arg2 withGroupId:(unsigned long long)arg3 withFaceId:(id)arg4;
+ (id)unitWithFaceIdentifier:(id)arg1;
@property(copy) NSString *faceIdentifier; // @synthesize faceIdentifier=_faceIdentifier;
@property(retain) NSString *md5; // @synthesize md5=_md5;
@property(retain) MQStoreEmoji *storeEmoji; // @synthesize storeEmoji=_storeEmoji;
@property int faceType; // @synthesize faceType=_faceType;
@property int count; // @synthesize count=count_;
@property unsigned long long dwGroupId; // @synthesize dwGroupId=dwGroupId_;
@property(retain) NSImage *preFaceImage; // @synthesize preFaceImage=preFaceImage_;
@property(retain) NSImage *faceImage; // @synthesize faceImage=faceImage_;
@property(retain) NSString *faceId; // @synthesize faceId=faceId_;
@property(retain) NSString *fileFixNameB; // @synthesize fileFixNameB=fileFixNameB_;
@property(retain) NSString *fileNameB; // @synthesize fileNameB=fileNameB_;
@property(retain) NSString *fileFixName; // @synthesize fileFixName=fileFixName_;
@property(retain) NSString *fileName; // @synthesize fileName=fileName_;
@property int index; // @synthesize index=index_;
- (void).cxx_destruct;
- (id)previewImagePath;
- (id)imagePath;
- (BOOL)hasPreviewImageFile;
- (BOOL)hasImageFile;
- (unsigned int)marketTabId;
- (id)marketFaceId;
- (BOOL)sizeOverLimit1M;
- (BOOL)sizeOverLimit;
- (BOOL)isAvailable;
- (id)getPreFaceImage;
- (id)getFaceImage;
- (void)transCustomToPureFile;
- (void)repairFixBmp;
- (BOOL)isEquareToUnit:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (BOOL)isMarket;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;

@end

