//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSButton, NSImageView, NSTextField;

@interface MQFileMessageView : NSView
{
    NSImageView *_fileIcon;
    NSButton *_operationBtn;
    NSView *_btnBgView;
    NSTextField *_titleTextField;
    NSTextField *_subtitleTextField;
    NSImageView *_blurImageView;
}

+ (id)instanceFromNib;
@property(nonatomic) __weak NSImageView *blurImageView; // @synthesize blurImageView=_blurImageView;
@property(nonatomic) __weak NSTextField *subtitleTextField; // @synthesize subtitleTextField=_subtitleTextField;
@property(nonatomic) __weak NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
@property(nonatomic) __weak NSView *btnBgView; // @synthesize btnBgView=_btnBgView;
@property(nonatomic) __weak NSButton *operationBtn; // @synthesize operationBtn=_operationBtn;
@property(nonatomic) __weak NSImageView *fileIcon; // @synthesize fileIcon=_fileIcon;
- (void).cxx_destruct;
- (id)toImage2;
- (id)toImage1;
- (id)toImage;
- (void)insertVibrancyViewBlendingMode:(long long)arg1;
- (void)awakeFromNib;
- (void)drawRect:(struct CGRect)arg1;

@end

