//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class NSTextField;

@interface MQFolderCellView : NSTableCellView
{
    id _item;
    NSTextField *_folderTextField;
    id <MQFolderCellViewDelegate> _delegate;
}

@property __weak id <MQFolderCellViewDelegate> delegate; // @synthesize delegate=_delegate;
@property NSTextField *folderTextField; // @synthesize folderTextField=_folderTextField;
- (void).cxx_destruct;
- (void)mouseDown:(id)arg1;
- (void)setupFolderItem:(id)arg1;
- (void)awakeFromNib;

@end

