//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMenuItem.h"

@class NSImage;

@interface MQHoverMenuItem : NSMenuItem
{
    long long _trackingTag;
    NSImage *_alternateImage;
}

@property(retain) NSImage *alternateImage; // @synthesize alternateImage=_alternateImage;
- (void).cxx_destruct;

@end

