//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextAttachmentCell.h"

@class MQHrCandicateInfo, MQNinePartImage, NSLayoutManager, NSTextView, NSView;

@interface MQHrAssistantAttachmentCell : NSTextAttachmentCell
{
    unsigned long long _charIndex;
    NSLayoutManager *_layoutManager;
    struct CGRect _cellFrame;
    struct CGSize _fileNameSize;
    NSView *_controlView;
    BOOL _isSelf;
    NSTextView *_textView;
    SEL _doubleClickOperation;
    MQNinePartImage *_bubbleImage;
    MQNinePartImage *_selectedBubbleImage;
    MQNinePartImage *_maskBubbleImage;
    MQNinePartImage *_textBgImage;
    MQHrCandicateInfo *_candicateInfo;
    struct NSEdgeInsets _contentPaddingEdgeInsets;
}

@property(retain, nonatomic) MQHrCandicateInfo *candicateInfo; // @synthesize candicateInfo=_candicateInfo;
@property(retain, nonatomic) MQNinePartImage *textBgImage; // @synthesize textBgImage=_textBgImage;
@property(retain, nonatomic) MQNinePartImage *maskBubbleImage; // @synthesize maskBubbleImage=_maskBubbleImage;
@property(retain, nonatomic) MQNinePartImage *selectedBubbleImage; // @synthesize selectedBubbleImage=_selectedBubbleImage;
@property(retain, nonatomic) MQNinePartImage *bubbleImage; // @synthesize bubbleImage=_bubbleImage;
@property(nonatomic) BOOL isSelf; // @synthesize isSelf=_isSelf;
@property(nonatomic) SEL doubleClickOperation; // @synthesize doubleClickOperation=_doubleClickOperation;
@property(nonatomic) struct NSEdgeInsets contentPaddingEdgeInsets; // @synthesize contentPaddingEdgeInsets=_contentPaddingEdgeInsets;
@property(nonatomic) NSTextView *textView; // @synthesize textView=_textView;
- (void).cxx_destruct;
- (void)invalidateDisplay;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 atCharacterIndex:(unsigned long long)arg4 untilMouseUp:(BOOL)arg5;
- (id)subtitleAttributes;
- (id)nameAttributes;
- (id)titleAttributes;
- (void)drawTextElement:(id)arg1 offsetPoint:(struct CGPoint)arg2;
- (void)drawContent:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawBackground:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2 characterIndex:(unsigned long long)arg3 layoutManager:(id)arg4;
- (struct CGSize)cellSize;
- (struct CGSize)bubbleSize;
- (void)prepareUI;
- (id)init;

@end

