//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextAttachment.h"

@class BHMessageModel, MQHrAssistantAttachmentCell;

@interface MQHrAssistantAttachment : NSTextAttachment
{
    MQHrAssistantAttachmentCell *_cell;
    BHMessageModel *_messageModel;
}

- (void).cxx_destruct;
- (void)parseMsgModel;
- (void)doubleClickAction:(id)arg1;
- (void)setTextView:(id)arg1;
- (id)initWithMessageModel:(id)arg1;

@end

