//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableView.h"

@interface MQLocResultTableView : NSTableView
{
    id <MQLocTableViewExtendDelegate> _extendedDelegate;
}

@property(nonatomic) __weak id <MQLocTableViewExtendDelegate> extendedDelegate; // @synthesize extendedDelegate=_extendedDelegate;
- (void).cxx_destruct;
- (void)mouseDown:(id)arg1;

@end

