//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface MQLocation : NSObject <NSCoding>
{
    NSString *_area_code;
    NSString *_en_name;
    NSString *_area_name;
}

+ (id)LocationWithDictionary:(id)arg1;
@property(copy, nonatomic) NSString *area_name; // @synthesize area_name=_area_name;
@property(copy, nonatomic) NSString *en_name; // @synthesize en_name=_en_name;
@property(copy, nonatomic) NSString *area_code; // @synthesize area_code=_area_code;
- (void).cxx_destruct;
- (void)replaceDataWithDictionary:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

