//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperationQueue, NSString;

@interface MQOCRHandleManager : NSObject
{
    NSString *_auth;
    NSOperationQueue *_httpQueue;
}

+ (id)shareInstance;
- (void).cxx_destruct;
- (id)hmacsha1:(id)arg1 secret:(id)arg2;
- (id)makeAuth:(unsigned int)arg1;
- (id)base64Encoded:(id)arg1 compressByFactor:(float)arg2;
- (id)imageToJPEG:(id)arg1 compressByfactor:(float)arg2;
- (id)detectORCodeFromImage:(id)arg1;
- (void)startOCRDetecting:(id)arg1 Priority:(long long)arg2 overTime:(float)arg3;
- (id)createOCRHandleTaskByImage:(id)arg1 handleType:(long long)arg2 successBlock:(id)arg3 failureBlock:(id)arg4;
- (id)init;

@end

