//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSString, NSURLSessionDataTask;

@interface MQOCRHandleTask : NSOperation
{
    BOOL _isExecuting;
    BOOL _isFinished;
    BOOL _isCancelled;
    NSURLSessionDataTask *_task;
    long long _hType;
    NSString *_path;
    id _successBlock;
    id _failedBlock;
}

@property(readonly, copy, nonatomic) id failedBlock; // @synthesize failedBlock=_failedBlock;
@property(readonly, copy, nonatomic) id successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(readonly, nonatomic) long long hType; // @synthesize hType=_hType;
@property(readonly, nonatomic) NSURLSessionDataTask *task; // @synthesize task=_task;
- (void).cxx_destruct;
- (void)changeValueForKeys:(id)arg1 withBlock:(id)arg2;
- (void)finishOperation;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (BOOL)isCancelled;
- (void)cancel;
- (BOOL)isAsynchronous;
- (BOOL)isConcurrent;
- (void)start;
- (id)parseOCRResultItemsWithJSONDict:(id)arg1;
- (id)initHttpTaskWithImage:(id)arg1 handleType:(long long)arg2 authorization:(id)arg3 successBlock:(id)arg4 failureBlock:(id)arg5;
- (id)initOCRSDKTaskWithPath:(id)arg1 handleType:(long long)arg2 successBlock:(id)arg3 failureBlock:(id)arg4;

@end

