//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MQPhoto, MQPhotoOCRListVC, NSString;

@protocol MQPhotoViewControllerDelegate <NSObject>
- (MQPhoto *)photoForIndex:(long long)arg1;
- (long long)numberOfPhotos;
- (void)showPhotoAlbumWithPhoto:(MQPhoto *)arg1;
- (BOOL)canBeCollected;
- (void)collectPhoto;
- (MQPhotoOCRListVC *)OCRListVC;
- (MQPhoto *)currentPhoto;
- (BOOL)albumEnable;
- (void)hideOCRResultPlace:(void (^)(void))arg1;
- (void)showOCRResultPlace:(void (^)(void))arg1;
- (NSString *)title;
@end

