//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MQScreenCaptureApp2.h"
#import "MQSuspensionApp.h"

@class NSString;

@interface MQScreenCaptureDOApp : NSObject <MQScreenCaptureApp2, MQSuspensionApp>
{
    NSString *_loginItemBundleId;
}

@property(copy) NSString *loginItemBundleId; // @synthesize loginItemBundleId=_loginItemBundleId;
- (void).cxx_destruct;
- (void)handlerShowingContactListWithFilePaths:(id)arg1;
- (void)handlerSuspensionShowingFromJietuWithOrigin:(struct CGPoint)arg1 runningApps:(id)arg2;
- (void)handlerSuspensionFrameOrigin:(struct CGPoint)arg1;
- (void)handlerMouseEventFromServer:(unsigned long long)arg1;
- (void)enableLoginItem:(BOOL)arg1;
- (void)buttonReport:(id)arg1;
- (void)didCancelScreenCaptureRequstByMe:(BOOL)arg1;
- (void)didFinishRecordRequestByMe:(BOOL)arg1 withSessionUin:(unsigned long long)arg2 chatType:(unsigned long long)arg3 filePath:(id)arg4;
- (void)didCaptureImageData:(id)arg1 requstByMe:(BOOL)arg2;
- (unsigned long long)appId;
- (void)updateShortcutByFlags:(unsigned int)arg1 keyCode:(int)arg2;
- (BOOL)wantTheCaputreImageStartedByShortcutNow;
- (void)startOCRCaptureFromTabBar;
- (void)startScreenCaptureByShortcut;
- (void)startScreenRecordByShortcut;

@end

