//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQScreenShareMarkRectResizableDelegate.h"

@class MQScreenShareMarkBase, NSEvent;

@protocol MQScreenShareMarkTopEditViewDelegate <MQScreenShareMarkRectResizableDelegate>

@optional
- (void)addNewMarkWithMouseDownEvent:(NSEvent *)arg1;
- (BOOL)canAddMarkItem;
- (void)captureImageToFile:(BOOL)arg1;
- (void)markItemReadyDelete;
- (void)setSelectedMarkItem:(MQScreenShareMarkBase *)arg1;
- (MQScreenShareMarkBase *)selectedMarkItem;
@end

