//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQScreenShareMarkBase.h"

@interface MQScreenShareMarkOval : MQScreenShareMarkBase
{
}

- (void)setReady:(BOOL)arg1;
- (int)type;
- (BOOL)mouseInInterestRegion:(struct CGPoint)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (double)margin;

@end

