//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButtonCell.h"

@class NSProgressIndicator;

@interface MQSearchProgressCell : NSButtonCell
{
    NSProgressIndicator *searchProgressIndicator;
    struct CGRect searchCellFrame;
    BOOL inProgress;
}

@property struct CGRect searchCellFrame; // @synthesize searchCellFrame;
@property BOOL inProgress; // @synthesize inProgress;
- (void).cxx_destruct;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

