//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface MQSessionID : NSObject <NSCopying>
{
    int _sessionChatType;
    unsigned long long _uin;
    BOOL _addBySingleChat;
}

+ (id)tencentNewsSessionID;
+ (id)groupAssistantSessionID;
+ (id)sessionIdWithChatType:(int)arg1 andUin:(unsigned long long)arg2;
@property(nonatomic) BOOL addBySingleChat; // @synthesize addBySingleChat=_addBySingleChat;
@property(readonly, nonatomic) unsigned long long uin; // @synthesize uin=_uin;
@property(readonly, nonatomic) int chatType; // @synthesize chatType=_sessionChatType;
- (id)chatTypeString;
- (BOOL)isChatSession;
- (id)debugDescription;
- (id)description;
@property(readonly, nonatomic) int realTimeChatType;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (int)QQMessageType;
- (id)sessionIdentity;
- (id)uinTypeString;
- (id)uinString;
- (unsigned long long)hash;
- (BOOL)isEqualToChatType:(int)arg1 andUin:(unsigned long long)arg2;
- (BOOL)isEqual:(id)arg1;
- (id)initWithChatType:(int)arg1 andUin:(unsigned long long)arg2;

@end

