//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MQSourceList, NSArray, NSColor, NSImage, NSPasteboard, NSURL;

@protocol MQSourceListDataSource <NSObject>
- (BOOL)sourceList:(MQSourceList *)arg1 isItemExpandable:(id)arg2;
- (id)sourceList:(MQSourceList *)arg1 objectValueForItem:(id)arg2;
- (id)sourceList:(MQSourceList *)arg1 child:(unsigned long long)arg2 ofItem:(id)arg3;
- (unsigned long long)sourceList:(MQSourceList *)arg1 numberOfChildrenOfItem:(id)arg2;

@optional
- (NSArray *)sourceList:(MQSourceList *)arg1 namesOfPromisedFilesDroppedAtDestination:(NSURL *)arg2 forDraggedItems:(NSArray *)arg3;
- (BOOL)sourceList:(MQSourceList *)arg1 acceptDrop:(id <NSDraggingInfo>)arg2 item:(id)arg3 childIndex:(long long)arg4;
- (unsigned long long)sourceList:(MQSourceList *)arg1 validateDrop:(id <NSDraggingInfo>)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;
- (BOOL)sourceList:(MQSourceList *)arg1 writeItems:(NSArray *)arg2 toPasteboard:(NSPasteboard *)arg3;
- (id)sourceList:(MQSourceList *)arg1 persistentObjectForItem:(id)arg2;
- (id)sourceList:(MQSourceList *)arg1 itemForPersistentObject:(id)arg2;
- (NSImage *)sourceList:(MQSourceList *)arg1 iconForItemSelected:(id)arg2;
- (NSImage *)sourceList:(MQSourceList *)arg1 iconForItem:(id)arg2;
- (BOOL)sourceList:(MQSourceList *)arg1 itemHasIcon:(id)arg2;
- (NSColor *)sourceList:(MQSourceList *)arg1 badgeBackgroundColorForItem:(id)arg2;
- (NSColor *)sourceList:(MQSourceList *)arg1 badgeTextColorForItem:(id)arg2;
- (long long)sourceList:(MQSourceList *)arg1 badgeValueForItem:(id)arg2;
- (BOOL)sourceList:(MQSourceList *)arg1 itemHasBadge:(id)arg2;
- (void)sourceList:(MQSourceList *)arg1 setObjectValue:(id)arg2 forItem:(id)arg3;
@end

