//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ConfToolbarBase.h"

@class MQSSToolbarView_Video;

@interface MQSSVideoToolbarController : ConfToolbarBase
{
    MQSSToolbarView_Video *_toolbar;
}

@property(readonly, nonatomic) MQSSToolbarView_Video *toolbar; // @synthesize toolbar=_toolbar;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithIOF:(id)arg1;

@end

