//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MQContactPopover, MQSuspensionWindowController, NSImage, NSMutableArray;

@interface MQSuspensionManager : NSObject
{
    id _eventMonitor;
    NSMutableArray *_appInfos;
    NSMutableArray *_filePaths;
    MQSuspensionWindowController *_suspensionWinCtrl;
    MQContactPopover *_contactPopover;
    MQContactPopover *_tipsPopover;
    NSImage *_headImg;
    BOOL _suspensionIsShow;
    BOOL _popoverIsShow;
    BOOL _itemBarIsHide;
}

+ (id)shareExtension;
@property(readonly) BOOL itemBarIsHide; // @synthesize itemBarIsHide=_itemBarIsHide;
@property(readonly) BOOL popoverIsShow; // @synthesize popoverIsShow=_popoverIsShow;
@property(readonly) BOOL suspensionIsShow; // @synthesize suspensionIsShow=_suspensionIsShow;
- (void).cxx_destruct;
- (void)restore;
- (void)restoreSuspension;
- (void)createTipsPopover;
- (void)makeJietuBecomeActive;
- (void)showTips:(id)arg1;
- (void)showContactPopoverWithFilePaths:(id)arg1;
- (void)requestContactListShowing:(unsigned long long)arg1;
- (void)setFilesFromPasteBoard:(id)arg1;
- (id)getAllAppInfos;
- (void)showSuspension:(struct CGPoint)arg1 WithAppInfos:(id)arg2;
- (void)setSuspensionFrameOrigin:(struct CGPoint)arg1;
- (struct CGRect)statusItemFrame;
- (void)reportItemFrame;
- (void)handleMouseEventFromJT:(unsigned long long)arg1;
- (void)dealloc;
- (void)registerGlobalMouseEvent;
- (void)registerPopover;
- (id)contactPopover;
- (id)init;

@end

