//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQHoverTipsButton.h"

@class NSImage;

@interface MQTextAttachmentCellButton2 : MQHoverTipsButton
{
    NSImage *_buttonIcon;
    id _target;
    SEL _selector;
    int _clickedArea;
    BOOL _isPlaceHolder;
}

+ (id)placeHolderButtonWithFrame:(struct CGRect)arg1;
+ (id)cellButtonWithFrame:(struct CGRect)arg1 buttonIcon:(id)arg2 buttonTag:(int)arg3;
@property SEL selector; // @synthesize selector=_selector;
@property BOOL isPlaceHolder; // @synthesize isPlaceHolder=_isPlaceHolder;
@property int clickedArea; // @synthesize clickedArea=_clickedArea;
@property(retain) NSImage *buttonIcon; // @synthesize buttonIcon=_buttonIcon;
- (void).cxx_destruct;

// Remaining properties
@property struct CGRect frame;
@property __weak id target;

@end

