//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FileBoxModel, NSArray, NSManagedObjectContext, NSManagedObjectModel;

@interface MQTransferedFilesManager : NSObject
{
    FileBoxModel *_fileBoxModel;
    NSManagedObjectContext *managedObjectContext;
    NSManagedObjectModel *managedObjectModel;
    NSArray *_allFiles;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(readonly) NSArray *allFiles;
- (BOOL)reload;
- (BOOL)removeTransferedFiles:(id)arg1;
- (id)recordInfo;
- (id)itemInfoByPath:(id)arg1;
- (BOOL)addTransferedFile:(id)arg1;
- (id)init;

@end

