//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MQTranslateResultViewController, NSArray, NSMutableArray;

@interface MQTranslateManager : NSObject
{
    NSArray *_languageTag;
    NSMutableArray *_timeStack;
    id _monitor;
    MQTranslateResultViewController *_resultViewController;
    NSMutableArray *_strokeSessions;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSMutableArray *strokeSessions; // @synthesize strokeSessions=_strokeSessions;
@property(readonly, nonatomic) MQTranslateResultViewController *resultViewController; // @synthesize resultViewController=_resultViewController;
- (void).cxx_destruct;
- (BOOL)showStrokeTips;
- (void)resetStrokeTipsAppearedTime;
- (id)md5:(id)arg1;
- (id)makeToken:(id)arg1;
- (void)translateAIOMessageWithRequest:(id)arg1 completion:(id)arg2;
- (void)translateStringBatch:(id)arg1 fromLanguage:(long long)arg2 toLanguage:(long long)arg3 Completion:(id)arg4;
- (void)translateString:(id)arg1 fromLanguage:(long long)arg2 toLanguage:(long long)arg3 Completion:(id)arg4;
- (void)translateString:(id)arg1 toLanguage:(long long)arg2 Completion:(id)arg3;
- (void)setupMonitor;
- (id)init;

@end

