//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQUnreadMsgItem.h"

@interface MQUnreadSysMsgItem : MQUnreadMsgItem
{
    unsigned long long _msgCount;
    unsigned long long _msgCountForDisplay;
}

- (BOOL)isOfflineMsg;
- (id)textOfChatMsg;
- (void)destoryMsgList;
- (void)removeMessage:(void *)arg1;
- (int)addMessage:(void *)arg1 MessageTail:(id)arg2;
- (void)loadSysMsgCount;
- (unsigned long long)latestMsgTime;
- (unsigned long long)msgCountForDisplay;
- (unsigned long long)msgCount;
- (id)itemTitle;
- (id)itemIcon;
- (void)dealloc;
- (id)initWithUin:(unsigned long long)arg1 chatType:(int)arg2;

@end

