//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "NSAnimationDelegate.h"

@class ClickThroughTextField, NSBezierPath, NSString, NSTrackingArea;

@interface MQUnreadCountView : NSView <NSAnimationDelegate>
{
    ClickThroughTextField *_countView;
    BOOL _wideMode;
    BOOL _middleModel;
    BOOL _noneCountModel;
    long long _visibleModel;
    NSTrackingArea *_trackingArea;
    NSBezierPath *_path;
    long long _unreadCount;
    BOOL _isNavigateTab;
    BOOL _isMouseDrag;
    BOOL _isSimple;
    id <MQUnreadCountViewDelegate> _delegate;
}

@property(nonatomic) BOOL isSimple; // @synthesize isSimple=_isSimple;
@property(nonatomic) BOOL isMouseDrag; // @synthesize isMouseDrag=_isMouseDrag;
@property(nonatomic) __weak id <MQUnreadCountViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL isNavigateTab; // @synthesize isNavigateTab=_isNavigateTab;
- (void).cxx_destruct;
- (void)mouseDown:(id)arg1;
- (struct CGPoint)convertedStartPoint;
- (void)mouseEntered:(id)arg1;
- (void)shakeAnimete;
- (void)updateTrackingArea;
- (BOOL)acceptsFirstResponder;
- (BOOL)isOpaque;
- (struct CGSize)intrinsicContentSize;
- (void)setUnreadCount:(long long)arg1;
- (void)setUnreadCountViewModel:(long long)arg1;
- (void)setHighlightBackground:(BOOL)arg1;
- (void)awakeFromNib;
- (void)onSimplestModeDidChange:(id)arg1;
- (void)updateBackgroundImage;
- (id)navigationUnreadCountBackgroundImage;
- (id)backgroundImage;
- (void)dealloc;
- (id)countView;
- (void)setFont:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

