//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQUnreadMsgItem.h"

@class NSMutableArray;

@interface MQUnreadMailMsgItem : MQUnreadMsgItem
{
    NSMutableArray *_mailMsgs;
}

@property(retain, nonatomic) NSMutableArray *mailMsgs; // @synthesize mailMsgs=_mailMsgs;
- (void).cxx_destruct;
- (BOOL)isOfflineMsg;
- (id)destURL;
- (BOOL)showFloatHint;
- (void)resetAfterRead;
- (unsigned long long)popMsgItemToTXArray:(id)arg1 currentCount:(unsigned long long)arg2;
- (int)addMessage:(void *)arg1 MessageTail:(id)arg2;
- (id)textOfChatMsg;
- (unsigned long long)latestMsgTime;
- (id)messageArray;
- (unsigned long long)msgCount;
- (id)itemTitle;
- (id)itemIcon;
- (void)dealloc;
- (id)initWithUin:(unsigned long long)arg1 chatType:(int)arg2;

@end

