//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TXHoverButton.h"

@class NSLayoutConstraint;

@interface MQWidgetButton : TXHoverButton
{
    NSLayoutConstraint *_marginLeftConstraint;
    NSLayoutConstraint *_marginRightConstraint;
    NSLayoutConstraint *_marginTopConstraint;
    NSLayoutConstraint *_marginBottomConstraint;
    NSLayoutConstraint *_paddingLeftConstraint;
    NSLayoutConstraint *_paddingRightConstraint;
    NSLayoutConstraint *_paddingTopConstraint;
    NSLayoutConstraint *_paddingBottomConstraint;
    struct NSEdgeInsets _marginEdgeInsets;
    struct NSEdgeInsets _paddingEdgeInsets;
}

@property(nonatomic) struct NSEdgeInsets paddingEdgeInsets; // @synthesize paddingEdgeInsets=_paddingEdgeInsets;
@property(nonatomic) struct NSEdgeInsets marginEdgeInsets; // @synthesize marginEdgeInsets=_marginEdgeInsets;
- (void).cxx_destruct;
- (void)setFrame:(struct CGRect)arg1;
- (void)setContentView:(id)arg1;

@end

