//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MsfIPInfo : NSObject
{
    int port;
    int protocolType;
    NSString *ip;
}

@property(nonatomic) int protocolType; // @synthesize protocolType;
@property(nonatomic) int port; // @synthesize port;
@property(retain, nonatomic) NSString *ip; // @synthesize ip;
- (void)dealloc;

@end

