//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSFNetReachability;

@interface MSFSystemNetworkTypeManager : NSObject
{
    MSFNetReachability *_pReach;
    MSFNetReachability *_pReachForWifi;
    struct IMSFSystemNetworkEvent *_event;
}

@property(nonatomic) struct IMSFSystemNetworkEvent *event; // @synthesize event=_event;
- (void)reachabilityChanged:(id)arg1;
- (int)netStatus;
- (void)dealloc;
- (id)init;

@end

