//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class MQAIOTopViewController, NSArray, NSView, TChatView, TXTopTextView;

@interface MultiMsgWindowController : NSWindowController
{
    NSView *_msgFlowWrapper;
    TXTopTextView *_topTextView;
    TChatView *_chatView;
    NSArray *_msgList;
    MQAIOTopViewController *_topMsgListViewController;
}

@property(retain) MQAIOTopViewController *topMsgListViewController; // @synthesize topMsgListViewController=_topMsgListViewController;
@property(copy, nonatomic) NSArray *msgList; // @synthesize msgList=_msgList;
- (void).cxx_destruct;
- (id)scrollViewWithClass:(Class)arg1 documentFrame:(struct CGRect)arg2;
- (id)createTextViewOfClass:(Class)arg1 frame:(struct CGRect)arg2;
- (id)createChatView;
- (void)buildUI;
- (void)showWindow:(id)arg1;
- (void)close;
- (void)windowDidLoad;

@end

