//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TXColorView.h"

#import "NScheduleDayCellDelegate.h"

@class NSDate, NSMutableArray, NSString, NScheduleDayCell;

@interface NScheduleMonthView : TXColorView <NScheduleDayCellDelegate>
{
    NSMutableArray *cellArray;
    long long rowOfPreMonthFirstDay;
    long long rowOfNextMonthFirstDay;
    long long selectDayInRow;
    long long perSelectDayInRow;
    long long nextSelectDayInRow;
    long long selectDay;
    long long perSelectDay;
    long long nextSelectDay;
    TXColorView *prevMonthSelectWeekBackgroundView;
    TXColorView *currMonthSelectWeekBackgroundView;
    TXColorView *nextMonthSelectWeekBackgroundView;
    BOOL isDoubleClicking;
    NScheduleDayCell *currentClickCell;
    BOOL isLastWindowLargeModel;
    BOOL isFirstSetFrame;
    id _backToWeakViewBlock;
    id _createWithDateBlock;
    id _selectScheduleWithBaseViewAndDate;
    id _deleteSchedule;
    id _cancelSchedule;
    id _modifyScheduleWithDate;
    id _doubleClickDateBlock;
    id _clickDateBlock;
    id _clickMoreScheduleBlock;
    id _scheduleDayCellScrollViewChangePage;
    NSDate *_date;
    NSDate *_prevMonthDate;
    NSDate *_nextMonthDate;
    NSDate *_nextNextMonthDate;
    NSDate *_selectedDate;
}

+ (id)dd:(id)arg1;
@property(retain, nonatomic) NSDate *selectedDate; // @synthesize selectedDate=_selectedDate;
@property(retain, nonatomic) NSDate *nextNextMonthDate; // @synthesize nextNextMonthDate=_nextNextMonthDate;
@property(retain, nonatomic) NSDate *nextMonthDate; // @synthesize nextMonthDate=_nextMonthDate;
@property(retain, nonatomic) NSDate *prevMonthDate; // @synthesize prevMonthDate=_prevMonthDate;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(copy, nonatomic) id scheduleDayCellScrollViewChangePage; // @synthesize scheduleDayCellScrollViewChangePage=_scheduleDayCellScrollViewChangePage;
@property(copy, nonatomic) id clickMoreScheduleBlock; // @synthesize clickMoreScheduleBlock=_clickMoreScheduleBlock;
@property(copy, nonatomic) id clickDateBlock; // @synthesize clickDateBlock=_clickDateBlock;
@property(copy, nonatomic) id doubleClickDateBlock; // @synthesize doubleClickDateBlock=_doubleClickDateBlock;
@property(copy, nonatomic) id modifyScheduleWithDate; // @synthesize modifyScheduleWithDate=_modifyScheduleWithDate;
@property(copy, nonatomic) id cancelSchedule; // @synthesize cancelSchedule=_cancelSchedule;
@property(copy, nonatomic) id deleteSchedule; // @synthesize deleteSchedule=_deleteSchedule;
@property(copy, nonatomic) id selectScheduleWithBaseViewAndDate; // @synthesize selectScheduleWithBaseViewAndDate=_selectScheduleWithBaseViewAndDate;
@property(copy, nonatomic) id createWithDateBlock; // @synthesize createWithDateBlock=_createWithDateBlock;
@property(copy, nonatomic) id backToWeakViewBlock; // @synthesize backToWeakViewBlock=_backToWeakViewBlock;
- (void).cxx_destruct;
- (void)changePage:(int)arg1;
- (void)clickMoreSchedule:(id)arg1 withDate:(id)arg2;
- (void)modifySchedule:(id)arg1 withDate:(id)arg2;
- (void)cancelSchedule:(id)arg1;
- (void)deleteSchedule:(id)arg1;
- (void)selectSchedule:(id)arg1 baseView:(id)arg2 date:(id)arg3;
- (void)onDoubleClickDate:(id)arg1 schedule:(id)arg2;
- (void)onClickDate:(id)arg1 schedule:(id)arg2;
- (long long)getRowOfNextMonthFirstDay;
- (long long)getRowOfPreMonthFirstDay;
- (void)drawRect:(struct CGRect)arg1;
- (void)backToday;
- (void)prevMonth;
- (void)nextMonth;
- (void)stepMonth:(long long)arg1;
- (void)layoutCalendar;
- (void)reloadData;
- (long long)colForDay:(long long)arg1;
- (long long)lastDayOf:(id)arg1;
- (id)monthDay:(long long)arg1 date:(id)arg2;
- (void)delayHandleCellClicked;
- (void)cellClicked:(id)arg1;
- (id)toUTC:(id)arg1;
- (BOOL)isFlipped;
- (void)setFrame:(struct CGRect)arg1;
- (void)delayInitHover;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

