//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class MQRecentMsgTipsRightView, MQRecentMsgTipsView, NSDate, NSImageView, NSLayoutConstraint, NScheduleBaseView, NScheduleWeakBackgroudView, NScheduleWeakScrollView, NScheduleWeakTitleView4Weak, TXHoverButton;

@interface NScheduleWeakViewController : NSViewController
{
    MQRecentMsgTipsView *_recentTipsView;
    MQRecentMsgTipsRightView *_recentTipsViewRight;
    NScheduleWeakTitleView4Weak *_weakTitleView;
    NScheduleWeakScrollView *dayMatrix;
    NScheduleWeakBackgroudView *backgroudView;
    NSLayoutConstraint *_backgroundViewHeightConstraint;
    double offsetRate;
    BOOL isDraging;
    int times;
    NScheduleBaseView *__view;
    NSImageView *_imageView;
    BOOL _isFirstOpenSchedule;
    BOOL _needScrollToDefaultSchedule;
    id _backToMonthBlock;
    id _menuEventBlock;
    NSDate *_date;
    TXHoverButton *_leftButton;
    TXHoverButton *_rightButton;
    TXHoverButton *_backButton;
}

@property __weak TXHoverButton *backButton; // @synthesize backButton=_backButton;
@property __weak TXHoverButton *rightButton; // @synthesize rightButton=_rightButton;
@property __weak TXHoverButton *leftButton; // @synthesize leftButton=_leftButton;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(nonatomic) BOOL needScrollToDefaultSchedule; // @synthesize needScrollToDefaultSchedule=_needScrollToDefaultSchedule;
@property(nonatomic) BOOL isFirstOpenSchedule; // @synthesize isFirstOpenSchedule=_isFirstOpenSchedule;
@property(copy, nonatomic) id menuEventBlock; // @synthesize menuEventBlock=_menuEventBlock;
@property(copy, nonatomic) id backToMonthBlock; // @synthesize backToMonthBlock=_backToMonthBlock;
- (void).cxx_destruct;
- (id)getScheduleViewWithModel:(id)arg1;
- (void)showRecentTipsViewRight:(struct CGPoint)arg1 text:(id)arg2 rightlength:(int)arg3;
- (void)showRecentTipsView:(struct CGPoint)arg1 text:(id)arg2 rightlength:(int)arg3;
- (void)tableViewMouseMove;
- (void)tableViewMouseIn:(struct CGPoint)arg1:(BOOL)arg2:(int)arg3;
- (void)tableViewMouseExit:(struct CGPoint)arg1;
- (void)viewDidLoad;
- (void)buttonClick:(id)arg1;
- (void)scrollToSchedule:(id)arg1;
- (void)reloadData;
- (void)scrollToDefaultSchedule;
- (void)delayCalOffset;
- (void)handleDidScrolled:(id)arg1;
- (void)hiddenScrollBar;
- (void)layoutSubViews:(struct CGRect)arg1;
- (void)viewDidLayout;
- (void)loadView;
- (void)dealloc;

@end

