//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Message)
+ (id)shakeTipsWithMessageModel:(id)arg1;
+ (id)getXMLTitleInQQSMMessage:(id)arg1;
+ (id)stringWithMessageModel:(id)arg1 inGroup:(unsigned long long)arg2;
+ (id)stringWithMessageModel:(id)arg1;
- (id)stringByRemoveNewLineCode;
- (id)stringByDeletingNewlineCode;
@end

