//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "AuthConfigViewControllerDelegate.h"
#import "MQSwitchButtonDelegate.h"

@class AuthConfigViewController, NSButton, NSLayoutConstraint, NSString, NSView;

@interface PreferenceNotificationsViewController : NSViewController <MQSwitchButtonDelegate, AuthConfigViewControllerDelegate>
{
    NSView *authConfigView;
    NSView *_notificationsSettingView;
    NSButton *_checkEnableSystemSound;
    NSButton *_checkShowFutuNotification;
    NSButton *_checkShowMailBadge;
    NSButton *_checkShowFutuBadge;
    NSButton *_checkShowQzoneBadge;
    NSButton *_checkShowMessageDetail;
    NSButton *_checkShowBuddyNotification;
    NSButton *_checkShowBuddyShake;
    NSButton *_checkShowDiscussNotification;
    NSButton *_checkShowGroupNotification;
    NSButton *_checkShowEmailNotification;
    NSButton *_checkShowQZoneNotification;
    NSButton *_checkEnableGroupAssistant;
    NSButton *_checkShowRedpackPush;
    AuthConfigViewController *m_authConfigController;
    NSLayoutConstraint *authconfgHeightConstraint;
}

- (void).cxx_destruct;
- (void)adjustAuthConfigViewHeight:(double)arg1;
- (void)SetNewQuestions:(id)arg1;
- (void)SetNewQuestionAndAnswer:(id)arg1 answer:(id)arg2;
- (void)EnableButtonApplay:(int)arg1;
- (void)handleRedpackPushCDNStateChange:(BOOL)arg1;
- (void)handleRedpackPushCheckState:(id)arg1;
- (void)onChangeShowFutuNotification:(id)arg1;
- (void)onCheckRedpackPush:(id)arg1;
- (void)onChangeShowQZoneNotification:(id)arg1;
- (void)onChangeShowEmailNotification:(id)arg1;
- (void)onCheckShowGroupNotification:(id)arg1;
- (void)onCheckShowDiscussNotification:(id)arg1;
- (void)onCheckShowBuddyShake:(id)arg1;
- (void)onCheckShowBuddyNotification:(id)arg1;
- (void)onCheckEnableGroupAssistant:(id)arg1;
- (void)onCheckShowQZoneNotification:(id)arg1;
- (void)onCheckShowEmailNotification:(id)arg1;
- (void)onClickSwitchButton:(id)arg1;
- (void)onChangeStateButton:(id)arg1 state:(int)arg2;
- (void)onClickRestoreDefaults:(id)arg1;
- (void)openGroupMessageSettingPanel:(id)arg1;
- (void)onCheckMessageDetail:(id)arg1;
- (void)onCheckQzoneBadge:(id)arg1;
- (void)onCheckFutuBadge:(id)arg1;
- (void)onCheckEmailBadge:(id)arg1;
- (void)prepareToBeHidden:(BOOL)arg1;
- (void)onCheckEnableSystemSound:(id)arg1;
- (void)loadSettings;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

