//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProfileBaseInfoViewController.h"

#import "MQFloatTextFieldDelegate.h"
#import "NSCollectionViewDelegate.h"

@class MQFloatTextField, MQSessionID, NSArray, NSCollectionView, NSLayoutConstraint, NSMutableArray, NSString, NSTextField, TXColorView, TXHoverButton;

@interface ProfileDisInfoViewController : ProfileBaseInfoViewController <MQFloatTextFieldDelegate, NSCollectionViewDelegate>
{
    TXColorView *_infoView;
    NSTextField *_labelDisCard;
    MQFloatTextField *_textDisCard;
    TXHoverButton *_btnEditDisCard;
    NSTextField *_labelDisName;
    MQFloatTextField *_textDisName;
    TXHoverButton *_btnEditDisName;
    NSTextField *_labelDisMember;
    NSCollectionView *_collectionView;
    NSString *_realDiscussName;
    NSMutableArray *_images;
    NSLayoutConstraint *_collectionViewHeightconstraint;
    NSArray *_memberList;
    MQSessionID *_sessionId;
}

@property(retain, nonatomic) MQSessionID *sessionId; // @synthesize sessionId=_sessionId;
- (void).cxx_destruct;
- (void)handleAvatarChange:(id)arg1;
- (void)saveMyDiscussCard;
- (void)saveDiscussTitle;
- (void)floatTextFieldDidEndEditing:(id)arg1;
- (void)onClickEditDiscussCard:(id)arg1;
- (void)onClickEditDiscussName:(id)arg1;
- (void)didEndNewDiscussSheet:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)onDiscussAddMember:(id)arg1;
- (void)itemClicked:(id)arg1;
- (void)reLayoutCollectionView:(unsigned long long)arg1;
- (void)updateDiscussMemberCollectionView:(id)arg1;
- (void)reloadMemberList;
- (id)discussShowNameFromRealName;
- (id)selfDiscussMemberInfo:(id)arg1;
- (void)updateContentWithDiscussProfile:(id)arg1;
- (void)awakeFromNib;
- (id)infoNibName;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

