//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "MQUIScrollDelegate.h"
#import "NSPopoverDelegate.h"
#import "ProfileActiveHeaderViewDelegate.h"
#import "ProfilePreferenceDelegate.h"

@class MQProfileSlideView, MQRoundRectImageView, MQUIScrollView, NSLayoutConstraint, NSPopover, NSString, NSTimer, NSView, ProfileActiveHeaderView, ProfileBaseInfoViewController, ProfileBasePreferenceViewController, ProfileFlippedContainer, TXColorView, TXHoverButton, TXPopoverController;

@interface ProfileBaseViewController : NSViewController <MQUIScrollDelegate, ProfileActiveHeaderViewDelegate, ProfilePreferenceDelegate, NSPopoverDelegate>
{
    unsigned long long m_dwUin;
    long long _viewType;
    MQProfileSlideView *_headerCoverView;
    MQRoundRectImageView *_headerBgMask;
    ProfileActiveHeaderView *_headerView;
    MQProfileSlideView *_headerLayView;
    NSView *scrollCenterView;
    TXColorView *scrollArea;
    TXHoverButton *_settingBtn;
    TXHoverButton *_closeBtn;
    ProfileFlippedContainer *_mainView;
    MQUIScrollView *_scrollView;
    NSView *_preferenceView;
    TXColorView *_shadowBg;
    NSLayoutConstraint *_preferenceLeadingConstraint;
    ProfileBaseInfoViewController *_infoController;
    ProfileBasePreferenceViewController *_preferenceController;
    BOOL _scrollAnim;
    BOOL _firstScrollFrameChange;
    int headerBgTopY;
    int topOverPull;
    int headContainerWidth;
    TXPopoverController *_popOver;
    NSPopover *popover;
    NSTimer *scrollTimer;
    int lastScrollY;
    BOOL pauseTimer;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)callBack;
- (void)closePopover;
- (void)popoverWillClose:(id)arg1;
- (void)showPopInView:(id)arg1;
- (void)hidePreferenceViewAnimation:(BOOL)arg1;
- (void)showPreferenceViewAnimation:(BOOL)arg1;
- (void)onSettingBtnClick:(id)arg1;
- (void)showOrHidePreferenceWithAnim:(BOOL)arg1;
- (void)viewWillAddToWindow;
- (void)viewWillRemoveFromWindow;
- (void)onClose:(id)arg1;
- (void)onScroll:(id)arg1;
- (void)updateProfileHeadWithUin:(unsigned long long)arg1;
- (void)stopScrollTimer;
- (void)checkScroll:(id)arg1;
- (void)scrollViewDidScroll:(int)arg1;
- (void)stopScrollAnim:(id)arg1;
- (void)scrollViewDidLiveScroll:(id)arg1;
- (void)scrollViewDidEndScrolling:(id)arg1;
- (void)scrollViewDidScrollToBottom:(id)arg1;
- (void)onScrollOffsetYChanged:(int)arg1;
- (void)scrollViewFrameDidChange:(struct CGRect)arg1;
- (void)onAvatarChange:(id)arg1 imageColor:(long long)arg2;
- (void)onHeadViewRelayout;
- (void)onHeadViewHeightChange;
- (id)createPreferenceContent;
- (id)createInfoViewController;
- (void)onInfoBottomViewHeightNeedChange;
- (void)showOrHideScrollArea;
- (void)infoViewFrameChanged:(id)arg1;
- (void)changeSettingBtnFrame;
- (void)mainViewFrameChanged:(id)arg1;
- (void)reLayoutHeaderContainer;
- (void)notifyHeadViewHeightChange;
- (void)initPreferenceView;
- (id)createActiveHeaderView;
- (void)initScrollArea;
- (void)initHeaderView;
- (void)addScrollInfoConstraints:(id)arg1;
- (void)initBaseView;
- (void)awakeFromNib;
- (unsigned long long)currentUin;
- (void)initViewController;
- (id)initWithType:(long long)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

