//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSData, NSString;

@interface QmfDownstream : JceObjectV2
{
    short jcev2_p_2_r_WnsCode;
    short jcev2_p_3_r_BizCode;
    int jcev2_p_0_r_Seq;
    long long jcev2_p_1_r_Wid;
    NSString *jcev2_p_4_r_ServiceCmd;
    NSData *jcev2_p_5_r_BusiBuff;
    NSData *jcev2_p_6_r_Extra;
    NSString *jcev2_p_7_o_BizErrorMsg;
    NSString *jcev2_p_8_o_Uid;
    NSString *jcev2_p_9_o_anonymousId;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_anonymousId, setter=setJce_anonymousId:) NSString *jcev2_p_9_o_anonymousId; // @synthesize jcev2_p_9_o_anonymousId;
@property(retain, nonatomic, getter=jce_Uid, setter=setJce_Uid:) NSString *jcev2_p_8_o_Uid; // @synthesize jcev2_p_8_o_Uid;
@property(retain, nonatomic, getter=jce_BizErrorMsg, setter=setJce_BizErrorMsg:) NSString *jcev2_p_7_o_BizErrorMsg; // @synthesize jcev2_p_7_o_BizErrorMsg;
@property(retain, nonatomic, getter=jce_Extra, setter=setJce_Extra:) NSData *jcev2_p_6_r_Extra; // @synthesize jcev2_p_6_r_Extra;
@property(retain, nonatomic, getter=jce_BusiBuff, setter=setJce_BusiBuff:) NSData *jcev2_p_5_r_BusiBuff; // @synthesize jcev2_p_5_r_BusiBuff;
@property(retain, nonatomic, getter=jce_ServiceCmd, setter=setJce_ServiceCmd:) NSString *jcev2_p_4_r_ServiceCmd; // @synthesize jcev2_p_4_r_ServiceCmd;
@property(nonatomic, getter=jce_BizCode, setter=setJce_BizCode:) short jcev2_p_3_r_BizCode; // @synthesize jcev2_p_3_r_BizCode;
@property(nonatomic, getter=jce_WnsCode, setter=setJce_WnsCode:) short jcev2_p_2_r_WnsCode; // @synthesize jcev2_p_2_r_WnsCode;
@property(nonatomic, getter=jce_Wid, setter=setJce_Wid:) long long jcev2_p_1_r_Wid; // @synthesize jcev2_p_1_r_Wid;
@property(nonatomic, getter=jce_Seq, setter=setJce_Seq:) int jcev2_p_0_r_Seq; // @synthesize jcev2_p_0_r_Seq;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

