//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDate;

@interface QQAirInfo : NSObject <NSCoding>
{
    long long _pm2dot5;
    long long _quality;
    NSDate *_time;
}

@property(retain, nonatomic) NSDate *time; // @synthesize time=_time;
@property(nonatomic) long long quality; // @synthesize quality=_quality;
@property(nonatomic) long long pm2dot5; // @synthesize pm2dot5=_pm2dot5;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

