//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQBaseSkinConfig : NSObject
{
}

+ (id)getConfigKey;
+ (id)getInstance;
- (void)setViewAppearance:(id)arg1;
- (void)setConfigValues:(id)arg1;

@end

