//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSThread.h"

@class NSRunLoop;

@interface QQBlueThread : NSThread
{
    NSRunLoop *_runloop;
}

+ (void)resumeTimer:(struct dispatch_source_s *)arg1;
+ (void)suspendTimer:(struct dispatch_source_s *)arg1;
+ (void)resetTimer:(struct dispatch_source_s *)arg1;
- (void).cxx_destruct;
- (struct dispatch_source_s *)createTimerWithInterval:(unsigned int)arg1 callback:(id)arg2;
- (void)setRealTime;
- (void)syncWork:(id)arg1;
- (void)asyncWork:(id)arg1;
- (void)doBlock:(id)arg1;
- (void)main;
- (id)runloop;
- (void)addSourceToRunloop;
- (id)init;

@end

