//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QQChatHistoryManager, QQChatHistoryTimeLine;

@interface QQChatHistoryRetrieveSession : NSObject
{
    CDStruct_71990bde _afterCursor;
    CDStruct_71990bde _beforeCursor;
    QQChatHistoryTimeLine *_timeLine;
    QQChatHistoryManager *_manager;
}

@property(nonatomic) __weak QQChatHistoryManager *manager; // @synthesize manager=_manager;
@property(readonly, nonatomic) QQChatHistoryTimeLine *timeLine; // @synthesize timeLine=_timeLine;
- (void).cxx_destruct;
- (BOOL)hasMoreFutureMessages;
- (BOOL)hasMorePastMessages;
- (void)loadBeforeInLimit:(long long)arg1 completion:(id)arg2;
- (void)loadAfterInLimit:(long long)arg1 completion:(id)arg2;
- (void)setBaseDateForItem:(id)arg1;
- (void)setBaseDateForGroup:(id)arg1;
- (id)initWithTimeLine:(id)arg1 forManager:(id)arg2;

@end

