//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IEngineDispatchDelegate.h"

@class NSMutableArray, NSMutableSet, NSString;

@interface QQGetRoamMsgModel : NSObject <IEngineDispatchDelegate>
{
    int LastSeq;
    NSMutableArray *_MsgArray;
    id <QQGetRoamMsgModelProtocol> _delegate;
    int _TotalGetNum;
    NSMutableSet *_gettingUins;
}

+ (id)shareInstance;
@property(nonatomic) __weak id <QQGetRoamMsgModelProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)hasPassword;
- (BOOL)roamOn;
- (void)switchRoamMessage:(BOOL)arg1;
- (void)deleteUserRoamInfo:(id)arg1;
- (void)deleteUserRoamInfo;
- (void)removeUserSig;
- (void)removeUserPwd;
- (void)removeUserSig:(id)arg1;
- (void)removeUserPwd:(id)arg1;
- (void)setUserSig:(id)arg1;
- (void)setUserPwd:(id)arg1;
- (id)getUserSig;
- (id)getUserPwd;
- (void)closeGetRoamMsgFunction;
- (void)ClearAllCache;
- (void)actionGetRoamMsg:(id)arg1;
- (void)didRecievedMsg:(CDStruct_a00ab4be)arg1;
- (int)sendGetRoamFriendUin:(long long)arg1 lastMsgTime:(int)arg2 random:(int)arg3;
- (void)QQGetRoamMsg:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

