//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQGroupFileTransferOperation.h"

#import "QQGroupFileOIDBRespondDelegate.h"

@class NSString, QQGroupFileDownloadTask, QQGroupFileOIDBRequest;

@interface QQGroupFolderDownloadOperation : QQGroupFileTransferOperation <QQGroupFileOIDBRespondDelegate>
{
    QQGroupFileOIDBRequest *_fileListRequest;
    QQGroupFileDownloadTask *_downloadTask;
}

@property(retain, nonatomic) QQGroupFileDownloadTask *downloadTask; // @synthesize downloadTask=_downloadTask;
@property(retain, nonatomic) QQGroupFileOIDBRequest *fileListRequest; // @synthesize fileListRequest=_fileListRequest;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cancel;
- (void)didFinishSubTask;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)startDownloadFiles;
- (void)groupFileOIDBRequest:(id)arg1 didFailWithError:(id)arg2;
- (void)groupFileOIDBRequest:(id)arg1 didReceivedRespond:(id)arg2;
- (void)checkFolder;
- (void)start;
- (id)initWithDownloadTask:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

