//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

@interface QQMessageTableBase : QQBaseSingleton
{
}

+ (id)commonMesssageModelFromQueryResult:(id)arg1;
- (void)upOfflineFileMsg:(id)arg1 uuid:(id)arg2 forContent:(id)arg3 tableName:(id)arg4 inDb:(id)arg5;
- (void)upOfflineFileMsg:(id)arg1 uuid:(id)arg2 forRead:(int)arg3 tableName:(id)arg4 inDb:(id)arg5;
- (void)upOfflineFileMsg:(id)arg1 time:(int)arg2 forRead:(int)arg3 tableName:(id)arg4 inDb:(id)arg5;
- (void)upOffLineFileMsg:(id)arg1 time:(long long)arg2 forRead:(int)arg3 tableName:(id)arg4 inDb:(id)arg5;
- (BOOL)updateFileMsgContent:(id)arg1 msgID:(int)arg2 msgTime:(int)arg3 content:(id)arg4 tableName:(id)arg5 inDb:(id)arg6;
- (void)upOffLineFileMsg:(id)arg1 msgId:(int)arg2 forRead:(int)arg3 tableName:(id)arg4 inDb:(id)arg5;
- (id)messageWithMaxMsgID:(int)arg1 withCondition:(id)arg2 withArguments:(id)arg3 tableName:(id)arg4 inDb:(id)arg5;
- (id)messageIDsByDayWithMaxMsgID:(int)arg1 withCondition:(id)arg2 withArguments:(id)arg3 tableName:(id)arg4 inDb:(id)arg5;
- (id)getPageIndexWithMessageDate:(id)arg1 tableName:(id)arg2 inDb:(id)arg3;
- (int)getLastMessageTimeWithTableName:(id)arg1 inDb:(id)arg2;
- (id)getMessageDayListWithFromDate:(id)arg1 toDate:(id)arg2 tableName:(id)arg3 inDb:(id)arg4;
- (id)getMessageWithPageIndex:(int)arg1 tableName:(id)arg2 inDb:(id)arg3;
- (id)getPageCountWithTableName:(id)arg1 inDb:(id)arg2;
- (id)getRecentMsgWithSessType:(int)arg1 identityUin:(long long)arg2 inDb:(id)arg3;
- (id)getDiscussLastActiveTimeInDb:(id)arg1;
- (id)getC2CMessageWithIdentify:(unsigned long long)arg1 startTime:(int)arg2 endTime:(int)arg3 tableName:(id)arg4 inDb:(id)arg5;
- (id)getMessageListWithIdentify:(unsigned long long)arg1 EndTime:(unsigned int)arg2 exceptMsgId:(unsigned int)arg3 exceptBlankMsg:(BOOL)arg4 count:(unsigned int)arg5 tableName:(id)arg6 inDb:(id)arg7;
- (id)getAssociatedLongTextMsgWithMsgArray:(id)arg1 tableName:(id)arg2 inDb:(id)arg3;
- (id)getClusterMsgEndSeq:(unsigned int)arg1 count:(unsigned int)arg2 tableName:(id)arg3 inDb:(id)arg4;
- (id)getClusterMsgFromSeq:(unsigned int)arg1 endSeq:(unsigned int)arg2 tableName:(id)arg3 inDb:(id)arg4;
- (id)getRecordCount:(id)arg1 inDb:(id)arg2;
- (int)getBubbleIdWithSessType:(int)arg1 tableName:(id)arg2 senderUin:(long long)arg3 inDb:(id)arg4;
- (id)getLastMessageWithSessType:(int)arg1 tableName:(id)arg2 inDb:(id)arg3;
- (double)maxMessageTimeOfTableName:(id)arg1 inDb:(id)arg2;
- (unsigned int)getMsgMaxSeqWithTableName:(id)arg1 inDb:(id)arg2;
- (id)messageWithIdentify:(long long)arg1 msgSeq:(int)arg2 time:(int)arg3 random:(int)arg4 tableName:(id)arg5 inDb:(id)arg6;
- (id)messageWithMsgIds:(id)arg1 tableName:(id)arg2 inDb:(id)arg3;
- (id)querySQLWithTableName:(id)arg1 condition:(id)arg2;
- (id)commonMesssageModelFromQueryResult:(id)arg1;
- (void)setFileMsgSendStateWithMsgID:(int)arg1 state:(int)arg2 read:(int)arg3 tableName:(id)arg4 inDb:(id)arg5;
- (void)updateMessageRichInfo:(id)arg1 tableName:(id)arg2 inDb:(id)arg3;
- (void)markC2CMessageIsFault:(id)arg1 tableName:(id)arg2 inDb:(id)arg3;
- (void)updateMessageSeqWithMsgId:(int)arg1 msgSeq:(int)arg2 time:(int)arg3 tableName:(id)arg4 inDb:(id)arg5;
- (void)updateMessageOnSendResult:(id)arg1 state:(int)arg2 tableName:(id)arg3 inDb:(id)arg4;
- (id)messageModelKeyToFieldName:(id)arg1 model:(id)arg2;
- (void)updateQQMessageModel:(id)arg1 keyArray:(id)arg2 tableName:(id)arg3 inDb:(id)arg4;
- (void)deleteQQMessageFromTime:(int)arg1 toTime:(int)arg2 tableName:(id)arg3 inDb:(id)arg4;
- (BOOL)deleteMessages:(id)arg1 containLargeMsg:(BOOL)arg2 tableName:(id)arg3 inDb:(id)arg4;
- (void)deleteMsgsWithTableName:(id)arg1 inDb:(id)arg2;
- (BOOL)insertSingleQQMessageModel:(id)arg1 tableName:(id)arg2 toDb:(id)arg3;
- (id)_getClusterId:(id)arg1;
- (id)getInsertSql:(id)arg1;
- (void)createTableIndex_msgSeq:(id)arg1 inDb:(id)arg2;
- (void)createTableIndex_time:(id)arg1 inDb:(id)arg2;
- (void)createTableWithName:(id)arg1 sessType:(int)arg2 inDb:(id)arg3;

@end

