//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQMultiVideoMsgModel : NSObject
{
    int _msgTime;
    unsigned long long _friuin;
    unsigned int _msgDataLen;
    char *_msgData;
}

@property(nonatomic) char *msgData; // @synthesize msgData=_msgData;
@property(nonatomic) unsigned int msgDataLen; // @synthesize msgDataLen=_msgDataLen;
@property(nonatomic) unsigned long long friuin; // @synthesize friuin=_friuin;
@property(nonatomic) int msgTime; // @synthesize msgTime=_msgTime;
- (void)dealloc;
- (id)init;

@end

