//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQUtilFun : NSObject
{
}

+ (id)returnValueOfInvoke:(id)arg1;
+ (void)QQSetWORD:(char *)arg1 from:(unsigned short)arg2;
+ (void)QQSetDWORD:(char *)arg1 from:(unsigned int)arg2;
+ (id)MD5Hash:(id)arg1;
+ (id)HexStrToBuff:(id)arg1;
+ (id)HexStrFromBuff:(const char *)arg1 length:(int)arg2;

@end

