//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@protocol QRCodeCallBackProtocol <NSObject>
- (void)auth_failed:(int)arg1 withMsg:(NSString *)arg2;
- (void)auth_succ:(unsigned long long)arg1;
- (void)showQrPic_failed:(int)arg1 withMsg:(NSString *)arg2;
- (void)showQrPic_succWithPush:(NSData *)arg1 withExpireTime:(unsigned int)arg2 withQueryTime:(unsigned short)arg3;
- (void)showQrPic_succ:(NSData *)arg1 withExpireTime:(unsigned int)arg2 withQueryTime:(unsigned short)arg3;
- (void)qrCodeFailed:(int)arg1 withMsg:(NSString *)arg2;
- (void)qrCodeReject_failed:(int)arg1 withMsg:(NSString *)arg2;
- (void)qrCodeReject_succ;
- (void)qrCodeConfirm_failed:(int)arg1 withMsg:(NSString *)arg2;
- (void)qrCodeConfirm_succ:(unsigned int)arg1 withAppName:(NSString *)arg2;
- (void)qrCodeVerify_failed:(int)arg1 withMsg:(NSString *)arg2;
- (void)qrCodeVerify_succ:(unsigned int)arg1 withAppName:(NSString *)arg2;
@end

