//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QZBaseParser.h"

@class NSArray, URKArchive;

@interface QZRarParser : QZBaseParser
{
    URKArchive *_rarArchive;
    NSArray *_unrarFiles;
}

- (void).cxx_destruct;
- (BOOL)hasPassword;
- (id)fileWithRarFile:(id)arg1;
- (id)getFilesList;
- (void)parseSubFiles;
- (void)parse;
- (void)cancelParse;
- (void)setPassword:(id)arg1;
- (id)urkArchive;

@end

