//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RqdErrorPopulator : NSObject
{
}

+ (BOOL)populateError:(id *)arg1 errnoVal:(int)arg2 description:(id)arg3;

@end

