//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSString, RqdLocalStrategy;

@interface RqdFilePersistHandler : NSObject
{
    NSString *folderPath;
    NSString *crashMetaFile;
    NSString *userinfoFile;
    NSString *cmmstrategyFile;
    NSMutableArray *allUserInfos;
    NSMutableDictionary *allCrashMetas;
    RqdLocalStrategy *commonStrategyData;
    BOOL dataLoaded;
    BOOL strategyLoaded;
}

+ (id)sharedInstance;
- (void)persistAllUserInfoDatas;
- (int)getCurrSize;
- (id)getAllDatas;
- (BOOL)deleteDatas:(id)arg1;
- (BOOL)saveOneData:(id)arg1;
- (id)getByMeta:(id)arg1;
- (id)getCrashesNeedUpload:(int)arg1;
- (id)getCrashesNeedDel;
- (id)getAllCrashed:(int)arg1;
- (BOOL)deleteCrashes:(id)arg1;
- (BOOL)deleteCrash:(id)arg1;
- (BOOL)deleteCrashMeta:(id)arg1;
- (id)getCrashWithMd5:(id)arg1;
- (id)getLatestCrash;
- (BOOL)deleteAllInvalidCrashes;
- (BOOL)deleteAllCrashes;
- (BOOL)updateOneCrash:(id)arg1 uplaoded:(BOOL)arg2;
- (BOOL)updateOneCrash:(id)arg1;
- (BOOL)saveOneCrash:(id)arg1;
- (BOOL)hasCrash;
- (void)persistAllCrashMetaDatas;
- (BOOL)saveCommonStrategy:(id)arg1;
- (id)loadCommonStrategyFile;
- (void)loadStrategys;
- (void)loadAllDatas;
- (BOOL)changeDbPath:(id)arg1;
- (id)init;

@end

