//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSProgressIndicator;

@interface SearchProgressWindowController : NSWindowController
{
    NSProgressIndicator *progressIndicator;
}

- (void).cxx_destruct;
- (void)OnCancel:(id)arg1;
- (void)UpdateProgressBar:(double)arg1;
- (void)windowDidLoad;
- (id)initWithWindow:(id)arg1;

@end

