//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSActionCell.h"

#import "NSCoding.h"

@class NSGradient, NSSet, NSString, SRValidator;

@interface SRRecorderCell : NSActionCell <NSCoding>
{
    NSGradient *recordingGradient;
    NSString *autosaveName;
    BOOL isRecording;
    BOOL mouseInsideTrackingArea;
    BOOL mouseDown;
    int style;
    BOOL isAnimating;
    double transitionProgress;
    BOOL isAnimatingNow;
    BOOL isAnimatingTowardsRecording;
    BOOL comboJustChanged;
    long long removeTrackingRectTag;
    long long snapbackTrackingRectTag;
    struct _KeyCombo keyCombo;
    BOOL hasKeyChars;
    NSString *keyChars;
    NSString *keyCharsIgnoringModifiers;
    unsigned long long allowedFlags;
    unsigned long long requiredFlags;
    unsigned long long recordingFlags;
    BOOL allowsKeyOnly;
    BOOL escapeKeysRecord;
    NSSet *cancelCharacterSet;
    SRValidator *validator;
    id delegate;
    BOOL globalHotKeys;
    void *hotKeyModeToken;
}

+ (BOOL)styleSupportsAnimation:(int)arg1;
- (void).cxx_destruct;
- (id)keyCharsIgnoringModifiers;
- (id)keyChars;
- (id)keyComboString;
- (void)setAutosaveName:(id)arg1;
- (id)autosaveName;
- (void)setCanCaptureGlobalHotKeys:(BOOL)arg1;
- (BOOL)canCaptureGlobalHotKeys;
- (void)setKeyCombo:(struct _KeyCombo)arg1;
- (struct _KeyCombo)keyCombo;
- (void)setRequiredFlags:(unsigned long long)arg1;
- (unsigned long long)requiredFlags;
- (void)setAllowsKeyOnly:(BOOL)arg1 escapeKeysRecord:(BOOL)arg2;
- (BOOL)escapeKeysRecord;
- (BOOL)allowsKeyOnly;
- (void)setAllowedFlags:(unsigned long long)arg1;
- (unsigned long long)allowedFlags;
- (void)flagsChanged:(id)arg1;
- (BOOL)performKeyEquivalent:(id)arg1;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)resetTrackingRects;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)setStyle:(int)arg1;
- (int)style;
- (void)setAnimates:(BOOL)arg1;
- (BOOL)animates;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;
- (BOOL)shortcutValidator:(id)arg1 isKeyCode:(long long)arg2 andFlagsTaken:(unsigned long long)arg3 reason:(id *)arg4;
- (BOOL)_isEmpty;
- (unsigned long long)_filteredCocoaToCarbonFlags:(unsigned long long)arg1;
- (BOOL)_validModifierFlags:(unsigned long long)arg1;
- (unsigned long long)_filteredCocoaFlags:(unsigned long long)arg1;
- (struct CGRect)_snapbackRectForFrame:(struct CGRect)arg1;
- (struct CGRect)_removeButtonRectForFrame:(struct CGRect)arg1;
- (void)_loadKeyCombo;
- (void)_saveKeyCombo;
- (id)_defaultsKeyForAutosaveName:(id)arg1;
- (void)_endRecording;
- (void)_startRecording;
- (void)_transitionTick;
- (void)_endRecordingTransition;
- (void)_startRecordingTransition;
- (BOOL)_supportsAnimation;
- (BOOL)_effectiveIsAnimating;
- (void)_setJustChanged;
- (void)_createGradient;
- (void)_privateInit;

@end

