//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface STDetectResult : NSObject
{
    int _retCode;
    unsigned int _clientIp;
    int _sendPkgNum;
    int _recvPkgNum;
    int _connCost;
    int _recvAckDelayTime;
    int _sendPkgTimeoutNum;
    int _connTimeoutNum;
    int _sndPkgSize;
    NSMutableArray *_vConnCost;
    NSMutableArray *_vRecvAckDelayTime;
}

@property(retain, nonatomic) NSMutableArray *vRecvAckDelayTime; // @synthesize vRecvAckDelayTime=_vRecvAckDelayTime;
@property(retain, nonatomic) NSMutableArray *vConnCost; // @synthesize vConnCost=_vConnCost;
@property(nonatomic) int sndPkgSize; // @synthesize sndPkgSize=_sndPkgSize;
@property(nonatomic) int connTimeoutNum; // @synthesize connTimeoutNum=_connTimeoutNum;
@property(nonatomic) int sendPkgTimeoutNum; // @synthesize sendPkgTimeoutNum=_sendPkgTimeoutNum;
@property(nonatomic) int recvAckDelayTime; // @synthesize recvAckDelayTime=_recvAckDelayTime;
@property(nonatomic) int connCost; // @synthesize connCost=_connCost;
@property(nonatomic) int recvPkgNum; // @synthesize recvPkgNum=_recvPkgNum;
@property(nonatomic) int sendPkgNum; // @synthesize sendPkgNum=_sendPkgNum;
@property(nonatomic) unsigned int clientIp; // @synthesize clientIp=_clientIp;
@property(nonatomic) int retCode; // @synthesize retCode=_retCode;
- (void)dealloc;
- (id)init;

@end

