//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol StringFormatterDelegate <NSObject>

@optional
- (void)beyondMaxLengthNotify:(NSString *)arg1 exactIndex:(long long)arg2 exactStr:(NSString *)arg3;
@end

