//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface TableViewMember : NSObject
{
    NSNumber *_privilegeLevel;
    NSNumber *_uin;
    NSString *_nickName;
    NSString *_cardName;
    NSNumber *_gender;
    NSNumber *_lastMsgTime;
}

@property(copy) NSNumber *LastMsgTime; // @synthesize LastMsgTime=_lastMsgTime;
@property(copy) NSNumber *Gender; // @synthesize Gender=_gender;
@property(copy) NSString *CardName; // @synthesize CardName=_cardName;
@property(copy) NSString *NickName; // @synthesize NickName=_nickName;
@property(copy) NSNumber *Uin; // @synthesize Uin=_uin;
@property(copy) NSNumber *PrivilegeLevel; // @synthesize PrivilegeLevel=_privilegeLevel;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithPrivilegeLevel:(id)arg1 Uin:(id)arg2 NickName:(id)arg3 CardName:(id)arg4 Gender:(id)arg5 LastMsgTime:(id)arg6;

@end

