//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"
#import "TChatHisRowViewDelegate.h"

@class NSMutableArray, NSString, NSTableView;

@interface TChatHisSearchPresenter : NSObject <NSTableViewDelegate, NSTableViewDataSource, TChatHisRowViewDelegate>
{
    BOOL _isSetFirstResult;
    unsigned long long _timeFilter;
    unsigned long long _sessionFilter;
    NSTableView *_tableView;
    NSMutableArray *_dataSource;
    id <TChatHisSearchPresenterDelegate> _delegate;
    long long _searchResultAllCount;
    NSMutableArray *_dataSourceOfFriends;
    NSMutableArray *_dataSourceOfGroup;
    NSMutableArray *_dataSourceOfDisccuss;
    NSMutableArray *_dataSourceOfTempSession;
    NSMutableArray *_dataSourceOfDevice;
}

@property(retain, nonatomic) NSMutableArray *dataSourceOfDevice; // @synthesize dataSourceOfDevice=_dataSourceOfDevice;
@property(retain, nonatomic) NSMutableArray *dataSourceOfTempSession; // @synthesize dataSourceOfTempSession=_dataSourceOfTempSession;
@property(retain, nonatomic) NSMutableArray *dataSourceOfDisccuss; // @synthesize dataSourceOfDisccuss=_dataSourceOfDisccuss;
@property(retain, nonatomic) NSMutableArray *dataSourceOfGroup; // @synthesize dataSourceOfGroup=_dataSourceOfGroup;
@property(retain, nonatomic) NSMutableArray *dataSourceOfFriends; // @synthesize dataSourceOfFriends=_dataSourceOfFriends;
@property(nonatomic) long long searchResultAllCount; // @synthesize searchResultAllCount=_searchResultAllCount;
@property(nonatomic) BOOL isSetFirstResult; // @synthesize isSetFirstResult=_isSetFirstResult;
@property(nonatomic) __weak id <TChatHisSearchPresenterDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak NSTableView *tableView; // @synthesize tableView=_tableView;
@property(readonly, nonatomic) unsigned long long sessionFilter; // @synthesize sessionFilter=_sessionFilter;
@property(readonly, nonatomic) unsigned long long timeFilter; // @synthesize timeFilter=_timeFilter;
- (void).cxx_destruct;
- (long long)_getFirstCell;
- (void)_insertRowsWithItem:(id)arg1;
- (void)_addObjectToDataSource:(id)arg1;
- (void)_createSectionInDataSource:(id)arg1 item:(id)arg2;
- (void)onClickItem:(id)arg1;
- (void)drawSelectionForContactRowView:(id)arg1 rect:(struct CGRect)arg2;
- (void)tableViewSelectionDidChange:(id)arg1;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (id)tableView:(id)arg1 rowViewForRow:(long long)arg2;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)cancelSearch;
- (void)searchWithKey:(id)arg1 andData:(id)arg2 andSessionFilter:(unsigned long long)arg3 completion:(id)arg4;
- (void)_removeDataSources;
- (void)filterDateWithTimerFilter:(unsigned long long)arg1 andSessionFilter:(unsigned long long)arg2 completion:(id)arg3;
- (void)dealloc;
- (void)handleRemoveSearchResult:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

