//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChatVirtualView.h"

@interface TChatImageVirtualView : TChatVirtualView
{
}

- (void)setIndex:(long long)arg1;
- (id)viewAttributedDescription;
- (void)drawContentInRect:(struct CGRect)arg1;
- (void)drawBackgroundInRect:(struct CGRect)arg1;
- (id)init;
- (void)dealloc;

@end

