//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

@class NSDate, NSMutableArray, NSObject<OS_dispatch_queue>, NSString, TChatHistorySearchModelWrapper;

@interface TChatSearcher : QQBaseSingleton
{
    BOOL _isCancel;
    BOOL _isSearching;
    int _lastItemSessionType;
    NSObject<OS_dispatch_queue> *_queue_search;
    NSMutableArray *_targetModelList;
    NSMutableArray *_seacherModelList;
    unsigned long long _sessionFilter;
    id _getResultCompletion;
    long long _taskIndex;
    NSString *_key;
    NSDate *_fromDate;
    NSMutableArray *_friendList;
    long long _lastItemUin;
    TChatHistorySearchModelWrapper *_hisSearchModelForSingleWin;
}

@property(retain, nonatomic) TChatHistorySearchModelWrapper *hisSearchModelForSingleWin; // @synthesize hisSearchModelForSingleWin=_hisSearchModelForSingleWin;
@property(nonatomic) long long lastItemUin; // @synthesize lastItemUin=_lastItemUin;
@property(nonatomic) int lastItemSessionType; // @synthesize lastItemSessionType=_lastItemSessionType;
@property(retain, nonatomic) NSMutableArray *friendList; // @synthesize friendList=_friendList;
@property(retain, nonatomic) NSDate *fromDate; // @synthesize fromDate=_fromDate;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
@property(nonatomic) long long taskIndex; // @synthesize taskIndex=_taskIndex;
@property(nonatomic) BOOL isSearching; // @synthesize isSearching=_isSearching;
@property(copy, nonatomic) id getResultCompletion; // @synthesize getResultCompletion=_getResultCompletion;
@property(nonatomic) unsigned long long sessionFilter; // @synthesize sessionFilter=_sessionFilter;
@property(retain, nonatomic) NSMutableArray *seacherModelList; // @synthesize seacherModelList=_seacherModelList;
@property(retain, nonatomic) NSMutableArray *targetModelList; // @synthesize targetModelList=_targetModelList;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue_search; // @synthesize queue_search=_queue_search;
@property(readonly, nonatomic) BOOL isCancel; // @synthesize isCancel=_isCancel;
- (void).cxx_destruct;
- (id)_getDeviceList;
- (id)_getTempSessionList;
- (id)_getRecentSessionList;
- (id)_getDiscussList;
- (id)_getGroupList;
- (id)_getFriendList;
- (void)_initData;
- (void)cancelSearch;
- (void)searchWithKey:(id)arg1 andDate:(id)arg2 andSessionFilter:(unsigned long long)arg3 completion:(id)arg4;
- (void)searchWithUin:(long long)arg1 sessionType:(int)arg2 key:(id)arg3 andDate:(id)arg4 completion:(id)arg5;
- (id)_firstAvaibleTask;
- (void)_start;
- (void)_createTask;
- (void)_getUinAndSessionTypeWithTarget:(id)arg1 type:(int *)arg2 uin:(long long *)arg3;
- (void)dealloc;
- (id)init;

@end

