//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChatBaseBubbleBuilder.h"

#import "NSTextViewDelegate.h"

@class NSString;

@interface TChatCompoundCellBuilder : TChatBaseBubbleBuilder <NSTextViewDelegate>
{
    id <TChatCellBuilderEventDelegate> _eventDelegate;
}

@property(nonatomic) __weak id <TChatCellBuilderEventDelegate> eventDelegate; // @synthesize eventDelegate=_eventDelegate;
- (void).cxx_destruct;
- (id)tableCellAttributedStringWithString:(id)arg1 table:(id)arg2 backgroundColor:(id)arg3 borderColor:(id)arg4 row:(int)arg5 column:(int)arg6 columnSpan:(int)arg7;
- (id)tableAttributedString;
- (struct CGSize)resizeImage:(id)arg1 scaleDownFitTo:(struct CGSize)arg2;
- (void)resizeAllImageInAttributeString:(id)arg1 withMaxSize:(struct CGSize)arg2;
- (struct CGSize)sizeForAttributedString:(id)arg1 width:(double)arg2 viewModel:(id)arg3;
- (id)contentAttStr:(id)arg1;
- (id)getRangeStr:(id)arg1 findText:(id)arg2;
- (void)refreshWithModel:(id)arg1;
- (double)getContentHeightWidthModel:(id)arg1 row:(long long)arg2 cellWidth:(double)arg3;
- (id)getIdentifier;
- (long long)getBubbleType;
- (id)getFooterView:(id)arg1 message:(id)arg2 parentView:(id)arg3 cellWidth:(double)arg4;
- (double)getFooterHeightWidthModel:(id)arg1 row:(long long)arg2 cellWidth:(double)arg3;
- (id)getContentView:(id)arg1 message:(id)arg2 parentView:(id)arg3 cellWidth:(double)arg4;
- (void)textView:(id)arg1 clickedOnCell:(id)arg2 inRect:(struct CGRect)arg3 atIndex:(unsigned long long)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

