//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChatBaseViewModel.h"

@class NSImage, NSString, NSWindow;

@interface TChatHistoryFileViewModel : TChatBaseViewModel
{
    NSImage *_icon;
    NSString *_name;
    NSString *_size;
    NSString *_date;
    NSString *_sender;
    NSString *_state;
    double _progress;
    BOOL _showProgress;
    unsigned long long _operationImageType;
    SEL _operationSelector;
    NSString *_operationName;
    NSWindow *_toastWindow;
    id <TChatHistoryFileViewModelDelegate> _delegate;
}

@property(nonatomic) __weak id <TChatHistoryFileViewModelDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak NSWindow *toastWindow; // @synthesize toastWindow=_toastWindow;
@property(readonly, nonatomic) NSString *operationName; // @synthesize operationName=_operationName;
@property(readonly, nonatomic) SEL operationSelector; // @synthesize operationSelector=_operationSelector;
@property(readonly, nonatomic) unsigned long long operationImageType; // @synthesize operationImageType=_operationImageType;
@property(readonly, nonatomic) BOOL showProgress; // @synthesize showProgress=_showProgress;
@property(readonly, nonatomic) double progress; // @synthesize progress=_progress;
@property(readonly, nonatomic) NSString *state; // @synthesize state=_state;
@property(readonly, nonatomic) NSString *sender; // @synthesize sender=_sender;
@property(readonly, nonatomic) NSString *date; // @synthesize date=_date;
@property(readonly, nonatomic) NSString *size; // @synthesize size=_size;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSImage *icon; // @synthesize icon=_icon;
- (void).cxx_destruct;
- (id)msgViewModel;
- (BOOL)showSaveTo;
- (BOOL)isImageFile;
- (void)onSaveToPath:(id)arg1;
- (void)refuseOnlineFile;
- (void)cancelOnlineFile;
@property(readonly, nonatomic) BOOL isOnlineFile;
@property(readonly, nonatomic) NSString *filePath;
- (void)notifyUpdate;
- (id)initWithMessageModel:(id)arg1;

@end

