//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChatAIOTipViewModel.h"

@class NSString;

@interface TChatWalletTipsViewModel : TChatAIOTipViewModel
{
    NSString *_redPackName;
    NSString *_timeUnitStr;
    NSString *_uin4Lucky;
    NSString *_uin4Host;
    long long _timeNum;
}

@property(nonatomic) long long timeNum; // @synthesize timeNum=_timeNum;
@property(copy, nonatomic) NSString *uin4Host; // @synthesize uin4Host=_uin4Host;
@property(copy, nonatomic) NSString *uin4Lucky; // @synthesize uin4Lucky=_uin4Lucky;
@property(copy, nonatomic) NSString *timeUnitStr; // @synthesize timeUnitStr=_timeUnitStr;
@property(copy, nonatomic) NSString *redPackName; // @synthesize redPackName=_redPackName;
- (void).cxx_destruct;
- (id)_getHostName;
- (id)_getTimeUnitStr:(id)arg1;
- (BOOL)_isEnglish;
- (id)_displayNameWithUin:(id)arg1;
- (id)_getLocalString:(id)arg1;
- (void)_getTimeString:(id)arg1;
- (id)text;
- (id)outputMessageWithInformativeText:(id)arg1 time:(double)arg2 chatUIStyle:(int)arg3 background:(BOOL)arg4;
- (void)_initData;
- (id)initWithMessageModel:(id)arg1;

@end

