//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSColor, NSImage, NSString;

@protocol TChatPickerCellProtocol <NSObject>
@property(copy, nonatomic) id clickActionBtn;
- (void)setActionBtnShowWhenHover:(BOOL)arg1;
- (void)setActionBtnHidden:(BOOL)arg1;
- (void)setHoverBackgroundColor:(NSColor *)arg1;
- (void)setContentPaddingLeft:(double)arg1;
- (void)setChecked:(BOOL)arg1;
- (void)setSubTitle:(NSString *)arg1;
- (void)setTitle:(NSString *)arg1;
- (void)setIcon:(NSImage *)arg1;
@end

