//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChatBaseCellView.h"

#import "TChatRichTextViewEventDelegate.h"

@class NSLayoutConstraint, NSString, NSView, SurpriseButton, TChatAvatarAction, TChatAvatarView, TChatCellBubbleView, TChatRichTextView, TChatTranslateHandler, TChatTranslateSuccessedTailView, TXHoverButton;

@interface TChatBubbleCellView : TChatBaseCellView <TChatRichTextViewEventDelegate>
{
    BOOL _isSelf;
    BOOL _hasBubble;
    TChatRichTextView *_nickNameView;
    TChatAvatarView *_avatarView;
    TChatCellBubbleView *_bubbleView;
    TChatAvatarAction *_menuAction;
    SurpriseButton *_surpriseBtn;
    TChatTranslateHandler *_translateHandler;
    TChatTranslateSuccessedTailView *_translateTailView;
    NSView *_contentWrapView;
    double _contentWrapWidth;
    double _contentWrapHeight;
    NSView *_footerWrapView;
    double _footerWrapWidth;
    double _footerWrapHeight;
    NSLayoutConstraint *_c_avatarview_bubble_width_both;
    NSLayoutConstraint *_c_avatarview_bubble_height_both;
    NSLayoutConstraint *_c_avatarview_bubble_leading_other_bubble;
    NSLayoutConstraint *_c_avatarview_bubble_trailing_self_bubble;
    NSLayoutConstraint *_c_avatarview_bubble_top_both_bubble;
    NSLayoutConstraint *_c_nicknameview_bubble_width_both_bubble;
    NSLayoutConstraint *_c_nicknameview_bubble_height_both_bubble;
    NSLayoutConstraint *_c_nicknameview_bubble_trailing_self_bubble;
    NSLayoutConstraint *_c_nicknameview_bubble_leading_other_bubble;
    NSLayoutConstraint *_c_nicknameview_bubble_top_both_bubble;
    NSLayoutConstraint *_c_contentwrap_bubble_width_both_bubble;
    NSLayoutConstraint *_c_contentwrap_bubble_height_both_bubble;
    NSLayoutConstraint *_c_contentwrap_bubble_leading_other_bubble;
    NSLayoutConstraint *_c_contentwrap_bubble_traling_self_bubble;
    NSLayoutConstraint *_c_contentwrap_bubble_top_both_bubble;
    NSLayoutConstraint *_c_swiftaddone_bubble_width_both_bubble;
    NSLayoutConstraint *_c_swiftaddone_bubble_height_both_bubble;
    NSLayoutConstraint *_c_swiftaddone_bubble_top_both_bubble;
    NSLayoutConstraint *_c_swiftaddone_bubble_leading_other_bubble;
    NSLayoutConstraint *_c_swiftaddone_bubble_traling_self_bubble;
    NSLayoutConstraint *_c_footertwrap_bubble_width_both_bubble;
    NSLayoutConstraint *_c_footerwrap_bubble_height_both_bubble;
    NSLayoutConstraint *_c_footerwrap_bubble_leading_other_bubble;
    NSLayoutConstraint *_c_footerwrap_bubble_traling_self_bubble;
    NSLayoutConstraint *_c_footerwrap_bubble_top_both_bubble;
    NSLayoutConstraint *_c_surprise_bubble_width_both_bubble;
    NSLayoutConstraint *_c_surprise_bubble_height_both_bubble;
    NSLayoutConstraint *_c_surprise_bubble_leading_other_bubble;
    NSLayoutConstraint *_c_surprise_bubble_traling_self_bubble;
    NSLayoutConstraint *_c_surprise_bubble_top_both_bubble;
    NSLayoutConstraint *_c_translate_bubble_width_both_bubble;
    NSLayoutConstraint *_c_translate_bubble_height_both_bubble;
    NSLayoutConstraint *_c_translate_bubble_leading_both_bubble;
    NSLayoutConstraint *_c_translate_bubble_bottom_both_bubble;
    NSLayoutConstraint *_c_bubbleview_bubble_left_both_bubble;
    NSLayoutConstraint *_c_bubbleview_bubble_right_both_bubble;
    NSLayoutConstraint *_c_bubbleview_bubble_top_both_bubble;
    NSLayoutConstraint *_c_bubbleview_bubble_bottom_both_bubble;
    id <TChatViewStateProtocol> _viewStateDelegate;
    TXHoverButton *_swiftAddBtn;
}

+ (struct CGSize)sizeForAttributedString:(id)arg1 aioWidth:(double)arg2;
+ (double)_isShowNick:(id)arg1 aioWidth:(double)arg2;
+ (double)getExtendHeight:(long long)arg1 withViewModel:(id)arg2 aioWidth:(double)arg3 option:(id)arg4;
+ (double)getContentWidth:(double)arg1 viewModel:(id)arg2 sessionID:(id)arg3 option:(id)arg4;
@property(retain, nonatomic) TXHoverButton *swiftAddBtn; // @synthesize swiftAddBtn=_swiftAddBtn;
- (void)setViewStateDelegate:(id)arg1;
- (id)viewStateDelegate;
- (void).cxx_destruct;
- (void)showTranslationTips;
- (BOOL)isMessageContentTextViewInAIOBubble:(id)arg1;
- (void)replaceStrin:(id)arg1:(id)arg2:(id)arg3;
- (void)clickSwiftAdd:(id)arg1;
- (void)surpriseBtnClick:(id)arg1;
- (void)onHandleHover:(id)arg1 point:(struct CGPoint)arg2 enter:(BOOL)arg3;
- (void)onHandleClick:(id)arg1 point:(struct CGPoint)arg2;
- (void)addRevokeMenuItem:(id)arg1 belongView:(id)arg2;
- (void)addCollectMenuItem:(id)arg1 belongView:(id)arg2;
- (void)highlight;
- (void)saveSelectionRanges:(id)arg1 forView:(id)arg2;
- (id)selectionDictionaryForView:(id)arg1;
- (id)selectionRangesForView:(id)arg1;
- (void)createConstraints;
- (void)createElements;
- (void)_initUI;
- (void)_setWrapsConstraints;
- (void)setLayoutBychatType;
- (void)setSimplesModel;
- (void)setDisplayModel;
- (void)setCellLayout;
- (void)setFooterView:(id)arg1;
- (void)setContentView:(id)arg1;
- (void)addTranslateSuccessedTips;
- (void)addTranslateHandler;
- (void)checkTranslateModeByViewModel:(id)arg1;
- (void)checkTranslateMode;
- (void)setViewModel:(id)arg1 andSessionID:(id)arg2 aioWidth:(double)arg3;
- (void)setAddOne:(BOOL)arg1;
- (void)setBubbleType:(long long)arg1;
- (void)setCellBuilderOption:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

