//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChatBaseContentView.h"

@class TXHoverButton;

@interface TChatClearScreenCellView : TChatBaseContentView
{
    TXHoverButton *_loadMoreBtn;
}

+ (id)instanceFromNib;
@property __weak TXHoverButton *loadMoreBtn; // @synthesize loadMoreBtn=_loadMoreBtn;
- (void).cxx_destruct;
- (void)initUI;
- (void)setViewModel:(id)arg1;
- (void)clickLoadMoreBtn:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

