//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCollectionViewItem.h"

@class NSImageView, NSTextField;

@interface TChatHistoryCalendarItem : NSCollectionViewItem
{
    NSImageView *_bgImageView;
    NSImageView *_dotImageView;
    NSTextField *_dayTextField;
}

@property(nonatomic) __weak NSTextField *dayTextField; // @synthesize dayTextField=_dayTextField;
@property(nonatomic) __weak NSImageView *dotImageView; // @synthesize dotImageView=_dotImageView;
@property(nonatomic) __weak NSImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
- (void).cxx_destruct;
- (void)update:(BOOL)arg1;
- (void)setRepresentedObject:(id)arg1;
- (void)setSelected:(BOOL)arg1;
- (void)setSize:(struct CGSize)arg1;
- (void)awakeFromNib;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

