//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TChatCacheImage;

@protocol TChatTextAttachmentCellProtocol <NSObject>
- (void)cancel;
- (void)reloadImage;
- (void)loadImageIfNeeded;
- (long long)imageState;
- (TChatCacheImage *)cellImage;
@end

