//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class MQAvatarImageView, NSLayoutConstraint, NSTextField;

@interface TChatHisCellItem : NSTableCellView
{
    MQAvatarImageView *_avtarImgView;
    NSTextField *_nameTextField;
    NSTextField *_countTextField;
    NSLayoutConstraint *_constraintWidthCountTextField;
    id <TChatHisCellItemDelegate> _delegate;
    id _objectParam;
}

@property __weak id objectParam; // @synthesize objectParam=_objectParam;
@property __weak id <TChatHisCellItemDelegate> delegate; // @synthesize delegate=_delegate;
@property __weak NSLayoutConstraint *constraintWidthCountTextField; // @synthesize constraintWidthCountTextField=_constraintWidthCountTextField;
@property __weak NSTextField *countTextField; // @synthesize countTextField=_countTextField;
@property __weak NSTextField *nameTextField; // @synthesize nameTextField=_nameTextField;
@property __weak MQAvatarImageView *avtarImgView; // @synthesize avtarImgView=_avtarImgView;
- (void).cxx_destruct;
- (void)rightMouseDown:(id)arg1;
- (void)setBackgroundStyle:(long long)arg1;
- (void)setCount:(long long)arg1;
- (void)setupContactItem:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)awakeFromNib;

@end

