//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChatBaseViewModel.h"

@class NSString;

@interface TChatVoiceViewModel : TChatBaseViewModel
{
    BOOL _isSelf;
    int _timeLength;
    NSString *_guid;
    NSString *_filePath;
}

@property(copy) NSString *filePath; // @synthesize filePath=_filePath;
@property NSString *guid; // @synthesize guid=_guid;
@property int timeLength; // @synthesize timeLength=_timeLength;
@property BOOL isSelf; // @synthesize isSelf=_isSelf;
- (void).cxx_destruct;
- (id)attributedStringFormPasteboard;
- (void)_downloadFile;
- (id)initWithMessageModel:(id)arg1;

// Remaining properties
@property unsigned long long uin;

@end

