//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextField.h"

@class MQToolTips;

@interface TChatTextFieldTip : NSTextField
{
    MQToolTips *_toolTips;
}

- (void).cxx_destruct;
- (void)addToolTips;
- (void)setToolTips:(id)arg1;

@end

