//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseSingleton.h"

#import "QLPreviewPanelDataSource.h"
#import "QLPreviewPanelDelegate.h"

@class NSMutableArray, NSString, QLPreviewPanel;

@interface TChatPreviewPanelManager : QQBaseSingleton <QLPreviewPanelDelegate, QLPreviewPanelDataSource>
{
    NSMutableArray *_dataSource;
    QLPreviewPanel *_previewPanel;
}

@property(nonatomic) __weak QLPreviewPanel *previewPanel; // @synthesize previewPanel=_previewPanel;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (id)previewPanel:(id)arg1 previewItemAtIndex:(long long)arg2;
- (long long)numberOfPreviewItemsInPreviewPanel:(id)arg1;
- (void)showPreviewPanel:(id)arg1;
- (void)_initData;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

