//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface ThreadSafeMutableDictionary : NSObject
{
    int _lock;
    NSMutableDictionary *_dictionary;
}

+ (id)dictionaryWithDictionary:(id)arg1;
+ (id)dictionaryWithContentsOfFile:(id)arg1;
- (void).cxx_destruct;
- (id)fetchDictionary;
- (BOOL)writeToFileSyn:(id)arg1 atomically:(BOOL)arg2;
- (void)setObjectSyn:(id)arg1 forKey:(id)arg2;
- (void)setValueSyn:(id)arg1 forKey:(id)arg2;
- (id)description;
- (BOOL)writeToFile:(id)arg1 atomically:(BOOL)arg2;
- (id)valueForKey:(id)arg1;
- (id)objectForKey:(id)arg1;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)arg1;
- (id)allKeys;
- (void)setDictionary:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)dealloc;
- (id)initWithCapacity:(unsigned long long)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithObjects:(id)arg1 forKeys:(id)arg2;
- (id)init;
- (id)getPrivateMutableDictionary;

@end

