//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DevLockTlv_base.h"

@class NSString;

@interface Tlv_0x1_CommRsp : DevLockTlv_base
{
    unsigned int dwRetCode;
    unsigned int dwReason;
    NSString *sErrorTitle;
    NSString *sErrorMsg;
    unsigned short wErrorInfoType;
    NSString *sErrorInfo;
}

@property(copy) NSString *sErrorInfo; // @synthesize sErrorInfo;
@property unsigned short wErrorInfoType; // @synthesize wErrorInfoType;
@property(copy) NSString *sErrorMsg; // @synthesize sErrorMsg;
@property(copy) NSString *sErrorTitle; // @synthesize sErrorTitle;
@property unsigned int dwReason; // @synthesize dwReason;
@property unsigned int dwRetCode; // @synthesize dwRetCode;
- (void)dealloc;
- (int)decode:(char **)arg1 andBuffLen:(int *)arg2;

@end

