//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQMsgTextBlock.h"

#import "NSLayoutManagerDelegate.h"

@class MAVBubbleMessageView, NSString, NSTimer, TXAudioView, TXBubbleImageView, TXBubbleUserInfo;

@interface TXBubbleTextBlock : MQMsgTextBlock <NSLayoutManagerDelegate>
{
    int _hostSessionChatType;
    int mBubbleType;
    _Bool mIsSelf;
    NSString *mUin;
    TXBubbleUserInfo *mBubbleUserInfo;
    TXBubbleImageView *_headView;
    TXAudioView *audioView;
    MAVBubbleMessageView *_mavview;
    NSTimer *audioAnimateTimer;
    float bubbleImageAlphaValue;
    int bubbleImageAlphaCount;
    float bubbleNowPosForX;
    float bubbleTargetPosForX;
    float bubbleNowLength;
    float bubbleTargetLength;
    float bubbleExpendSpeedPerFrame;
    struct CGRect demoHeadRect;
    BOOL _isFileBubble;
    double _minHeightForFileBubble;
    BOOL _isNeedBubble;
}

+ (id)getOthersMsgBubbleColor;
+ (id)getSelfMsgBubbleColor;
+ (id)getOthersAutoReplyMsgBubbleImage;
+ (id)getSelfAutoReplyMsgBubbleImage;
+ (id)getOthersFileMsgSelectedBubbleImage;
+ (id)getSelfFileMsgSelectedBubbleImage;
+ (id)getOthersFileMsgBubbleImage;
+ (id)getSelfFileMsgBubbleImage;
+ (id)getOthersMsgBubbleImageOver;
+ (id)getSelfMsgBubbleImageOver;
+ (id)getOthersMsgBubbleImage;
+ (id)getSelfMsgBubbleImage;
+ (void)setBackgroundImage1:(id *)arg1 color:(id *)arg2 withProfileIndex:(long long)arg3 imageNameList:(id)arg4 isSelfMessage:(BOOL)arg5;
+ (void)setBackgroundImage:(id *)arg1 color:(id *)arg2 withProfileIndex:(long long)arg3 imageNameList:(id)arg4 isSelfMessage:(BOOL)arg5;
+ (void)setOthersBackgroundImage:(long long)arg1;
+ (void)setSelfBackgroundImage:(long long)arg1;
+ (void)initialize;
@property(retain) MAVBubbleMessageView *mavview; // @synthesize mavview=_mavview;
@property int hostSessionChatType; // @synthesize hostSessionChatType=_hostSessionChatType;
@property BOOL isNeedBubble; // @synthesize isNeedBubble=_isNeedBubble;
@property(retain) TXBubbleUserInfo *mBubbleUserInfo; // @synthesize mBubbleUserInfo;
@property(retain) TXAudioView *audioView; // @synthesize audioView;
@property(readonly) BOOL showHeadView;
@property(readonly, retain) TXBubbleImageView *headView;
- (void)setFileBubbleMinHeight:(double)arg1;
- (void)setIsFileBubble:(BOOL)arg1;
- (BOOL)invalidateAudioAnimateTimer;
- (void)audioShowingTimeOut:(id)arg1;
- (void)stopAudioShowingAnimate;
- (void)startShowing;
- (void)startAudioShowingAnimate;
- (void)audioRecordingTimeOut:(id)arg1;
- (void)stopAudioRecordingAnimate;
- (void)startAudioRecordingAnimate;
- (void)changeMsgHeaderColor:(id)arg1 characterRange:(struct _NSRange)arg2;
- (struct CGRect)rectForLayoutAtPoint:(struct CGPoint)arg1 inRect:(struct CGRect)arg2 textContainer:(id)arg3 characterRange:(struct _NSRange)arg4;
- (void)drawBackgroundWithFrame:(struct CGRect)arg1 inView:(id)arg2 characterRange:(struct _NSRange)arg3 layoutManager:(id)arg4;
- (struct CGRect)boundsRectForContentRect:(struct CGRect)arg1 inRect:(struct CGRect)arg2 textContainer:(id)arg3 characterRange:(struct _NSRange)arg4;
- (void)setBubbleType:(int)arg1 isSelf:(_Bool)arg2 uin:(id)arg3 UserInfoMgr:(id)arg4;
- (void)setBubbleType:(int)arg1 isSelf:(_Bool)arg2 uin:(id)arg3 UserInfoMgr:(id)arg4 fontName:(id)arg5;
- (void)dealloc;
- (void)modifyMargin;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

