//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSBezierPath, NSImage, NSString, TXBubbleUserInfo, TXTopTextView;

@interface TXBubbleImageView : NSView
{
    NSString *_uin;
    NSImage *boarderImage;
    NSBezierPath *_roundClipPath;
    unsigned long long _specialAvatar;
    TXTopTextView *topTextView;
    TXBubbleUserInfo *bubbleUserInfo;
    NSImage *_anonymousImg;
}

@property(retain) NSImage *anonymousImg; // @synthesize anonymousImg=_anonymousImg;
@property unsigned long long specialAvatar; // @synthesize specialAvatar=_specialAvatar;
@property(retain) NSImage *boarderImage; // @synthesize boarderImage;
@property TXBubbleUserInfo *bubbleUserInfo; // @synthesize bubbleUserInfo;
@property TXTopTextView *topTextView; // @synthesize topTextView;
- (void).cxx_destruct;
@property(copy) NSString *uin; // @synthesize uin=_uin;
@property(readonly) NSImage *avatar;
- (void)mouseDown:(id)arg1;
- (void)drawInRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
@property(readonly) struct CGRect contentRect;
- (void)dealloc;
- (void)removeFromSuperview;
- (id)initWithFrame:(struct CGRect)arg1;

@end

