//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImageView.h"

@class NSTimer, NSTrackingArea, TXGIFImage;

@interface TXGIFImageView : NSImageView
{
    NSTrackingArea *trackingArea;
    TXGIFImage *m_img;
    NSTimer *m_timer;
    double m_mouseEnterTime;
    int showFrameCount;
    BOOL isRunning;
}

- (void).cxx_destruct;
- (id)clippingPathWithRect:(struct CGRect)arg1 cornerRadius:(double)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)update;
- (void)dealloc;
- (void)updateTrackingAreas;
- (void)stopAnimation;
- (void)mouseDown:(id)arg1;
- (void)startAnimation;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)setImage:(id)arg1;
- (void)awakeFromNib;

@end

