//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TXImageUtils : NSObject
{
}

+ (id)makeDragImageBy:(id)arg1;
+ (id)roundWhiteBorderImageOfSession:(id)arg1;
+ (id)resizedImage:(id)arg1 toPixelDimensions:(struct CGSize)arg2;
+ (id)statusIconDeviceType:(int)arg1;
+ (id)statusIconOf:(id)arg1;
+ (void)drawRect:(struct CGRect)arg1 withImageList:(id)arg2 subImageSize:(struct CGSize)arg3 spaceBetweenImage:(double)arg4;
+ (id)imageTileByImageList:(id)arg1 imageSize:(struct CGSize)arg2;
+ (id)keyByDiscussId:(id)arg1 andChatType:(int)arg2 blocked:(BOOL)arg3 size:(struct CGSize)arg4;
+ (id)sharedInstance;
+ (id)cacheImageOfDiscussSession:(id)arg1 andChatType:(int)arg2 blocked:(BOOL)arg3 size:(struct CGSize)arg4;
+ (id)imageOfDiscussSession:(id)arg1 andChatType:(int)arg2 blocked:(BOOL)arg3 size:(struct CGSize)arg4;
+ (id)imageOfDiscussSession:(id)arg1 andChatType:(int)arg2;
+ (void)removeFromBuddyCacheWithUin:(unsigned long long)arg1;
+ (void)removeHeadImgOfGroup:(id)arg1;
+ (void)removeHeadImgOfConfGroup:(id)arg1;
+ (void)removeHeadImgOfDiscuss:(unsigned long long)arg1 WithChatType:(int)arg2;
+ (void)removeFromCacheWithKey:(id)arg1;
+ (void)removeFromCacheWithUin:(unsigned long long)arg1 onlineState:(int)arg2 size:(struct CGSize)arg3;
+ (void)removeFromCacheWithUin:(unsigned long long)arg1;
+ (id)getGroupImage:(id)arg1 size:(struct CGSize)arg2 blocked:(BOOL)arg3;
+ (id)getGroupCustomImage:(id)arg1 size:(struct CGSize)arg2 blocked:(BOOL)arg3;
+ (id)getConfGroupImage:(id)arg1 size:(struct CGSize)arg2 blocked:(BOOL)arg3;
+ (id)imageUinListOfConfGroup:(id)arg1;
+ (id)getBuddySelfHeadImage:(BOOL)arg1;
+ (id)GetStatusImageSmall:(int)arg1;
+ (id)GetStatusImage:(int)arg1;
+ (id)imageWithStatus:(int)arg1 image:(id)arg2;
+ (id)GetBigHeadImageWithStatus:(id)arg1;
+ (id)GetBigHeadImageWithNOStatus:(id)arg1;
+ (id)GetHeadImageWithUin:(id)arg1 alawysOnline:(BOOL)arg2 withStatus:(BOOL)arg3 size:(struct CGSize)arg4;
+ (id)GetHeadImageWithUin:(id)arg1 alawysOnline:(BOOL)arg2 withStatus:(BOOL)arg3;
+ (id)GetHeadImageWithUin:(id)arg1 alawysOnline:(BOOL)arg2;
+ (id)GetHeadImageWithUin:(id)arg1 status:(int)arg2 size:(struct CGSize)arg3 withDefaulImage:(id)arg4;
+ (id)GetHeadImageWithUin:(id)arg1 status:(int)arg2 size:(struct CGSize)arg3 withDefaulImage:(id)arg4 forceRefresh:(BOOL)arg5;
+ (id)GetHeadImageWithUin:(id)arg1 status:(int)arg2 size:(struct CGSize)arg3;
+ (id)GetHeadImageWithUin:(id)arg1 status:(int)arg2;
+ (id)imageOfSession:(id)arg1;
+ (id)pathForImage:(id)arg1 ofType:(id)arg2;
+ (void)getAnonymousAvatar:(id)arg1 block:(id)arg2;
+ (id)GetImageFromPath:(id)arg1;
- (void)handleNfcDiscussMemberChanged:(id)arg1;
- (void)handleDiscussMemberChanged:(id)arg1;
- (id)_imageOfDiscussSession:(id)arg1 andChatType:(int)arg2 blocked:(BOOL)arg3 size:(struct CGSize)arg4;
- (id)makeMemberUinKey:(id)arg1;
- (id)imageUinListOfDiscussSession:(id)arg1;
- (id)_cacheImageOfDiscussSession:(id)arg1 andChatType:(int)arg2 blocked:(BOOL)arg3 size:(struct CGSize)arg4;
- (id)groupImageFromCache:(id)arg1 size:(struct CGSize)arg2 bloacked:(BOOL)arg3;
- (id)init;

@end

