//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MQMsgTextBlock.h"

@interface TXInformativeTextBlock : MQMsgTextBlock
{
    BOOL _isNeedsBackgroundImage;
}

+ (void)setInformativeMsgBackgroundImage;
+ (void)setInformativeMsgBackgroundImage:(id *)arg1;
@property(nonatomic) BOOL isNeedsBackgroundImage; // @synthesize isNeedsBackgroundImage=_isNeedsBackgroundImage;
- (void)drawBackgroundWithFrame:(struct CGRect)arg1 inView:(id)arg2 characterRange:(struct _NSRange)arg3 layoutManager:(id)arg4;
- (void)adjustContentWidthWithContentDrawnSize:(struct CGSize)arg1;
- (void)setMaxYEdgeSize:(long long)arg1;
- (void)setMinYEdgeSize:(long long)arg1;
- (id)init;

@end

