//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TXAudioView.h"

@interface TXNormalAudioView : TXAudioView
{
}

- (BOOL)isFlipped;
- (void)drawRect:(struct CGRect)arg1;
- (void)refreshWithTime:(int)arg1;
- (void)setBubbleImage:(BOOL)arg1;
- (BOOL)bIsAudioFileExist;
- (id)initWithUin:(unsigned long long)arg1 andAudioPath:(id)arg2 andTimeLength:(int)arg3 isSelf:(_Bool)arg4 withGUID:(id)arg5;

@end

