//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface TXOrderedDictionary : NSObject
{
    NSMutableDictionary *_dictionary;
    NSMutableArray *_orderedArray;
    unsigned long long maxCapacity;
    NSObject<OS_dispatch_queue> *_safeQueue;
}

@property(nonatomic) unsigned long long maxCapacity; // @synthesize maxCapacity;
- (void).cxx_destruct;
- (id)lastKey;
- (id)firstKey;
- (void)removeObjectForKey:(id)arg1;
- (id)objectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (id)valueForKey:(id)arg1;
- (void)dealloc;
- (id)initWithMaxCapacity:(unsigned long long)arg1;

@end

