//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPanel.h"

@class NSView, TXPopoverController, TXPopoverWindowFrame;

@interface TXPopoverWindow : NSPanel
{
    NSView *_popoverContentView;
    BOOL useCustomFrmaeView;
    int arrowDirection;
    struct CGPoint arrowOffsetPoint;
    TXPopoverController *pPopoverController;
    TXPopoverWindowFrame *_orgFrame;
    BOOL canWindowBecomeKeyWindow;
    double _animationResizeCustomTime;
}

@property(nonatomic) TXPopoverController *pPopoverController; // @synthesize pPopoverController;
@property(nonatomic) struct CGPoint arrowOffsetPoint; // @synthesize arrowOffsetPoint;
@property(nonatomic) int arrowDirection; // @synthesize arrowDirection;
@property(nonatomic) BOOL useCustomFrmaeView; // @synthesize useCustomFrmaeView;
@property(nonatomic) BOOL canWindowBecomeKeyWindow; // @synthesize canWindowBecomeKeyWindow;
- (void).cxx_destruct;
- (void)customAnimationResizeTime:(double)arg1;
- (BOOL)detectMouseInBounds;
- (void)becomeKeyWindow;
- (void)keyDown:(id)arg1;
@property(retain) NSView *realContentView;
- (void)setContentView:(id)arg1;
@property(readonly, nonatomic) TXPopoverWindowFrame *frameView;
- (id)contentView;
- (BOOL)canBecomeMainWindow;
- (BOOL)canBecomeKeyWindow;
- (struct CGRect)frameRectForContentRect:(struct CGRect)arg1;
- (struct CGRect)contentRectForFrameRect:(struct CGRect)arg1;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4;

@end

