//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface UnloadConfig : NSObject
{
    NSString *_bundleID;
    NSArray *_selectorList;
}

@property(copy, nonatomic) NSArray *selectorList; // @synthesize selectorList=_selectorList;
@property(retain) NSString *bundleID; // @synthesize bundleID=_bundleID;
- (void).cxx_destruct;
- (id)description;

@end

