//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSStatusItem, TXStatusItemView;

@interface UnreadMsgViewController : NSViewController
{
    NSStatusItem *_statusItem;
    long long _statusIconShowType;
    TXStatusItemView *_statusItemView;
    double _maxHeight;
    long long _preUnreadCount;
}

+ (id)sharedUnreadMsgViewController;
@property(nonatomic) long long preUnreadCount; // @synthesize preUnreadCount=_preUnreadCount;
@property(nonatomic) double maxHeight; // @synthesize maxHeight=_maxHeight;
@property(retain, nonatomic) TXStatusItemView *statusItemView; // @synthesize statusItemView=_statusItemView;
@property(nonatomic) long long statusIconShowType; // @synthesize statusIconShowType=_statusIconShowType;
@property(readonly, retain, nonatomic) NSStatusItem *statusItem; // @synthesize statusItem=_statusItem;
- (void).cxx_destruct;
- (void)setImages:(BOOL)arg1;
- (BOOL)isDarkModeOn;
- (void)darkModeChanged:(id)arg1;
- (void)onMQSelfIMStatusChange:(id)arg1;
- (void)onQQUnreadMsgCountUpdate:(id)arg1;
- (void)updateUnreadMsg;
- (void)updateIconImageWithUnread:(long long)arg1;
- (void)showAioInMainThread;
- (void)showAIO:(id)arg1;
- (void)updateStatusToolTip;
- (void)reloadSystemStatusBarIcon;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

