//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "BDHUploadSegmentDelegate.h"

@class BDHUploadFileArray, BDHUploadSegMentInfo, NSString, NSTimer, UploadReqPacket;

@interface UploadRequest : NSOperation <BDHUploadSegmentDelegate>
{
    int _requestID;
    int _state;
    int _lastState;
    UploadReqPacket *_packet;
    BDHUploadFileArray *_requestData;
    BDHUploadSegMentInfo *_querySeg;
    NSTimer *_dataTimer;
    BOOL _doMain;
    BOOL _finished;
    BOOL _inProgress;
    BOOL _cancelled;
    BOOL _markCanceled;
    BOOL _markFinished;
    double _beginTime;
    NSString *_startTimeStr;
    BOOL _hasPreConnect;
    int _retryType;
    int _retryCode;
    BOOL bUserCancel;
    int _fileType;
    int _priority;
}

+ (id)descState:(int)arg1;
+ (long long)queuePriorityFromUploadPriority:(int)arg1;
+ (int)uploadRequestPriorityFromBDHFiles:(id)arg1;
+ (id)monitorState:(int)arg1;
@property(nonatomic) int priority; // @synthesize priority=_priority;
@property(nonatomic) int fileType; // @synthesize fileType=_fileType;
@property(nonatomic) double beginTime; // @synthesize beginTime=_beginTime;
@property(retain, nonatomic) BDHUploadSegMentInfo *querySeg; // @synthesize querySeg=_querySeg;
@property(retain, nonatomic) NSTimer *dataTimer; // @synthesize dataTimer=_dataTimer;
@property(retain, nonatomic) BDHUploadFileArray *requestData; // @synthesize requestData=_requestData;
@property(nonatomic) BOOL bUserCancel; // @synthesize bUserCancel;
@property(retain) UploadReqPacket *packet; // @synthesize packet=_packet;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) int requestID; // @synthesize requestID=_requestID;
- (long long)compareWithPriority:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)main;
- (void)start;
- (void)markAsFinished;
- (BOOL)isCancelled;
- (BOOL)isExecuting;
- (BOOL)isFinished;
- (BOOL)isConcurrent;
- (void)sendNextFile:(int)arg1;
- (BOOL)checkMainDone:(int)arg1;
- (BOOL)readyForRun:(BOOL)arg1;
- (float)getProgress;
- (void)applicationWillEnterBackground;
- (void)applicationWillEnterForeground;
- (void)finishAsync;
- (void)finishUpload;
- (void)cancelFileNotReport:(id)arg1;
- (void)cancelOnRequestThread;
- (void)cancel;
- (void)throwErrorCode:(long long)arg1 domain:(id)arg2 userInfo:(id)arg3;
- (void)dealloc;
- (id)initWithData:(id)arg1 fileType:(int)arg2;
- (id)init;
- (void)finishRequest:(int)arg1;
- (void)recvDataProcess:(id)arg1;
- (void)processQueryResp:(id)arg1;
- (void)printErrorLog:(id)arg1 resp:(id)arg2;
- (void)processUploadResp:(id)arg1;
- (void)resetOffsetResp:(id)arg1;
- (void)processProgressResp:(id)arg1;
- (BOOL)checkRetryLimit;
- (BOOL)checkShouldReset:(id)arg1;
- (BOOL)checkShouldRetryRetCode:(id)arg1;
- (void)rdmUploadReport:(BOOL)arg1 param:(id)arg2;
- (void)checkStatus;
- (BOOL)checkTimerState;
- (BOOL)checkFileStatus;
- (void)NotifyNoSessionAvailable;
- (void)sessionMgrNotifySendResultState:(id)arg1 session:(id)arg2 info:(id)arg3;
- (void)sessionRecvDataUpdateTimer:(id)arg1;
- (void)sessionMgrNotifyData:(id)arg1 session:(id)arg2 rspPkt:(id)arg3;
- (void)sessionMgrNotifyApnChanged:(id)arg1;
- (void)sessionMgrNotifyEvent:(id)arg1;
- (void)sessionMgrNotifyFail:(id)arg1;
- (void)sessionMgrNotifySuccess:(id)arg1;
- (void)notifyRequestCancel:(int)arg1;
- (void)notifyRequestFinish;
- (void)notifyCancel:(id)arg1;
- (void)notifyFail:(id)arg1 error:(id)arg2;
- (void)notifyPacket:(id)arg1 success:(id)arg2;
- (void)notifyProgress:(long long)arg1 total:(long long)arg2;
- (void)notifyBegin:(id)arg1;
- (void)onSegmentFailed:(int)arg1;
- (void)onSegmentTimeout:(int)arg1;
- (void)requestUploadTimeout:(id)arg1;
- (void)cancelRequestTimer;
- (void)updateRequestTimer;
- (void)startRequestTimer;
- (double)getTimeout;
- (void)retrySendSegment:(int)arg1 code:(long long)arg2;
- (void)sendRequestData;
- (void)sendSegmentPacket;
- (void)retrySendQueryPacket:(int)arg1 code:(long long)arg2;
- (void)sendQueryPacket;
- (id)getRetryQueryRequestObj;
- (id)getQueryRequestObj;
- (void)cancelQuerySegment;
- (void)throwLocalError:(long long)arg1;
- (void)throwServerError:(long long)arg1;
- (void)throwRetryError:(int)arg1 code:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

