//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet;

@interface UsedResourceScanner : NSObject
{
    NSMutableSet *_imageNames;
    NSMutableSet *_fileNames;
    NSMutableSet *_whiteList;
    NSMutableSet *_alertedNames;
    BOOL _showAlert;
}

+ (id)getInstance;
@property BOOL showAlert; // @synthesize showAlert=_showAlert;
- (void).cxx_destruct;
- (void)writeToDisk;
- (void)addFileName:(id)arg1;
- (void)addImageName:(id)arg1;
- (void)addAlerted:(id)arg1;
- (BOOL)isAlerted:(id)arg1;
- (BOOL)isWhite:(id)arg1;
- (void)stop;
- (void)start;
- (id)init;

@end

