//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class BHURLTask, MQProgerssIndicator, NSImageView, NSLayoutConstraint, NSString, NSTextField, NSView, TXColorView, TXHoverButton;

@interface VerDownloadWindowController : NSWindowController
{
    BHURLTask *_downloadTask;
    NSString *_downloadUrl;
    TXHoverButton *_installBtn;
    TXHoverButton *_btnClose;
    TXColorView *_bgView;
    TXColorView *_installView;
    MQProgerssIndicator *_progerssView;
    NSTextField *_downloadLbl;
    NSView *_downloadView;
    NSTextField *_statusLbl;
    NSImageView *_statusImgView;
    NSTextField *_downloadingLbl;
    NSLayoutConstraint *_installWidthCinstraint;
}

@property __weak NSLayoutConstraint *installWidthCinstraint; // @synthesize installWidthCinstraint=_installWidthCinstraint;
@property __weak NSTextField *downloadingLbl; // @synthesize downloadingLbl=_downloadingLbl;
@property __weak NSImageView *statusImgView; // @synthesize statusImgView=_statusImgView;
@property __weak NSTextField *statusLbl; // @synthesize statusLbl=_statusLbl;
@property __weak NSView *downloadView; // @synthesize downloadView=_downloadView;
@property __weak NSTextField *downloadLbl; // @synthesize downloadLbl=_downloadLbl;
@property __weak MQProgerssIndicator *progerssView; // @synthesize progerssView=_progerssView;
@property __weak TXColorView *installView; // @synthesize installView=_installView;
@property __weak TXColorView *bgView; // @synthesize bgView=_bgView;
@property __weak TXHoverButton *btnClose; // @synthesize btnClose=_btnClose;
@property __weak TXHoverButton *installBtn; // @synthesize installBtn=_installBtn;
- (void).cxx_destruct;
- (void)onClose:(id)arg1;
- (void)onInstall:(id)arg1;
- (void)updateInstallView:(BOOL)arg1;
- (void)download;
- (void)updateDownloadUrl:(id)arg1;
- (id)downloadFilePath;
- (void)awakeFromNib;
- (void)windowDidLoad;

@end

