//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AVFullSizeContentWindow.h"

@interface VersionIndependentWindow : AVFullSizeContentWindow
{
    id <AVMainWindowDelegate> _aioDelegate;
}

@property id <AVMainWindowDelegate> aioDelegate; // @synthesize aioDelegate=_aioDelegate;
- (void)mouseDragged:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)keyDown:(id)arg1;

@end

