//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WloginTlv.h"

@class NSString;

@interface WloginTlv_0x173 : WloginTlv
{
    NSString *sBinHost;
    unsigned short wBinPort;
    NSString *sHttpHost;
    unsigned short wHttpPort;
}

@property unsigned short wHttpPort; // @synthesize wHttpPort;
@property(copy) NSString *sHttpHost; // @synthesize sHttpHost;
@property unsigned short wBinPort; // @synthesize wBinPort;
@property(copy) NSString *sBinHost; // @synthesize sBinHost;
- (void)dealloc;
- (int)decode:(char **)arg1 andBuffLen:(int *)arg2;

@end

