//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WtBase64 : NSObject
{
}

+ (id)base64DecodedData:(id)arg1;
+ (id)base64DecodedString:(id)arg1;
+ (id)base64EncodedString:(id)arg1;
+ (id)base64EncodedStringWithWrapWidth:(id)arg1 andWidth:(unsigned long long)arg2;
+ (id)stringWithBase64EncodedString:(id)arg1;
+ (id)base64EncodedDataToString:(id)arg1;
+ (id)base64EncodedDataWithWrapWidth:(id)arg1 andWidth:(unsigned long long)arg2;
+ (id)dataWithBase64EncodedString:(id)arg1;

@end

