//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZipArchive : NSObject
{
}

+ (void)decodeDataFrom:(id)arg1 To:(id)arg2;
+ (id)gzipData:(id)arg1;
+ (void)ZipSrcData:(id)arg1 dest:(id)arg2;
+ (void)UnZipSrcData:(id)arg1 dest:(id)arg2;

@end

